### ISSUE TITLE
Stack is extremely slow for Cabal, due to custom setup script

### ISSUE THREAD

**Issue by ezyang** [commercialhaskell/stack#1041]
Stack uses runghc to run custom Setup scripts, which for Cabal means that builds are unusably slow as all of Cabal is interpreted. In these cases, I just stop having Cabal bootstrap itself because Stack is so slow in this case. I don't know, can Stack maybe build the script or something?

**Comment by snoyberg** [comment]
In principle this should be fine, there are just questions of:

1. Do we make it the default?
2. Where do we store the generate executable?

The relevant bit of code is at: https://github.com/commercialhaskell/stack/blob/11e02a8f9cddb6c24ee74648433e8706f25169a6/src/Stack/Build/Execute.hs#L690

**Comment by mgsloan** [comment]
If Setup.hs only needed to be run once, then running it in the interpreter would be a clear win over compiling it.  The issue isn't that interpreted Cabal is too slow - it isn't doing all that much heavy lifting.  The issue is that it gets re-run multiple times for a single build.  Interpreting Cabal once to build it is going to be much faster than building it twice.

I'm thinking maybe the complication isn't worth it, but it should be possible to get the best of both worlds:

```
mgsloan@computer:~/oss/haskell/cabal/Cabal$ ghci Setup.hs
...
*Main> :set args configure
*Main> main
Configuring Cabal-1.22.4.0...
*Main> :set args configure
*Main> main
Configuring Cabal-1.22.4.0...
*Main> :set args build
*Main> main
Building Cabal-1.22.4.0...
```

This is a substantially faster way to build Cabal than either `cabal install` or `stack install`.  ide-backend would let us do this very nicely, with proper handling of the output, etc.  However, I doubt we want to add a dependency on it at this point.  

Anyway, one way or another I am in favor of doing something about this.  It would be very nice for GHCJS, where the interpreter is still WIP.  In that circumstance it's even worse, because Setup.hs gets **compiled** each time it's run.  It only affects packages with custom scripts, but this is pretty bad.
