### ISSUE TITLE
Machine readable build logs

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1053]
I know this is a bit of a misfit, but it'd be nice. Having the option of having the tool dump a queryable/indexable JSON representation of the build logs would be really nice.

**Comment by borsboom** [comment]
Would this contain everything `stack` currently outputs, just in different format?  One thing we _can't_ do is make the GHC output machine-readable, so that would just have to be dumped as a big blob of text.

**Comment by bitemyapp** [comment]
@borsboom Could do it in stages, ideal would be parsing and re-emitting GHC output as the machine format.

**Comment by borsboom** [comment]
Parsing an re-emitting GHC output meant for human consumption is just asking for pain and frustration.  IMO, getting machine-readable output from GHC should be done in GHC itself.  From what I've heard, the chances of that happening any time soon are slim indeed, which is unfortunate because that'd be very useful for Stack as well.

Aside from that, I like the idea of making stack's message output more abstract, which would then make adding a machine-readable output option pretty easy.  It'd definitely be some work, but mostly pretty mechanical.

**Comment by snoyberg** [comment]
Closing as WONTFIX.
