### ISSUE TITLE
Support something like "stack ghc" and "stack runghc" for GHCJS

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1054]
There are a couple options here:

1) Make "stack ghc" and "stack runghc" use GHCJS.  One issue with this is that currently `stack ghc` and `stack runghc` are just thin layers wrapping `stack exec`.  So, this would make them quite a bit more special than before.

2) Add "stack ghcjs" and "stack runghcjs".  I think I favor this option.

**Comment by rvion** [comment]
I prefer 1: 

   - Ability to share scripts using stack independantly of if you use ghc or ghcjs
   - Less stack commands
   - Open for future ghc variant (like [haste](http://haste-lang.org/downloads/))
   - Conceptually simpler


I didn't want to propose it before, because I feel few will agree, but I also would like

 - `stack ghc` to be renamed `stack compile` (with doc saying "was `stack ghc`")
 - `stack runghc` to be renamed `stack run` (with doc saying "was `stack runghc`")
 - `stack ghci` to be renamed `stack repl` (with doc saying "was `stack ghci`")

I think standard vocabulary is better for newcomers, but also to help people conceptually understand `stack ghc` doesn't take standard ghc options. `stack ghc` takes stack specific arguments, only one of them being `--ghc-options`

**Comment by mgsloan** [comment]
Makes sense, IIRC that was also snoyberg's inclination when we discussed this quite a while back.  I'm revisiting the decision because the code changes aren't so clean as one would expect to implement (1)

**Comment by mgsloan** [comment]
Done!  I've opened this issue to track a potential renaming: https://github.com/commercialhaskell/stack/issues/1207

> stack ghc takes stack specific arguments, only one of them being --ghc-options

Actually, `stack ghc -- -ddump-splices --other-ghc-args`
