### ISSUE TITLE
Document installing native dependencies with MSYS2 WAS Specify in stack.yaml native build dependencies & install with MSYS2

### ISSUE THREAD

**Issue by NightRa** [commercialhaskell/stack#1060]
`stack.yaml` should contain a field `native-deps` which will contain a list of the native build tools and libraries required to install the package.
For example, to build Idris, the following is required on Windows:

``` yaml
native-deps:
  - make
  - gcc
  - gmp-devel
```

These libraries should be installed via `pacman` on Windows with the included MSYS2, with the following command:
`pacman -S make gcc gmp-devel --noconfirm --needed`
(`--needed` doesn't reinstall the packages if they are already installed)
Possible future expansion: installation via other package managers.

**Comment by borsboom** [comment]
I'm tempted to say this should be "out of scope" for Stack, but the Windows case is special because Stack installs its own package manager and has control over its environment.  Before continuing, let's at least think about non-Windows platforms a bit.  Some particular issues:

- On most OSs, you need root privileges to install packages.  But I don't think Stack should be running `sudo` commands, especially as stack.yaml will in many cases just come straight out of a git repo
- Different OSs will have different names for packages.  These can even vary between distribution versions
- Some OSs have multiple possible for their package manager.  E.g. OS X has brew, macports, and others

Handling all these complexities is not something I think we should be trying to reinvent in Stack.  This is configuration management territory, so having Stack be able to integrate with existing configuration management tools (e.g. chef/puppet/salt) might be a nice way to handle this.  Those systems already have ways to deal with all these complexities and are widely used.

Another way Stack already solves this sort of problem is with its Docker integration.  Of course, that's Linux-only for now.  Although native Docker support for Windows is in technical preview, so it will be possible to extend first-class Docker integration to Windows eventually.

And now, to circle back, it might still be worth implementing this as a Windows-only feature.  Stack controls the package manager and its environment, and people are much less likely to already have common dependencies installed than on other OSs.

**Comment by NightRa** [comment]
@borsboom After a second look, there are a couple of options with MSYS2 too;
1. Use the more linux-abiding ```msys``` packages - requires a dynamic library msys2.dll
2. Use the more windows-abiding ```mingw32``` or ```mingw64``` packages - doesn't require a dynamic library.

So there is also that to decide, how and when to use which.
* Stack is already shipped in 2 flavors for Windows; a 32-bit version and a 64-bit version => Decision between mingw variants is solved.

Managing native packages on Windows was one of my biggest hurdles around installing libraries in the Haskell ecosystem, so it may indeed be important to do something about this for the sake of Windows developers.

**Comment by radix** [comment]
Yeah, this is a huge can of worms. Another thing: don't forget about versioning! If you want repeatable builds, the version numbers of those packages should be specified in stack.yaml as well.

**Comment by snoyberg** [comment]
I agree that this should be considered out of scope. On the other hand, a dedicated page of documentation for these kinds of Windows issues is certainly _not_ out of scope, and can probably provide a lot of the same benefits. @NightRa interested in writing up a first draft of such a page?

**Comment by snoyberg** [comment]
No progress here, closing
