### ISSUE TITLE
Add date compiled in stack --version

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1062]
I regularly type `stack upgrade --git`. I rarely know if it worked or not, since `stack --version` just gives a revision and version. Having the date on which I compiled stack and the date at which the last commit was made would be very useful.

**Comment by borsboom** [comment]
I agree that would be handy (especially since `stack upgrade --git` can't display the number of commits due it not cloning the repo's history) and if anyone would like to add this a PR would be appreciated.  A first step might be to add support for getting the latest git commit's date into [gitrev](http://hackage.haskell.org/package/gitrev).

**Comment by GregorySchwartz** [comment]
I'll see if I can do this.

**Comment by GregorySchwartz** [comment]
This seems to be a duplicate issue of #792

**Comment by borsboom** [comment]
I guess @ndmitchell *really* wants this feature!  Closing as duplicate.

**Comment by ndmitchell** [comment]
Sorry for the noise! I keep trying out stack for an hour, raising all the things that rankle me, then putting it away for a few weeks. I think every other command I type is `stack --version` for bug reports :)
