### ISSUE TITLE
solver not considering cabal flags

### ISSUE THREAD

**Issue by eallik** [commercialhaskell/stack#1071]
when I add this

```yaml
  reactive-banana-wx: 
    buildExamples: true
```

to the `flags` section of `stack.yaml`, `stack build` starts complaining about missing dependencies (`random` and `executable-path`) and proposes adding `random-1.1` and `executable-path-0.0.3` to `extra-deps`, however, the next run of `stack build` complains about `random-1.1` and suggests something closer to `1.0.*` is needed. So I remove the 2 newly added items from `extra-deps` and try to make `stack solver` figure it out on its own. However, `stack solver` surprisingly responds with "no changes needed".

— does this mean `stack solver` doesn't take into account the `flags` section in `stack.yaml`?

**Comment by snoyberg** [comment]
Correct, that's the current behavior, since part of the solver step is to determine flags for us. It could be argued that explicit flag settings present in stack.yaml should be respected. It shouldn't be hard to implement this, want to take a crack at such a change and report how it works on your project?

**Comment by sebastianpoeplau** [comment]
I've tried an implementation (see referenced merge request). @eallik, would you mind testing how it works for your project?

**Comment by snoyberg** [comment]
Implemented by #1143.
