### ISSUE TITLE
Notify of the availability of a new lts version

### ISSUE THREAD

**Issue by ptek** [commercialhaskell/stack#1084]
It would be great if stack would notify the user if a newer lts version is available.
Maybe just for the minor versions. And maybe also about the fact that a new GHC support has arrived.

Right now one has to visit the page, follow the https://www.stackage.org/lts/cabal.config link and see if the version there is the same as one has in the project.

**Comment by cocreature** [comment]
If this gets added it should also be available for nightlies and similar stuff. However I wonder if it is really necessary to notify the users automatically. Maybe a separate command to list the stackage snapshots would be a good idea?

**Comment by ptek** [comment]
I find the way cabal-install is doing it very useful.
Often in the past I would find myself using outdated libraries, and then it turned out, that an Upgrade to newer versions was a real challenge.

Even more interesting would be to be able to see what libraries changed between the versions of lts.

**Comment by snoyberg** [comment]
What cabal-install does is quite different; it notifies of the availability of new versions of the cabal-install binary, since presumably upgrading will simply improve the user's situation without any cost (though, in reality, that's not always the case). Upgrading to a new version of LTS is not something that's always desirable, however, so Stack shouldn't nag the user to upgrade by default.

Issue #115 tracks the ability to automate some stack.yaml config, including the idea of upgrading to the newest LTS, which I think is the closest we'll get to this feature.

Note that the stackage-curator tool provides functionality for inspecting the difference between two LTS versions.

**Comment by snoyberg** [comment]
Closing, let's follow up on #115 as necessary.
