### ISSUE TITLE
Provides means of querying information about build WAS Offer command to find base directory for package

### ISSUE THREAD

**Issue by bitonic** [commercialhaskell/stack#1087]
This command, say `package-path`, would return the base directory (where the `.cabal` file lives) for a certain package, e.g.

```
$ cat stack.yaml
packages:
  - ./foo # Contains foo.cabal, package name foo
  - ./bar # Contains bar.cabal, package name bar
resolver: lts-3
$ stack package-path foo
./foo
```

**Comment by bitonic** [comment]
In the same direction, I'd like a
```
$ stack package-version foo
foo-0.1.2.3
```
@snoyberg suggested we should have a `locals` subcommand to do these queries, e.g.
```
$ stack locals path foo
./foo
$ stack locals version foo
foo-0.1.2.3
```

**Comment by snoyberg** [comment]
I thought about it a bit more, and I'm thinking we may want to create a much more generic `query` command, that could include more information in the future. Then perhaps we'd do something like:

    $ stack query locals.foo.path
    ./foo
    $ stack query locals.foo.version
    0.1.2.3
    $ stack query locals.foo
    path: ./foo
    version: 0.1.2.3

We could also have a different syntax, e.g. `stack query locals foo version`.

**Comment by borsboom** [comment]
This seems somewhat related to what @drwebb is doing with `stack config`.  At least, it may make sense for aspects of the syntax to be shared.

**Comment by snoyberg** [comment]
@bitonic I've added a new `query` command to master. With it, your original request can be handled with:

    stack query locals foo path

Please give it a shot and let me know if it works.

**Comment by bitonic** [comment]
Thanks!

**Comment by metaleap** [comment]
Just encountered this. Since searching haskellstack.org for `query` [returns only the change-log pointing to here](https://readthedocs.org/search/?q=query&project=stack&version=stable&type=file), a handful of simple questions --- if there has been a posting about this anywhere, do link!

- is the output of just `stack query`  equivalent to *all* possible scopes / queries / selectors and *all* their properties (path/version etc), or some select sub-set?

- is the output YAML or just some custom-easily-parsed-indentation-format?

- what are the additional (if any) supported scopes (other than `locals`) and properties (other than `path` / `version`)?

- this is still marked `experimental` by `stack` 1.4.0, just an oversight after 1.5 years or any caveats to beware of?

Cheers!

**Comment by mgsloan** [comment]
> is the output of just stack query equivalent to "all possible scopes / queries / selectors with all their possible properties (path/version etc)", or "some select sub-set"?

I believe it is all queriable info.

>  is the output YAML or just some stack-specific-easily-parsed-indented-lines-format?

It's YAML

> what are the additional (if any) supported scopes (other than locals) and properties (other than path / version)?

Only supports the structure of the output of plain `stack query`

> this is still marked experimental by stack 1.4.0, just an oversight after 1.5 years or any caveats to beware of?

No caveats, but it doesn't output as much info as a full fledged query feature ought to support.
