### ISSUE TITLE
Custom snapshots

### ISSUE THREAD

**Issue by feuerbach** [commercialhaskell/stack#111]
Custom snapshots are essential for me and generally important for user freedom.

By 'custom' I mean the ability to specify both custom constraints and a custom download repository.

I am happy to try to work on this myself, but wanted to find out your thoughts first.

**Comment by 3noch** [comment]
How's this coming?

**Comment by feuerbach** [comment]
Very slowly -- I haven't had time to work on this during the past few weeks, unfortunately.

**Comment by snoyberg** [comment]
If I have an opportunity to do so, you OK if I tackle this?

**Comment by feuerbach** [comment]
That'd be great.

**Comment by snoyberg** [comment]
I've done an [initial implementation](https://github.com/commercialhaskell/stack/compare/111-custom-snapshot?expand=1), available on the 111-custom-snapshot branch. Can you guys have a look and try this out? The syntax ended up slightly different than mentioned above.

**Comment by 3noch** [comment]
This looks amazing! I won't be able to test thoroughly until tomorrow. I can't wait to try it out.

I didn't realize how strongly this correlates to supporting GHC variants. Since GHC variants will often have their own version of `base`, integer library, etc., using a GHC variant will essentially beg the user to build a custom snapshot. This might be the a way to properly support `integer-simple` GHC variants, by hosting snapshots for it and allowing users to select them here. @manny-fp

**Comment by 3noch** [comment]
Could the snapshot file specify URLs for GHC bindists on each platform?

**Comment by snoyberg** [comment]
That's an interesting idea, we could consider it. I haven't thought it
through fully yet, I'm worried that it might break some invariants around
unique names

**Comment by 3noch** [comment]
What do you mean by "invariants around unique names."

I suppose to truly "normalize" the union of snapshots and compilers, you might prefer some sort of "linking table" that connects GHCs to their bindists. Then the question becomes, is commercial Haskell's "linking table" extensible/configurable like its snapshots are?

**Comment by snoyberg** [comment]
What I mean is this: the benefit we're trying to get from custom snapshots (vs just large extra-deps lists) is reusable builds. (There's also a bit of convenience in an external format, but that's much more easily achieved.) In order to make that work well, we need to have a stable mapping from *custom snapshot identifier* to *set of packages/flags*.

**Comment by 3noch** [comment]
This is a huge step forward. Thank you. I'll open another issue to document the enhancement we've been discussing.

**Comment by feuerbach** [comment]
Thanks a lot, Michael!
