### ISSUE TITLE
Failed to compile ghc-mod due to pulling in multiple version of the same package?

### ISSUE THREAD

**Issue by Javran** [commercialhaskell/stack#1167]
See build log [here.](https://gist.github.com/Javran/b778c040bcd3f81f996e)

All installed packages are [here](https://gist.github.com/Javran/d55775892c08e6fd1f58)

My stack version is 0.1.6.0 x86_64, using latest release.

I had some discussion with @DanielG on https://github.com/kazu-yamamoto/ghc-mod/issues/617 but still not sure what's wrong.

Feel free to ask for any info for troubleshoting.

**Comment by snoyberg** [comment]
Looks like a problem with your GHC installation. GHC 7.10.2 ships with transformers 0.4.2.0, but your copy ships with 0.4.3.0, thus the apparent incompatibility. The situation is worse here since the ghc package is involved, see https://www.fpcomplete.com/blog/2014/05/lenient-lower-bounds

Please try `stack --install-ghc --no-system-ghc --resolver nightly install ghc-mod` to install a pristine GHC and see if that fixes it.

**Comment by Javran** [comment]
Thanks @snoyberg it works now, probably it's not a good idea keeping haskell packages managed by system package manager .. turns out transformers got updated because of this.
Now I'll stick to `system-ghc: false` and see if it works fine.

feel free to close this issue.
