### ISSUE TITLE
stack check - verify dist tarball

### ISSUE THREAD

**Issue by wereHamster** [commercialhaskell/stack#1183]
Cabal has a command `check` which I used to verify the tarball before uploading it to hackage. Stack doesn't have such a command, and neither `sdist` nor `upload` indicate that they would run any such checks.

**Comment by borsboom** [comment]
Seems like that would be nice to add.  Perhaps `stack sdist --check` and `stack upload --check` options?  A pull request would be welcome.

**Comment by mrkkrp** [comment]
Is anyone working on this? I could try to implement it. I like the idea of `stack sdist --check` (print results of checking when creating a tarball), but how `stack upload --check` should work? Should it reject uploading if there are warnings or even worse upload package silently even if there are warnings (that's not what people would want, I guess)? Not clear.

**Comment by mgsloan** [comment]
@mrkkrp I don't think anyone is working on this, feel free to have at it!

I think both `stack sdist --check` and `stack upload --check` should refuse to perform their action if build + tests fail.  In order to reject uploading when there are warnings, we can use the `--pedantic` flag.

However, this brings up a tricky part of this - should `sdist` and `upload` get all of the flags that can be passed to `build`?  Otherwise, you won't be able to customize the build and test.  Other commands like `ghci`, which involve a build step, are likely to accept build flags in the future (https://github.com/commercialhaskell/stack/issues/1186).

However, it seems weird to have a bunch of flags in the docs which are only relevant when `--check` is passed.  Maybe the way to go is have `--check` and `--check-with "--pedantic"` - the latter form takes a list of arguments passed to the build and test steps.

Good news is that we don't have to figure out the full details of the build/test flags in order to implement  the main functionality!

**Comment by mgsloan** [comment]
See the [haddocks for Distribution.PackageDescription.Check](https://hackage.haskell.org/package/Cabal-1.22.4.0/docs/Distribution-PackageDescription-Check.html):

> This code gets uses when configuring a package when we consider only basic problems. The higher standard is uses when when preparing a source tarball and by Hackage when uploading new packages. 

I'm not sure what exactly this "higher standard" entails - does it mean that any `PackageCheck` result in the package is rejected?

If hackage is always running these checks, then we may as well have `stack upload` always run them too.  So, I think this shouldn't even require an extra `--check` flag, and perhaps that flag can instead be used for #1350.

**Comment by mrkkrp** [comment]
@mgsloan, I've tried to implement this (at least for `sdist`), but my questions are still not answered. Can you review what is already done in #1334 and give me a hint how to solve problems mentioned in comments? I planned to return to this when I have time (if it's still something you want to be implemented).

**Comment by mgsloan** [comment]
Thanks for your work on this!  I was still typing up my feedback and considering your changes, I've added that now.

**Comment by mrkkrp** [comment]
@mgsloan, Can we close this now when solution is merged?

**Comment by wereHamster** [comment]
What was the solution? Can you point me to a pull request?

**Comment by mgsloan** [comment]
Here's the PR: https://github.com/commercialhaskell/stack/pull/1334

Yup, this can be closed!
