### ISSUE TITLE
Be less verbose when extracting GHC

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1212]
Given `stack --arch i386 --no-terminal --install-ghc build`, that produces about 20K lines of output of the form `Extracting ...`. That level of output makes it impossible to find anything in my console, and also means that for CI system (e.g. appveyor) it becomes ridiculously sluggish to navigate. Perhaps pass a quieter option to 7zip? Updates every 10 seconds on how many files have been extracted so far would be fine, or a . for each file, or something else.

**Comment by ndmitchell** [comment]
For an example of sluggish and huge output https://ci.appveyor.com/project/ndmitchell/neil/build/1.0.1

**Comment by ndmitchell** [comment]
Current workaround I use is `stack setup > nul`, which produces an eclectic selection of messages. Just about enough for me to know where it's got to, but not a sensibly chosen set.

**Comment by borsboom** [comment]
I agree, it's really annoying.  I don't see a command-line option for 7z to disable all the output.  I think we'll have to swallow the stdout in [this code](https://github.com/commercialhaskell/stack/blob/193b285e0dc8fd705a7d2475e5a57bb15f4a9990/src/Stack/Setup.hs#L1141).  Might be as simple as switching to using [readProcessNull](http://hackage.haskell.org/package/stack-0.1.6.0/docs/System-Process-Read.html#v:readProcessNull) instead of `rawSystem`.  A PR would be welcome.

**Comment by ndmitchell** [comment]
A better option would be to swallow the lines and turn it into a single . per line, or even better, a single . per 1% of files.

**Comment by snoyberg** [comment]
Opened #4643
