### ISSUE TITLE
Stack exec should put cabal on the PATH

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1213]
Currently I am using `stack --install-ghc` and `stack exec` to run with GHC on my PATH. That also installs MinGW, Git etc, so it's quite a lot of Haskell tools. One tool it omits is `cabal`. I appreciate it's a competitor, but in comparison to the other tools it's trivially small, and it makes it much easier to bootstrap a Haskell environment. Plus there's an irony in running `stack exec cabal install` :)

**Comment by ndmitchell** [comment]
Looking further, I've discovered that two of my packages (ghcid and shake) both require cabal to be present in the test suite, so both these fail on a machine without cabal.

**Comment by borsboom** [comment]
If Stack's support for build-tools were less fragile, I'd suggest adding `build-tools: cabal-install` to your .cabal file to get it to install `cabal` first.  As it stands right now, though, I'm not sure that'll actually work since the package name is different than the executable name.  But having that working properly seems like it would be the right way to go forward.

If you just want `cabal`, running `stack install cabal-install` is the recommended way to install it (it'll go in your `~/.local/bin`).  If you only want it in the `stack exec` sandbox, running `stack build cabal-install` will do that.

**Comment by ndmitchell** [comment]
It's not a build-tool, so it seems wrong to declare it as such, it's a tool that I rely on being present when testing. I could `stack install` it, but since I really want it on the Appveyor CI testing stuff, that's a bit of a shame to pull down loads of dependencies for a binary. It would still be nice if `stack setup` just put it on the PATH, so `stack exec` gave me the "default Haskell environment" - but ultimately your choice, and I can certainly appreciate the reasons against doing it.

**Comment by borsboom** [comment]
>  that's a bit of a shame to pull down loads of dependencies for a binary

That's actually my main objection to having `stack setup` install `cabal`: since there are no official cabal-install bindists to we can use, it would have to pull down cabal-install's dependencies and build everything (we don't want to be in the business of maintaining cabal-install bindists ourselves).  Since in the majority of cases, people don't need `cabal` if they're using Stack, that would make `stack setup` take a lot longer for no good reason.  And while it would be possible to add a `stack setup --install-cabal`  option (off by default), I don't see the point since it's not much extra work to run `stack setup && stack install cabal-install`.

**Comment by borsboom** [comment]
Closing as "wont fix".

**Comment by ndmitchell** [comment]
Fair enough. For info, there are binary distributions of cabal, at least for Windows and I think other platforms too.
