### ISSUE TITLE
Support older version of glibc or for ease of install have a static build of stack available?

### ISSUE THREAD

**Issue by pharaun** [commercialhaskell/stack#1214]
This maybe an usecase that you folks are not interested in supporting at all but I figured I would at least ticket and document this particular usecase in case there exists others out there who has ran into this.

Basically at my workplace we are still running on top of Ubuntu Lucid which packs in a glibc version of 2.11 and this breaks the out-of-the-box experience for stack, because the provided binary depends on *min* of glibc 2.14.

I wanted to get stack so I could use the whole stack docker workflow to automatically pull down, build on a newer image and then ship a newer container (Ubuntu Trusty) with the executables.  So what I did to workaround the glibc issue was to grab alpine linux and build a static-linked musl version of stack and then share out that binary to the Lucid hosts, and then I was able to use stack to manage the docker build part of the project.

So I was wondering if there was any chance we could pack stack linking a earlier version of glibc or if it would be possible to pack it with something like musl linked in (a replacement/static replacement for glibc).

The glibc 2.14 lower bounds is probably forced by the pre-existing ghc platform binaries so I would understand if you folks didn't want to support this proposal.

**Comment by borsboom** [comment]
Yeah, we're tracking the GHC bindists when it comes to our stack bindists, since otherwise `stack setup` wouldn't work anyway.  The CentOS 6.6 binary works with glibc 2.12, not that that will help you.  Unless there's a great deal of call for supporting other versions, I don't think we're going to start releasing bindists for no-longer-maintained versions of Linux distributions.
