### ISSUE TITLE
stack solver: prompt user y/n to --modify-stack-yaml

### ISSUE THREAD

**Issue by codygman** [commercialhaskell/stack#1247]
Perhaps caching solver results could work to?

The use case is that it's more user friendly. It would also solve the case of me typing stack solver, switching to something else, then realizing I forgot --modify-stack-yaml.

Just throwing it out there, but figured I'd record it here and see what others think.

**Comment by borsboom** [comment]
Mostly we avoid making commands interactive, but we did make an exception for `stack new` because it's a command that really is meant to be a "wizard" (to borrow GUI terminology).  An argument could be made that `stack solver` (and `stack init`) could fall into that category as well.  So I'm not sold, but I'm also not deeply opposed.

**Comment by codygman** [comment]
I don't see a downside of `stack solver` being interactive. The only case I could see it being a problem is if someone were trying to get it's output and do something with it. In that case I'd argue it'd be even better to have something like `stack solver --output-only` which communicates they are only running the command for it's data and not some kind of effect.

**Comment by borsboom** [comment]
Yeah, `stack solver`'s current output isn't well suited for machine interpretation anyway.  So if someone would like to submit a PR, that'd be just fine with me.

**Comment by snoyberg** [comment]
We're going to avoid adding interactivity here
