### ISSUE TITLE
Is it possible stack not to include gcc with math functions built in on Windows?

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#1279]
I'm trying to build subhask library which depends on hmatrix. hmatrix have using external .c files that include math.h and use functions like atanh. But for some reason it give errors like:

```    [ 6 of 36] Compiling SubHask.Mutable  ( src\SubHask\Mutable.hs, .stack-work\dist\d96ab9d9\build\SubHask\Mutable.o )
    ghc.exe: unable to load package `hmatrix-0.18.0.0'
    ghc.exe: warning: _tzset from msvcrt is linked instead of __imp__tzset
    ghc.exe: D:\Projects\workspace\HL\.stack-work\install\x86_64-windows\lts-3.8\7.10.2\lib\x86_64-windows-ghc-7.10.2\hm
atrix-0.18.0.0-LvXLCIxF5ezHLYgHTbNvan\HShmatrix-0.18.0.0-LvXLCIxF5ezHLYgHTbNvan.o: unknown symbol `atanh' ```

**Comment by varosi** [comment]
Adding "m" or "libm" to extra-libraries doesn't help.

**Comment by mwu-tow** [comment]
From what I know the `atanh` and its friends are defined in the `libmingwex.a` — it is automatically linked it when building with Mingw (as GHC does behind the scenes) but GHCi library loader doesn't know about it. 
I'd try adding `mingwex` to `extra-ghci-libraries`.

**Comment by varosi** [comment]
As I know "stack build" don't use GHCi, but pure GHC build to executable and it is automatically setup to use its own MingW. Or I am wrong?

**Comment by mwu-tow** [comment]
Well, when GHC "just compiles" several files and then link them into the final executable (or library) it works basically as you said. However, sometimes during the compilation, GHC needs to execute some Haskell code contained within the sources of the package being built — usually it happens when package contains template haskell code. In such cases GHC uses „GHCi-like” mechanism to load package dependencies and evaluate the code needed to further the compilation. 

When you see messages about "loading packages" during the compilation it means that GHC does its own loading. It is a separate mechanism from the Mingw's linker and system loader and sometimes incompatibilities come up. (A typical case is having a DLL with the different filename than accompanying import library.)

In such cases `extra-ghci-libraries` entry can be used to explicitly tell GHC what libraries should be loaded.

**Comment by varosi** [comment]
I have added it into hmatrix.cabal and got that:
  [ 6 of 36] Compiling SubHask.Mutable  ( src\SubHask\Mutable.hs, .stack-work\dist\d96ab9d9\build\SubHask\Mutable.o )
  ghc.exe: warning: _tzset from msvcrt is linked instead of __imp__tzset
  GHC runtime linker: fatal error: I found a duplicate definition for symbol
     cos
  whilst processing object file
     C:\Users\Me\AppData\Local\Programs\stack\x86_64-windows\ghc-7.10.2\mingw\x86_64-w64-mingw32\lib\libmingwex.a
  This could be caused by:
     * Loading two different object files which export the same symbol
     * Specifying the same object file twice on the GHCi command line
     * An incorrect `package.conf' entry, causing some object to be
       loaded twice.
  ghc.exe: panic! (the 'impossible' happened)
    (GHC version 7.10.2 for x86_64-unknown-mingw32):
      loadArchive "C:\\Users\\Me\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-7.10.2\\mingw\\x86_64-w64-m
gw32\\lib\\libmingwex.a": failed

  Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

**Comment by mwu-tow** [comment]
Ouch. Now it has too many math functions. Well, perhaps adding the mingwex was not that good idea after all. Sorry I wasn't more of help.

I don't think this issue is related to stack. 

Recently I have spent lots of time trying to get the `cairo` bindings to work Windows. It was so painful.
The best words of encouragement I can think of are "likely there exists combination of `extra-ghci-libraries` `extra-libraries` in your package or dependencies of your pack
ion of `extra-ghci-libraries` `extra-libraries` in your package or dependencies of your package that'll make it work".
I see that hmatrix relies on C libraries (blas, lapack). You should be careful about C libraries that you expose to Haskell (if any) — when both static and dynamic version are visible, GHCi will pick the static one and GHC the dynamic. Whenever possible, avoid MSYS2 and its libraries — they often are built in a way that triggers this problem [not to say about relying on incompatible MinGW version]. 
If you use libraries compiled with MS Visual Studio (which I strongly recommend), be sure to patch your `ld.exe`  (see https://ghc.haskell.org/trac/ghc/ticket/10885 ). 

Good luck!

**Comment by varosi** [comment]
I'm linking against OpenBLAS library that is build against those MinGW libs:
http://sourceforge.net/projects/openblas/files/v0.2.15/

So you think that those DLLs contain math symbols already, but not all and when we add more via extra-ghci-libraries - it clashes?

**Comment by mwu-tow** [comment]
The OpenBLAS library package you linked contains both static and dynamic binaries:
* libopenblas.a  (static library)
* libopenblas.dll.a (import library for dll)

I believe that the actual linker will prefer the second one, while GHCi-like loader will pick the first one. It may cause issues. Or not. You can never tell with GHC on Windows.
I think such issue blocked for me for a while with Cairo until I switched to MSVC build that "just worked". Still, that'd be a bug in GHC.

However, this is not the immediate problem. The need for `atanh` comes from `hmatrix` itself, it's not related to OpenBLAS. 
I'd try making the self-contained repro first and minimizing it (eg. one Haskell package using `atanh` like hmatrix and the second one that depends on it and uses the TH), then if the issue persists, try reporting it to GHC people. [or try seeking help from someone more experieenced on IRC]

GHC 7.10.3 finally ships with an updated MinGW so it should solve some issues. You can check it out, though I doubt it will help. Also, recently GHCi loader received some fixes on Windows — they seem much more relevant but will ship in GHC 8 at best. See https://ghc.haskell.org/trac/ghc/ticket/3242

**Comment by varosi** [comment]
Thank you very much! I'll try with latest GHC, too!
atanh came from C code that comes with hmatrix and is not used in OpenBLAS.

**Comment by borsboom** [comment]
@varosi: have you established whether this is a problem with Stack
specifically or a more general problem of GHC/Cabal on Windows (i.e., if
you build with cabal-install, does the same thing happen)?

>
@mwu-tow: thanks for the help debugging this.

**Comment by mgsloan** [comment]
Since I don't think there's much more actionable here, marking this as support and closing.
