### ISSUE TITLE
Analogue of cabal repl

### ISSUE THREAD

**Issue by feuerbach** [commercialhaskell/stack#130]
IIUC `stack ghci` simply calls ghci with the stack's package db.

`cabal repl` is more than that: if run in a directory with a cabal file, it'll enable the extensions listed in the cabal file (super-useful) and also load all package's modules (moderately useful).

**Comment by hesselink** [comment]
I've never had great luck with `cabal repl`, so if `stack ghci` can improve on that, I'd love it. My use case is usually something like this: I'm developing a set of packages together, and would like to load a file from one of them in the repl. The files it depends on from its package, and preferably also the other packages in the set I'm working on, should come from source, not the package database. For anything else, the package database should be used like now.

I can see how sometimes it can be beneficial to use the compiled version of a package instead, since that speeds things up, so a flag either way looks good.

**Comment by chrisdone** [comment]
@hesselink Indeed, it seems a lot of the time one could load up GHCi with `-i./package1/src -i./package2/src` and optimistically assume the extensions will be non-conflicting. I think that `cabal_macros.h` may also cascade reasonably. 

Brainstorming, perhaps:

    $ cabal repl

* In the root directory: load up all packages specified in stack.yaml.
* In a project-specific directory: load up just that package.

    $  cabal repl foo bar

Load up the `foo` and `bar` packages together, with order being of significance for the order of `-i` and `-X`/`-XNo` specifications.

**Comment by acfoltzer** [comment]
Big :+1: to this in general, and to the improvements laid out in this thread. The biggest current pain point for me is the time it takes to `C-c C-l` after changing anything when running `cabal repl` in `haskell-interactive-mode`.

**Comment by hesselink** [comment]
@chrisdone We use a script that basically uses that approach: it adds all package source directories with `-i`, as well as all cabal macros and autogen directories. We've used it with about 30 packages at the same time, and never had trouble with conflicts between them. We don't specify extensions in cabal files (we put them in the source files instead) so I can't say anything about that.

**Comment by chrisdone** [comment]
Cool, sounds like we're all onboard with this going forward.

@hesselink We've been taking a similar approach of specifying extensions per-file too in anticipation of loading everything on at once for debugging purposes.

**Comment by ndmitchell** [comment]
Note that `ghcid` integration requires `stack ghci` to work as outlined above and load everything up. Requested at https://github.com/ndmitchell/ghcid/issues/38

**Comment by snoyberg** [comment]
This has been merged in, let's start tracking improvements in new issues.
