### ISSUE TITLE
Setting all flags to default `True` results in bad user experience:

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/stack#1313]
```
% stack install carray-0.1.6 ix-shapable-0.1.0
Run from outside a project, using implicit global project config
Using resolver: lts-2.22 from implicit global project's config file: /Users/ogre/.stack/global/stack.yaml
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      base: needed (>=4 && <5 && >=3 && >=2.0 && <2.2), 4.7.0.2 found (latest is 4.8.1.0)
    needed for package: carray-0.1.6
```

[`carray-0.1.6`](http://hackage.haskell.org/package/carray-0.1.6) has different flags, which modifies dependency on `base`. This is easy to fix by settings flags manually in `stack.yaml`, but `stack` should advice about that, as it does with missing dependencies.

**Comment by borsboom** [comment]
@phadej It does seem to be interpreting the build-depends as though all the flags are True when creating the build plan.  Perhaps it should use the default flag values from the `.cabal` file instead.  @snoyberg, any opinion about that?

Note that Stack doesn't do the cabal-install thing of trying out different permutations of flags until it finds a combination that works (and we have no plans to do so anytime soon, if ever)

**Comment by snoyberg** [comment]
I'm under the impression that we are using the default flag values by default. If not, I'd consider it a bug.

**Comment by mgsloan** [comment]
I've taken a look into this, since it was my impression that our treatment of cabal flags default to `False`.  Note that if defaults are specified, then things work fine.  Infact, `carray-0.1.6.1` adds default values the cabal file - https://hackage.haskell.org/package/carray-0.1.6/carray.cabal .

It looks like what's happening is that the `defaultFlags` [here](https://github.com/fpco/stack/blob/fd19fc674948ab07bd795a4b75843f47578e704c/src/Stack/Package.hs#L709) gets a list of flags where the defaults are `True`:

> [MkFlag {flagName = FlagName "splitbase", flagDescription = "array was in base < 3", flagDefault = True, flagManual = False},MkFlag {flagName = FlagName "bytestringinbase", flagDescription = "bytestring was included in base for 2.0 and 2.1", flagDefault = True, flagManual = False},MkFlag {flagName = FlagName "base4", flagDescription = "syb was split from base >= 4", flagDefault = True, flagManual = False}]

It seems really strange to me that `flagDefault` is set to `True`.

A couple ways to resolve this:

1) Force the default to be False when `flagManual` is `False`.

2) Add support for automatic flags.  Even though they're a rather strange default mechanism, this seems like the most "correct" approach.  It should be much easier for stack to determine these, since we fix all the dependency versions.  I'm not sure how automatic flags work in the presence of boolean operations, though, could get tricky...

Even though they're a rather strange default mechanism, maybe support should be added for automatic flags?

**Comment by snoyberg** [comment]
I'm very opposed to automatic flag detection, this is just a subproblem of
dependency solving in general, and that way leads to madness.

**Comment by mgsloan** [comment]
Indeed.  And I suppose adopting `False` as the default for automatic flags would be a major behavior change, and could break people's builds.

So, back to the specific issue @phadej brought up,  I suppose we should just warn about all the flags where `flagDefault x == True && flagManual x == False`, when failing to find a package's dependencies.

**Comment by sjakobi** [comment]
> It seems really strange to me that the cabal file parser sets flagDefault to True for flags which don't have a default value.

Actually that behavior is specified in [the cabal user guide, section "Configuration Flags"](https://www.haskell.org/cabal/users-guide/developing-packages.html#configurations):

> The rationale for having flags default to True is that users usually want new features as soon as they are available. Flags representing features that are not (yet) recommended for most users (such as experimental features or debugging support) should therefore explicitly override the default to False.

---
> I suppose we should just warn about all the flags where flagDefault x == True && flagManual x == False, when failing to find a package's dependencies.

I agree!

**Comment by sjakobi** [comment]
Here's another issue of someone who was surprised by the default flag settings: https://github.com/commercialhaskell/stack/issues/2371

**Comment by mgsloan** [comment]
Yeah, I think the current behavior is undesirable / counterintuitive.  It seems tricky to change it without breaking compatibility.

**Comment by snoyberg** [comment]
I think the takeaway from this is: if a package's dependencies fail, and it has any flags with `flagManual == False` which are not explicitly set, we can give a helpful suggestion of modifying it. If you have a different idea of what to do here, please speak up.

**Comment by snoyberg** [comment]
Closing as WONTFIX
