### ISSUE TITLE
could/should `stack exec` targets match `stack build` targets?

### ISSUE THREAD

**Issue by ghorn** [commercialhaskell/stack#1354]
When I have a library `mylib` with executables `myexe1`, `myexe2`, I can build the library with:

`stack build mylib`

and I can build specific executables with

`stack build mylib:myexe1`
`stack build mylib:myexe2`

I would like to run the executables with:

`stack exec mylib:myexe1`
`stack exec mylib:myexe2`

but I can only run them with: 

`stack exec myexe1`
`stack exec myexe2`

I'm on
```
$ stack --version
Version 0.1.6.0, Git revision e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64
```

**Comment by mgsloan** [comment]
This could be done, but I don't think it's worth it, since we'd just throw away the package name anyway.  What's the usecase?

One bad thing about this is that it would give the impression that `stack exec pkg1:same-exe-name` would do something different than `stack exec pkg2:same-exe-name`.  See https://github.com/commercialhaskell/stack/issues/1198

**Comment by mgsloan** [comment]
Closing as wontfix
