### ISSUE TITLE
Ubuntu source repository: bad URL semantics

### ISSUE THREAD

**Issue by lilred** [commercialhaskell/stack#1378]
The suggested command for adding the `stack` source repository to Ubuntu is:

    echo 'deb http://download.fpcomplete.com/ubuntu/wily stable main'|sudo tee /etc/apt/sources.list.d/fpco.list

But, from the [Debian documentation](https://wiki.debian.org/SourcesList):

>The 'distribution' can be either the release code name / alias (wheezy, jessie, stretch, sid) or the release class (oldstable, stable, testing, unstable) respectively. If you mean to be tracking a release class then use the class name, if you want to track a Debian point release, use the code name.

This semantics carries over to Ubuntu.

What I would expect instead:

    http://download.fpcomplete.com/ubuntu/wily stable main

Should be

    http://download.fpcomplete.com/ubuntu wily main

This may seem completely trivial, but it does cause certain issues with system tools - for example, deploying `stack` via `puppet` on Ubuntu is unusually inconvenient.

**Comment by borsboom** [comment]
I'll see about changing this for the next release.

>

**Comment by borsboom** [comment]
This is fixed in the release process to upload to new locations with better semantics, and I've uploaded the last three releases (0.1.5.0, 0.1.6.0, and 0.1.8.0) to the new locations as well.  The release process will, for now, continue uploading new versions to the old locations as well so that people don't need to update their sources list to get new releases.
