### ISSUE TITLE
Directories with colon `:` corrupt path - add graceful error

### ISSUE THREAD

**Issue by int-index** [commercialhaskell/stack#1387]
Stack version:
```
$ stack --version
Version 0.1.8.0, Git revision e33dd995e292efcf8ee42e1e4c649b96232abf2e (2603 commits) x86_64
```

Steps to reproduce:

```
mkdir some:dir
cd some:dir
stack new simple
stack init
stack build
stack exec -- simple-exe
```

Expected output:

```
someFunc
```

The actual output is something like this:

```
Executable named simple-exe not found on path: ["/home/int-index/Documents/some","dir/.stack-work/install/x86_64-linux/lts-3.14/7.10.2/bin", ... <omitted>
```

Possible solution: escape colons before adding the current dir to `$PATH`.

**Comment by mgsloan** [comment]
Good catch!

Unfortunately, it seems impossible to fix: http://stackoverflow.com/questions/14661373/how-to-escape-colon-in-path-on-unix

We should probably just have stack error out in this circumstance...

**Comment by borsboom** [comment]
This would be a good task for someone new to the codebase, so a pull request would be welcomed.

**Comment by int-index** [comment]
> We should probably just have stack error out in this circumstance...

Perhaps we can find a workaround? For example, create a symlink in `/tmp` and add it to `PATH` instead of the actual directory.

**Comment by mgsloan** [comment]
I'd prefer to just disallow colons in paths, it seems tricky to add special cases like this.

**Comment by int-index** [comment]
`cabal run` has no problems when run within a directory with a colon, why should `stack exec`? I don't want my build system to be limited by the output of `pwd`, honestly it sounds a little absurd.

**Comment by mgsloan** [comment]
With `stack exec bash`, you can run `compiled-exe` within the shell and actually run that one.  I haven't used cabal run much, but afaik it doesn't do that.

Your symlink solution sounds feasible, but it seems like putting in hacks to work around historical bugs.  It seems really sucky that we need to support some special modes of operation (easy to break), just because the user put their project in a subdir with `:`.  I'd rather that the code worked the same regardless of `pwd`.

I agree that having your build system be limited by the output of `pwd` is a bit absurd.  Due to this limitation of PATH, though, filepaths containing `:` are gimped and so asking for funky behaviors.  Unfortunately, there is also already precedent for being limited in the directory you place your project.  Under windows, you need to be conscious of filepath lengths due to MAX_PATH.

**Comment by borsboom** [comment]
I agree with @mgsloan.  The more hacky workarounds for weird OS issues we add to Stack, the harder it becomes to maintain and the more likely it is that something will break.  In some cases, it's worthwhile, but in this case I think just saying "don't use directories with `:` in them" is reasonable.
