### ISSUE TITLE
The documentation should be distributed together with the binaries

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#1395]
(Continuing from #1374)

As stack gains ever more commands, flags and options, it would be really handy to have html- and pdf-versions of doc/*.md locally installed together with the stack binary.

Current error messages like

```
You can try again, or create your stack.yaml file by hand. See:

    https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
```

(after a failed `stack init`)
could instead be

```
You can try again, or create your stack.yaml file by hand. For more info, run

    stack doc yaml_configuration
```

`stack doc <topic>` then opens the relevant html or pdf page (with the `--pdf` flag).

**Comment by borsboom** [comment]
Yeah, that seems like a good idea.  We should embed the docs into the executable using [file-embed](http://hackage.haskell.org/package/file-embed).  Since the docs are Markdown, they could potentially also be displayed using a pager (e.g. `less`) as well; in fact, there's already some unused code in the repo for running a pager (no idea if it works on Windows, though, but it might).

**Comment by yamadapc** [comment]
I'd say `help` is a nicer name for this command.

**Comment by mpilgrem** [comment]
I am going to close this because (a) the lack of activity and (b) modern terminal software detects URLs and automatically presents them as clickable links.
