### ISSUE TITLE
Build haddocks for dependencies

### ISSUE THREAD

**Issue by feuerbach** [commercialhaskell/stack#143]
From what I see, haddocks aren't built when installing dependencies.

It would be nice to support these use cases:

1. I only want to install an app and don't care about haddocks, don't waste my time
2. I have plenty of time, build haddocks while installing packages
3. I want to get started ASAP, so for now, only *build* the dependencies, but later I may want to run `stack  haddock` and have it build the haddocks for the dependencies (without rebuilding them, of course). In other words, be able to build haddocks on demand.

**Comment by taladar** [comment]
It might also make sense to add an option to just build the Haddocks for local packages mentioned in stack.yaml? The use-case I have in mind would be to build documentation for locally developed code on a CI server and upload it somewhere.

**Comment by manny-fp** [comment]
@taldar That's currently how `stack haddock` works and that option will definitely stay.

Question for everyone: should the default be to build haddocks for only local packages, or should the default be to build haddocks for all dependencies?

**Comment by chrisdone** [comment]
Good question, this is also relevant for providing an eventual `stack hoogle`.

**Comment by rvion** [comment]
I think the default should be to build the doc for all dependecies

**Comment by manny-fp** [comment]
Another question: for dependencies installed in `~/.stack`, we probably should put the haddocks there as well.  When linking from docs for local packages to dependencies' docs, should we:

1. Use absolute file URLs (e.g. `file:///home/user/.stack/doc/package/`)
2. Use relative file URLs (e.g. `../../../.stack/doc/package/`).  This means links would break if you move your project directory.
3. Always have the links to "../package/", and create filesystem symlinks (or fallback to copies if symlinks not available) pointing to the actual location.

The same question also applies to linking to docs for the standard libraries included with GHC.

I lean toward (3), as this makes for consistent links and makes the documentation easy to copy to a web server or otherwise move around.

**Comment by manny-fp** [comment]
And another question: should `stack haddock` also create a doc index for all packages by default?  What should be included in the index?

1. Only local packages?
2. Combine local packages and dependencies?
3. Separate indices for local packages and dependencies?
4. Both (2) and (3)?

Also, would a "master index" containing all packages installed in `~/.stack` be useful?

**Comment by rvion** [comment]
I vote for 3 ( links to ../package/) too because : 
 - ability to launch warp server to serve docs as you said,
 - ability to mount the .stack server in various docker container with different user name

**Comment by chrisdone** [comment]
> Another question: for dependencies installed in ~/.stack, we probably should put the haddocks there as well. When linking from docs for local packages to dependencies' docs, should we:

Option 1 or 3 seems pretty good. 

> And another question: should stack haddock also create a doc index for all packages by default? What should be included in the index?

Under `.stack-work`, I take it? I'm not sure what should be in the index, it's not a use-case I'm used to having. The index here means that big module listing, right? I can see either being helpful.

**Comment by manny-fp** [comment]
It would be under `~/.stack`, since it would only be for non-local packages.  It would basically give you one set of docs for every dependency you've ever used for any project.

In all this, I'm also thinking about optionally generating hoogle databases along the way, so I think the above would be especially useful for being able to hoogle a big set of packages locally.  In the case of using a Docker image with stackage preinstalled, it would give you a way to locally hoogle all of stackage.

**Comment by manny-fp** [comment]
@chrisdone Oh sorry, I answered the wrong question there!  To answer your actual question, YES, it would be in `~/.stack-work`.

**Comment by rvion** [comment]
just updated my opinion with more arguments and clarity

**Comment by manny-fp** [comment]
@rvion happy to say that we share basically the same vision

**Comment by snoyberg** [comment]
I believe this is fully implemented, closing. Please reopen otherwise.

**Comment by bitemyapp** [comment]
How do I get haddocks for my dependencies? Not seeing them in my snapshot or how to do it in this thread.

<img width="958" alt="screen shot 2016-05-18 at 6 04 17 pm" src="https://cloud.githubusercontent.com/assets/320177/15377654/fac85d08-1d22-11e6-8bc1-01dac952e81f.png">
