### ISSUE TITLE
stack setup / with ghcjs-boot

### ISSUE THREAD

**Issue by tolysz** [commercialhaskell/stack#1485]
Hi
I tried to setup ghcjs using different ways presented here but...

All tutorials assume: 
 we have a global ghc... so I had to:

    PATH=`stack path --bin-path  --stack-yaml $HOME/.stack/global/stack.yaml 2>/dev/null` stack build
    # or one from the project you actually work on 
And `boot.tar` has the same versions as ones implied by `stack.yaml` 
So I guess there should be a way to run `ghcjs-boot` with the same version of libraries as the ones derived from `resolver` ( even ones like custom  `aeson` ...)

So my question is how to do a custom `ghcjs-boot --dev` with stack

Or reimplement boot to be run each time...(unless cached)

Currently it looks like the `boot.tar` has some fixed git snapshot of libraries and they are usually different then ones from `resolver`

**Comment by mgsloan** [comment]
> we have a global ghc

Really?  `stack setup` for GHCJS is intended to also install GHC if necessary, so if a global GHC is necessary, that's a bug.

> So I guess there should be a way to run ghcjs-boot with the same version of libraries as the ones derived from resolver ( even ones like custom aeson ...)

That would be great, but it isn't straightforward because ghcjs needs to patch the boot libraries (https://github.com/ghcjs/ghcjs-boot/tree/master/patches).  An additional gotcha is that you shouldn't override these boot packages in your extra-deps / packages list, because then you won't get the patched version (https://github.com/commercialhaskell/stack/issues/1486).  Unfortunately, the unpatched version is likely to build, it just won't work correctly..

I think resolving this will require one of the two approaches:

1) Restrict stackage snapshots to use the ghcjs-boot versions of packages.  This seems like it would overly constrain things...

2) Have a separate line of snapshots which are as closely related to stackage snapshots as possible, but which fix the versions to the ones used to boot GHCJS.

Ideally, we'd just merge GHCJS support into these packages.  Then everything would be fine.

**Comment by mgsloan** [comment]
Please re-open if `stack setup` doesn't work for GHCJS when you don't have a global GHC.

(You can try this out be renaming the `.installed` file in `~/.stack/programs/x86_64-linux`)

**Comment by tolysz** [comment]
Ok; I managed to install it :)
For whatever reasons when it does not work ;( if I do not force ghc into the path.
I manually managed to patch/overwrite ghcsj boot to use the versions from lts-3.17 (only one needed to get patched); added my `aeson` and managed to boot it correctly.

So I guess; I will have to modify: https://gist.github.com/3noch/4696feff5c602e126681
to:
* patch .cabal to include version (or even a hash of boot?)
* substitute  /boot/*  (inside boot.tar) with versions from `resolver` (possibly applying patches)
* repack and boot
 
But to me it looks like we could use the same version (say 0.2) as base and have multiple boot directories which could be only dependent on `stack.yaml` currently their locations seems to be very much linked to the version name. 

So maybe `stack` should be able to say which `boot`-dir `ghcjs` should use. and maybe set-up one per project.
So again `stack` should allow to run only ghcjs-boot with a given `boot.tar` and store output per hash of constraints used to build it.

More, I think this way will force the `upstream` to take patchs to support `ghcjs` more serious
and we could drop boot altogether.
