### ISSUE TITLE
Stack doesn't install PO files properly

### ISSUE THREAD

**Issue by volhovM** [commercialhaskell/stack#1508]
There's a related problem [here](https://github.com/vasylp/hgettext/issues/7). 
[Distribution.Simple.I18N.GetText](https://hackage.haskell.org/package/hgettext-0.1.30/docs/Distribution-Simple-I18N-GetText.html) is common to work with locales and translations. It overrides cabal hooks in order to install `.po` files to `/usr/share/locale/...`.
This feature still works well with stack 0.1.6.0, but not anymore in version 0.1.8.0. In 0.1.6.0 .po translations are copied to `.stack-work/.../share/...` on `stack build`, but with new version it doesn't happen.

**Comment by mgsloan** [comment]
Yes, `stack build` now invokes Setup.hs copy and register instead of running Setup.hs install.  This means `postCopy` gets invoked instead of `postInstall`.  Here's the issue that caused this change: 
https://github.com/commercialhaskell/stack/issues/1203 .  IIRC, it's also what `cabal install` does?

Here's how to implement `postInstall` in terms of `postCopy`: https://github.com/ghcjs/ghcjs/commit/d5c67ef30c2ed1e39f6cc2555a5ec86d2ad566a1

**Comment by mgsloan** [comment]
Please re-open if there's something stack can do better here.  Unfortunately, there's not much we can do about the postInst / postCopy stuff.
