### ISSUE TITLE
apt package for debian unstable

### ISSUE THREAD

**Issue by ghorn** [commercialhaskell/stack#1519]
There are currently debian packages for debian 7 and 8: http://docs.haskellstack.org/en/stable/install_and_upgrade.html#debian

It would be great to add a package for debian sid/unstable

**Comment by borsboom** [comment]
Have you tried the jessie packages?  There's a good chance they'll work fine.  We don't usually make packages for unstable platforms, although if jessie's done work on sid then it might be worth doing.  Note, however, that if a stack build from jessie doesn't work on sid, chances are that GHC won't either (since the GHC bindists are built on jessie (ghc-7.10.3) or wheezy (ghc-7.10.2).

**Comment by borsboom** [comment]
Another option would be to get Stack included in the official Debian repos.  It'd be great if someone with more knowledge of Debian packaging could take a stab at that (the current FPM-based approach we use to generate .debs isn't going to be good enough).

**Comment by ghorn** [comment]
I tried the jessie one and it seems to work fine. If you are confident it will keep working in the future, it's probably worth it to update the stack installation documentation to mention this.

**Comment by ghorn** [comment]
:+1:
