### ISSUE TITLE
List available "new" templates along with descriptions

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1571]
It'd be nice to get a list of available templates, via something like `stack new --list` or `stack templates`.  Ideally, these templates would be accompanied by a short description.

Split off from #1564

**Comment by kadoban** [comment]
Any thoughts on how that should be implemented? I'm attempting to implement some more changes to 'new' at the moment and if I could roll that in it sounds like a really nice addition.

I guess it'd have to require some kind of addition to the template format, ideally something backwards compatible? Maybe there could be a specially named file in the template that if it exists is displayed for that purpose and otherwise not used? That sounds a bit hacky, but should work and nothing else really comes to mind.

**Comment by mgsloan** [comment]
Yeah, a file like `new-template.txt` or `new-template.desc` makes sense to me.

**Comment by mgsloan** [comment]
I think the best implementation would be based on resolving https://github.com/commercialhaskell/stack/issues/1595 .  So, marking this as blocked on that issue.

**Comment by mgsloan** [comment]
An alternative implementation not blocked on #1595 would be to have a single file in the templates repo that associated template names with descriptions / other metadata.  This might actually be preferable to putting the description in a separate file.

Marking as unblocked.

**Comment by mgsloan** [comment]
This got addressed by @narrative.  Thanks!
