### ISSUE TITLE
Use global --resolver option parsing for stack init

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#1588]
`stack init` implements its own `--resolver` command line option which seem to be doing exactly the same thing as the global `--resolver` option implementation.

We can avoid this duplication by deleting the parsing code in [initOptsParser](https://github.com/commercialhaskell/stack/blob/1faf121b14b165234676abd1fc1f28c75a302db7/src/Stack/Options.hs#L697) and passing the resolver value from globalOpts in [initCmd](https://github.com/commercialhaskell/stack/blob/3c3876cbed726c534fcd4db5b2d8cfcc33cd7819/src/main/Main.hs#L1176).

See also #1531.

**Comment by mgsloan** [comment]
Makes sense!

**Comment by borsboom** [comment]
`stack init`'s --resolver is slightly different because it selects the behaviour (note the usage has `([--solver] | [--resolver RESOLVER] | [--prefer-lts] | [--prefer-nightly])`), so fixing this may be a bit more involved as you'll have to ensure none of the other local options (--solver, --prefer-lts, --prefer-nightly) were given if the global --resolver is set.

**Comment by harendra-kumar** [comment]
Ah, I missed this point earlier. 

The init options have changed a bit with PR #1583 though. --resolver can now be specified with --solver. So we have to take care of --prefer-lts and --prefer-nightly only, but that does not change the order of effort.

```
Usage: stack init ([--resolver RESOLVER] | [--prefer-lts] | [--prefer-nightly])
                  [--solver] [--force] [--ignore-subdirs] [--help]
  Initialize a stack project based on one or more cabal packages
```
