### ISSUE TITLE
ghc-paths and other installation directories are hard-coded on Windows

### ISSUE THREAD

**Issue by hherman1** [commercialhaskell/stack#1644]
This honestly wouldn't be a problem except that the sheer nesting depth is causing node.js/ghcjs to fail at compiling ghcjs-dom. It'd be nice if ghc-paths and others depended on STACK-ROOT, or were at least somehow variable.

**Comment by borsboom** [comment]
Agreed.  I think the GHC paths were set where they are to be "friendly" to the Windows way of doing things, but it ends up with really long paths which are so troublesome.  There should at least be a way to change it.  You might try changing the `LOCALAPPDATA` environment and see if that helps, but I don't think that's a great workaround (since lots of other things use that variable as well).  A pull request would be welcome (the relevant code is [here](https://github.com/commercialhaskell/stack/blob/0ea6d9c78bac544a4c1d259e43e0e891391ca4f5/src/Stack/Config.hs#L325)).  Making the location configurable in STACK_ROOT\config.yaml is probably the right way to go (rather than use an environment variable).
