### ISSUE TITLE
Some way to pass in test arguments

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#172]
See: #170

**Comment by snoyberg** [comment]
We decided to treat this like `stack exec` and family, and just pass in the extra command line arguments to the test suites.

**Comment by snoyberg** [comment]
And that's not going to work, because those arbitrary arguments are used to indicate the targets. OK, will revert to --test-args (or --test-options for consistency with --ghc-options?).

**Comment by gregwebs** [comment]
`--test-options="TESTOPT"` is a pain because it introduces new quotation rules. I would find it a lot easier to use a `-` to indicate the end of stack args.

   stack test TARGET1 - TETOPT1

The main problem with this approach is it is harder to document; that mat favor supporting both styles

**Comment by gregwebs** [comment]
This approach is already taken by `stack ghc` https://github.com/commercialhaskell/stack/issues/258

**Comment by snoyberg** [comment]
The double dash in the arguments is a shell-ism to mean "don't interpret anything else as flags," so using it to distinguish between targets and test arguments feels incorrect. That's not to say that I don't like the idea in theory.

**Comment by gregwebs** [comment]
Again, I believe this is the exact same thing that is done for stack ghc mentioned in #258. It is correct in that the options being passed in are no longer treated as flags, but instead just as normal strings. But we are adding a new meaning that the arguments are different then the ones before `--`. They are not directly used by the command but passed on to the underlying one.

However, we can argue that
* one can never know how the bare double dash will be interpreted without looking at the command documentation because not all commands support it, in which case it will be erroneously used as an argument
* other commands already co-opt it for additional meaning. with git, one can use it to differentiate between files and branches
http://stackoverflow.com/questions/13321458/meaning-of-git-checkout-double-dashes

The question for me is: can a target begin with dashes? Would anyone ever think of doing that? If not (which I believe is the case), this seems ok to me. For the similar `stack ghc` issue, it appears that ghc does not support the bare double dash.

**Comment by chrisdone** [comment]
For now we'll just use `--test-arguments="<args here>"`.

**Comment by chrisdone** [comment]
Implemented. 

* Please see 64cd13b for the argument list parser.
* See 2736115 for the pass-through to the test suite.

Demonstration:

```
chris@retina:~/Work/stack$ stack test 
stack-0.0.2: test (suite: stack-test)
[snip]
  C-c C-c user interrupt
chris@retina:~/Work/stack$ stack test --test-arguments "x y z"
stack-0.0.2: test (suite: stack-test, args: x y z)
stack-test: unexpected argument `x'
[snip]
chris@retina:~/Work/stack$ stack test --test-arguments "\"x\" y z"
stack-0.0.2: test (suite: stack-test, args: x y z)
stack-test: unexpected argument `x'
[snip]
chris@retina:~/Work/stack$ stack test --test-arguments "\"x p\" y z"
stack-0.0.2: test (suite: stack-test, args: "x p" y z)
stack-test: unexpected argument `x p'
[snip]
chris@retina:~/Work/stack$ stack test --test-arguments "\"x\" y z\""
option --test-arguments: unterminated string: endOfInput
```

**Comment by chrisdone** [comment]
Passing to @snoyberg to review and then probably @gregwebs to also review and try out.

**Comment by gregwebs** [comment]
I don't actually have a use case for this right now although I have needed it in the past.

**Comment by luochen1990** [comment]
@gregwebs I think it is a good use case that when you use hspec & quickcheck, you want to specify the number of random tests, you can use this ` stack test --test-arguments "-a 1000"`
