### ISSUE TITLE
Print Cabal and other "external tool" dependency version in --version

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/stack#1800]
Compare to
```
% cabal --version
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library 
```

Related also to #1679 #1773

I could implement this, if the idea is ok.

**Comment by mgsloan** [comment]
`cabal-install` outputs those two versions because it's linking in a particular version of the `Cabal` library, and the format of the dist dir depends on the Cabal library version.

With `stack`, we really don't link anything in that matters in quite that same way.  Outputting say, the ghc version, requires parsing in the `stack.yaml` to determine which ghc to use, so I don't think it fits with a command like `stack --version`.

How about something like `stack query tools`, which would yield yaml formatted info about all the tool versions you might care about. `stack query tools ghc` could yield the version number, or something like that.

**Comment by phadej** [comment]
@mgsloan isn't `Cabal` used to parse `.cabal` files, so the version might influence what features are recognised there?

Also `hpack` will be used as library, and not thru call to the external tool?

**Comment by borsboom** [comment]
The linked Cabal is only used to parse the parts of the .cabal files that
are relevant to Stack itself to come up with a build plan (e.g. figuring
out the dependency graph), but not when actually configuring/building a
package.

**Comment by mgsloan** [comment]
True, by using `hpack` as a library, changes to its format could cause compatibility issues.  Since hpack itself and the inclusion in stack is experimental, I think this is ok.  If such compatibility issues become a concern, then

Note that it still isn't quite as big of a deal as the `Cabal` situation, because the library needs to match the dist dir contents.  Whereas in the case of hpack, it just depends on how well it maintains forwards and backwards compatibility.

**Comment by sol** [comment]
In the case somebody wants to add the `hpack` version, it is already exported from the `Hpack` module.

**Comment by mgsloan** [comment]
Implemented by @phadej at https://github.com/commercialhaskell/stack/pull/2037
