### ISSUE TITLE
No way to disable hpack running

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/stack#1813]
If I have used non-upstream version of hpack, now I'm forced to also use non-upstream version of stack - as I cannot disable regeneration of `cabal` files.

This now breaks many of our CI builds as they pull the latest stack binary in. Some of cabal files are generated with patched `hpack` or manually edited afterwards.

**Comment by phadej** [comment]
I don't know how to fix the issue. Maybe we should add file-edition-time checks after all?

**Comment by simonmichael** [comment]
I think it regenerates even if the cabal file has a newer timestamp than the hpack file, which is perhaps unintuitive and was inconvenient for #1814.

**Comment by mgsloan** [comment]
Perhaps this is one reason to use hpack as an external binary, as discussed in https://github.com/commercialhaskell/stack/issues/1800 .  If we do really care about the process invocation overhead, we could do the following:

* Invoke `hpack` as an external process if it exists, and otherwise use the hpack library that's been compiled into `stack`.

**Comment by mgsloan** [comment]
Having a `--[no-]hpack` flag would be a fine addition.

**Comment by sol** [comment]
I agree that a `--[no-]hpack` flag would be something useful.

Regarding manual editing cabal files, I understand that this is due to missing features in `hpack` and I'm sorry for that.  @phadej I'm trying to somehow free up the time to get the missing stuff on `master` (most importantly conditionals + flags I assume).

**Comment by phadej** [comment]
I can work on `--[no-]hpack` flag. The major problem is that `findOrRegenerateCabalFile` and all it's callers would need to pass thru `HpackOpts` or some other structure. 

I'm not sure how to do that, is adding `MonadReader env m, HasHpackOpts env` to the call chains ok approach?

Why `HpackOpts`? even it would be on/off currently, you never knows when `hpack` get's new optional features we might want to have (e.g. optionally generating version bounds).

**Comment by phadej** [comment]
@sol and @mgsloan, sorry for me being impatient :)

**Comment by mgsloan** [comment]
I'd probably put it in `GlobalOpts`.
