### ISSUE TITLE
Build only some of the Docker images

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#1837]
Currently, `stack image container` always builds all images specified in your stack.yaml file. It would be convenient in some use cases to give a list of Docker images that should be built instead.

**Comment by mgsloan** [comment]
@dysinger I merged the PR before realizing that it takes these image names via an undecorated argument.  I don't think this is what we want, because in the future we might also want to take TARGET syntax like the normal build command.

How about putting this option under a flag like `stack image container --name` or `stack image container --image` or something?

**Comment by dysinger** [comment]
How would multiple images look? `stack image container --image black --image orange --image red` ?

**Comment by mgsloan** [comment]
Yup, or possibly also `stack image container --image "black orange red"`

**Comment by dysinger** [comment]
It seems reordering tickets on waffle.io adds back the "in progress" label

**Comment by borsboom** [comment]
It looks like this issue can be closed.  Please reopen if I'm incorrect.
