### ISSUE TITLE
How do I get Stack to use the correct Haddock?

### ISSUE THREAD

**Issue by ChristopherKing42** [commercialhaskell/stack#1868]
1. stack haddock for [network-uri](https://github.com/haskell/network-uri) clone

I was hoping it would download a haddock that was compatible.

It said that haddock was at GHC version 7.8.1 but the version in use was 7.8.3

```
$ stack --version
Version 1.0.4.1 x86_64
```

```
$ stack haddock
network-uri-2.6.0.3: build
Preprocessing library network-uri-2.6.0.3...
In-place registering network-uri-2.6.0.3...
network-uri-2.6.0.3: haddock
Running Haddock for network-uri-2.6.0.3...
setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: Haddock's internal GHC version must
match the configured GHC version.
The GHC version is 7.10.3 but haddock is using GHC version 7.10.1

--  While building package network-uri-2.6.0.3 using:
      /home/theking/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux/
Cabal-1.22.5.0 haddock --html --hoogle --html-location=../$pkg-$version/ --hyperlink-source
    Process exited with code: ExitFailure 1
```

Is there a way to get stack to use the right haddock?

**Comment by mgsloan** [comment]
Haddock gets installed with GHC, so this should only happen when you're shadowing the correct version of haddock with a local install.  What do `stack exec -- which ghc` and `stack exec -- which haddock` say?  I'm guessing it's using your system install of GHC, along with a haddock that got installed manually.

This is one of the reasons it's good to use the ghc installed by `stack setup` instead of a system install, because then that dir will be near the top of the PATH used when running, and you will get consistent versions of these tools.  Infact, maybe we should reverse [this decision](https://github.com/commercialhaskell/stack/issues/1129), and default to ignoring the system ghc.  This default could be overridden in config.

Oh, and if you want to solve this without mucking around with PATH or your ghc installs, just do `stack build haddock` and it will get installed to your project's bin dir, and be available during subsequent builds (but only for that project).

**Comment by mgsloan** [comment]
There was also [this mailinglist thread](https://groups.google.com/forum/#!topic/haskell-stack/-XaXiq5Wdo8).  I'm not sure if protecting people from the system configuration is worth the behavior change..

One option might be to leave `system-ghc: true` as a default, but start generating `~/.stack/config.yaml` with `system-ghc: false`.  This way, people who have old configurations won't see a behavior change, and new users will be guided towards having stack install ghc.  Perhaps initializing config with a non-default value is rather unexpected, though. 

Anywho, I'm interested in whether it does turn out to be a system GHC issue, as this'd be one more issue in the direction of changing the default.

**Comment by mgsloan** [comment]
The latest version of stack defaults to not using the system GHC!

Closing this, as it's an old support ticket.  If you think this is in error, please comment with more info.
