### ISSUE TITLE
"stack setup" fails with "Permission Denied" error

### ISSUE THREAD

**Issue by ismail-s** [commercialhaskell/stack#1880]
*Steps to reproduce*
1. Download the latest Stack installer, install it somewhere.
1. Run "stack setup"

*Expected*
Command runs successfully

*Actual*
Get a "permission denied" error:
![image](https://cloud.githubusercontent.com/assets/3778413/13571276/e03ad974-e46b-11e5-9129-3cff34642aac.png)

*Additional*
- I am running this command on a uni computer. My hope was that I would be able to install ghc in some form in my documents (ie a portable install).
- My original idea for fixing the error in the above screenshot was that it should be configurable where ghc is installed to, as opposed to hardcoding it. But I am not sure that that would fix my issue, as the dowloaded ghc thing is over a 1GB in size (I expect others have complained about this before, and I am now too) and my uni quota is only 1GB.

So:

1. I am not sure that I can see a reasonable solution to this issue from that perspective. Feel free to close this if that makes the most sense, but I thought it important to report any errors I encounter.
1. I have a feeling that my protestations that the download is too big will not be enacted on, simply because other people _must_ have mentioned this already as an issue.
1. I'll probs just have to mention it to IT people at uni that they should install ghc.

**Comment by mgsloan** [comment]
> I am running this command on a uni computer. My hope was that I would be able to install ghc in some form in my documents (ie a portable install).

On windows, this is based on `LOCALAPPDATA` env var, rather than being put in the dir specified by the `STACK_ROOT` env var.  If you can unset `LOCALAPPDATA`, this should cause it to put ghc under STACK_ROOT (but it needs to be unset for all stack invocations).

> But I am not sure that that would fix my issue, as the dowloaded ghc thing is over a 1GB in size (I expect others have complained about this before, and I am now too) and my uni quota is only 1GB.

Yeah, you're going to need quite a fair amount more than 1GB to install all this stuff :/  

> 2. I have a feeling that my protestations that the download is too big will not be enacted on, simply because other people must have mentioned this already as an issue.

I'm not sure how much of a priority keeping ghc's size down is.  Such things are always a balance between where development effort goes.  Lots of folks have huge hard drives and fast internet connections, so for many, the size doesn't matter very much.

> 3. I'll probs just have to mention it to IT people at uni that they should install ghc.

Yup, that'd be a good idea!

**Comment by ismail-s** [comment]
Thanks for the quick reply.
