### ISSUE TITLE
Support pulling templates from paths in git repos

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1980]
From the terraform documentation:

```
$ terraform init github.com/hashicorp/terraform/examples/aws-two-tier
```

I rather like this as it is flexible and means you can have more than one template in a repository without requiring it to be located anywhere in particular. I think having stack-templates be the initial namespace is fine, but something like this would help with the "I want private company templates" use-case.

**Comment by mgsloan** [comment]
Good idea!

For the "I want private company templates" use-case, I think the best solution would be to have a configuration field that specifies a repo / dir of additional templates.  

Tangent:  Way down the road, we might even want to specify this field within a project itself, in order to specify a set of templates for a particular piece of functionality (e.g. adding a yesod handler).  Not sure how well that works out, since I imagine many of these templates would be package specific rather than project specific.

A different approach would be to implement #1595, but do so in such a way that it allows you to also use your own repos of templates.  For example, the default repo of templates would go in `~/.stack/templates/default/` or something.  If you add a `~/.stack/templates/proprietary` folder, then it's used.

An advantage of the configuration based approach is that if pointed at a git repo, it could auto-pull it, just like it needs to for the default template repo.

**Comment by harendra-kumar** [comment]
Should we rename the label `component: init/solver` to `component: new/init/solver` instead? They are all closely related.

**Comment by mgsloan** [comment]
@harendra-kumar Sure, renamed!

**Comment by snoyberg** [comment]
This is now supported in the `new` command.
