### ISSUE TITLE
Remove the password from the GnuPG test key in etc/docker/stack-base/.gnupg/

### ISSUE THREAD

**Issue by dysinger** [commercialhaskell/stack#2006]
To make testing easier, let's remove the password from the GnuPG key used for testing in the etc/docker image

**Comment by maxnordlund** [comment]
Won't this expose a backdoor, especially since the keys have been [committed](https://github.com/commercialhaskell/stack/tree/692f6ff73de8bf7354488469c89565114842710b/etc/docker/stack-base/.gnupg) to this repo, and the [default password](https://github.com/commercialhaskell/stack/blob/692f6ff73de8bf7354488469c89565114842710b/etc/docker/stack-base/Dockerfile#L55) as well?

Overall, I don't think shipping any sort of trusted keys is a good idea, and instead why not use a second image that adds just that for development of the image themselves?

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time without further activity.
