### ISSUE TITLE
Hpack annoyances (duplicated logs, doesn't take target into account, re-generate on clean, etc.)

### ISSUE THREAD

**Issue by rvion** [commercialhaskell/stack#2011]
Hello, 
I use stack in conjunction with hpack.
here is a list of small annoyance I have found with hpack support in stack:

  1. building __one specific__ component will regenerate cabal files for __all components__
    ```bash
    foo$ stack install app --fast --file-watch
    /Users/rvion/dev/foo/lib/lib.cabal is up-to-date
    /Users/rvion/dev/foo/app/app.cabal is up-to-date
    ```

  2. stack will regenerate cabal files / print info __once per target in each package (lib, executable)__
    (or something like that, but either: 1 - there is log duplication or 2 - log is incorrect / not complete)
    ```bash
    foo$ stack install app-and-lib --fast --file-watch
    /Users/rvion/dev/foo/app-and-lib/app-and-lib.cabal is up-to-date
    /Users/rvion/dev/foo/app-and-lib2/app-and-lib2.cabal is up-to-date
    /Users/rvion/dev/foo/app-and-lib/app-and-lib.cabal is up-to-date
    /Users/rvion/dev/foo/app-and-lib2/app-and-lib2.cabal is up-to-date
    ```

  3. stack ouput hpack info / debug like `foo.cabal is up-to-date` even when I don't specify any verbosity level
    I think those informations are always so usefull.
  
  4.  `stack clean ` and `stack clean --full` will regenerate cabal files.
    Should it ?

The reason I opened this issue is that because of (1), (2), (3), stack print dozens for each file change when I `stack build component --file-change` unless I fight against stack by manually running hpack

**Comment by rvion** [comment]
for ref, here is [an other issue related to hpack](https://github.com/commercialhaskell/stack/issues/2001)

**Comment by rvion** [comment]
implementation was done here: https://github.com/commercialhaskell/stack/commits?author=sol
ping @sol in case he has a few pointer to give about implementation

**Comment by sol** [comment]
## Alternative approaches

My original implementation makes sure that the cabal file is up-to-date when ever we look for a cabal file (specifically when we call `findOrGenerateCabalFile`), which results in the behavior you describe.  There may be other approaches that don't have those issues.  I'll not have time to explore this, but if somebody is tackling this and requires changes to `hpack`, I'd be more than happy to help with that.

## Tuning the output of `hpack`
If we want to stick with the current implementation, and want to tune the output generated by `hpack` instead, then I think it makes sense to think about what exact behavior we want.

`hpack` can generate three different *status messages* and *warnings*.  The three status messages are:

1. `generated hpack.cabal`
2. `foo.cabal is up-to-date`
3. `foo.cabal was generated with a newer version of hpack, please upgrade and try again.`

Warnings are things like `WARNING: Ignoring unknown field "foo" in package description`.

Currently, we can choose to silence all status messages by passing `False` instead of `True` when we invoke `hpack` (see https://github.com/commercialhaskell/stack/blob/d631a20c2a3ea404710292a5ce1b1d60b6573feb/src/Stack/Package.hs#L1149).

Warnings are always written to `stderr`.  Currently there is no way to silence warnings.

If we want something different, e.g. only print status messages (1) and (3), but never (2), we need to make changes to `hpack`.  So again, if we want to tune the output, let's think about what exact behavior we want.  I would then be happy to make the required changes to `hpack` (or accept PRs, in case somebody else wants to do it).

**Comment by rvion** [comment]
thanks for your detailed answer.
I see no fast & simple alternative that everybody will agree on easilly.

here is a pr that would help me: https://github.com/sol/hpack/pull/89

**Comment by soenkehahn** [comment]
I would prefer `stack` to never output status (2) `foo.cabal is up-to-date`. I would still want `hpack` to output that status if invoked standalone, however. This might not solve all problems at once, but should be a non-controversial change, I hope.

I wouldn't change how warnings are reported atm.

**Comment by mgsloan** [comment]
Agreed, I've reduced the output to just warnings with the following PRs:

https://github.com/sol/hpack/pull/95
https://github.com/commercialhaskell/stack/pull/2097

**Comment by mgsloan** [comment]
I think the overall issue is resolved.  Please open other issues if not.
