### ISSUE TITLE
Rebuilding when disabling profiling

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/stack#2023]
Currently running `stack build --profile` and then `stack build` triggers unregistering and rebuilding of all dependencies. It's not supposed to do that.

**Comment by mgsloan** [comment]
Oh man, I didn't realize that list existed.  I've moved it next to the options generation code - https://github.com/commercialhaskell/stack/commit/75294ebef5cf7c6c6f540a9c4946cdba30d344b6

Is `isStackopt` still an apt name? As far as I understand it, these are all the options that shouldn't cause package rebuild dirtiness.  This can either be because we know through a different mechanism that we need to rebuild the package when it's due to say, a dependency change.  Similarly, when resolving dependencies for a profiling build, it only considers packages that are built with profiling.

So based on this, I'm thinking options like `extra-lib-dirs` and `extra-include-dirs` shouldn't be in the list?  These options come from the stack.yaml and changing them should cause a rebuild.

**Comment by chrisdone** [comment]
Right, there's a different mechanism to trigger building all the profiling packages when we enable profiling, so this doesn't need to be in this list. But beyond that I'm not sure about the other options.
