### ISSUE TITLE
"stack sdist" does not include stack.yaml file by default

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#2105]
Currently when I do "stack sdist" it include *.cabal files, but doesn't include stack.yaml. So after distribution I cannot build what's in the archive with stack anymore.

Stack version 0.1.8.0 x86_64

**Comment by mgsloan** [comment]
@varosi Since sdists are typically used for hackage, they do not need to include stack.yaml files.  That said, I can see it being valuable metadata to include.

I can think of just one potential downside, which is that if you `stack unpack` a package into your project, and then cd into it, you might expect `stack build` to build the project you're working on, and not the inner stack.yaml.  One solution to this could be to warn when there are multiple stack.yamls on the path.

I think the upsides outweigh the downside, I'm in favor of making that change.

Also, that stack version is old, you should probably upgrade.

**Comment by borsboom** [comment]
You can also put this in your `.cabal` file:

```
extra-source-files: stack.yaml
```

**Comment by varosi** [comment]
@borsboom, Thanks! 

@mgsloan, it will be really great! Because I hit this problem for the second time.

**Comment by seagreen** [comment]
Yikes, that will be confusing for people who didn't intend to include `stack.yaml` in their upload.

**Comment by varosi** [comment]
I'm just giving it "stack sdist" to distribute whole package, not to upload
it to Hackage.

2016-05-10 23:14 GMT+03:00 Ian Jeffries <notifications@github.com>:

**Comment by mgsloan** [comment]
One reason to include it in the package is a future feature like https://github.com/commercialhaskell/stack/issues/2122

**Comment by quasicomputational** [comment]
How would this work for megarepos, where each project is in a subdirectory and there's a top-level stack.yaml?

**Comment by mgsloan** [comment]
@quasicomputational Great question.  It should be possible to generate an appropriate stack.yaml for each.  This would look like:

1. Remove the packages list (implicitly it's just the current directory).

2. Add extra-deps for every local package that it depends on.

With current YAML decoding / encoding, this would forget about any of the user's ordering, comments, or layout.  But it should work.  Doing better would be somewhat tracked by https://github.com/commercialhaskell/stack/issues/115

**Comment by snoyberg** [comment]
Being explicit about listing the file in `extra-source-files` as mentioned above is the best approach, closing
