### ISSUE TITLE
Windows install a bit confusing

### ISSUE THREAD

**Issue by flip111** [commercialhaskell/stack#2131]
at http://docs.haskellstack.org/en/stable/install_and_upgrade/#windows it's advised:

```
It is strongly advised to set your STACK_ROOT environment variable similarly to your root (e.g., set STACK_ROOT=c:\stack_root) before running stack.
```

However how can i know my stack root BEFORE the installer? Or what would the installer choose as default root?

**Comment by simonmichael** [comment]
Related: the first two Notes are confusing, and should be less prominent. I think the "Windows 64-bit Installer" is all that matters to the huge majority of people arriving here.

**Comment by mgsloan** [comment]
>  However how can i know my stack root BEFORE the installer? Or what would the installer choose as default root?

I think this is the confusion - the user determines STACK_ROOT, and it is used by stack.  The installer doesn't care about it.

**Comment by sjakobi** [comment]
I'd like to fix this issue but don't really enough about the Windows platform.

For the `STACK_ROOT` note I propose the following wording:

> _Note_: Before installing `stack`, please set the `STACK_ROOT` variable to a short path of your choice, e.g. `set STACK_ROOT=c:\stack`. By setting the main `stack` installation directory to such a short path, you ensure that `stack` will not run any issues related to the filepath length limit.

Is this ok?

Could you possibly propose what to do about the 32-bit / 64-bit note, @simonmichael?

**Comment by simonmichael** [comment]
Drop the 32-bit option entirely ?

**Comment by borsboom** [comment]
STACK_ROOT can be set before _or_ after running the installer.  It doesn't make any difference.  Maybe the installer itself should offer to set it, since it doesn't look like long path issues are going to be fixed on Windows any time soon.

I know in the past we had requests for a 32-bit binary, but I've not heard any reports of problems with the 64-bit version for a long time, so maybe we should just recommend the 64-bit binary but leave the 32-bit one for now in case anyone really wants it.

**Comment by flip111** [comment]
The sentence seems to be removed from the documentation at the moment. Perhaps STACK_ROOT is set automatically. Since i just reinstalled windows and stack and i had no issues and because the original sentence is no longer present in the documentation i'm going to close this.
