### ISSUE TITLE
Document build options passed to GHC

### ISSUE THREAD

**Issue by JanGe** [commercialhaskell/stack#2132]
I couldn't find any mentioning in the docs of which `ghc-options` are by default passed to GHC.

E. g. the `--fast` flag apparently disables optimisation by passing `-O0`. This is AFAIK the default for GHC. But then what is the default for `stack build`?

It would be nice to have some short overview of what exactly will be passed when it's not overridden manually.

**Comment by mgsloan** [comment]
AFAIK, by default, the only extra ghc-options passed by stack are `-ddump-hi -ddump-to-file`.  Otherwise, it's exactly the same behavior that Cabal uses.  I agree that this should be documented further - it's under the purview of the Cabal project.

GHC uses `-O1` by default, so even if you don't have `-O1` or `-O2` in your cabal file, `--fast` will make compilation faster.

Feel free to open a doc change about `-ddump-hi -ddump-to-file`, though it's already somewhat covered [here](http://docs.haskellstack.org/en/stable/faq/#where-does-the-output-from-ghc-options-ddump-splices-and-other-ddump-options-go)

**Comment by JanGe** [comment]
GHC's documentation actually [lists `-O0` as default](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/flag-reference.html#idp46686514893008):

    Flag        Description
    -O0         Disable optimisations (default)
    -O or -O1   Enable level 1 optimisations
    -O2         Enable level 2 optimisations
    -Odph       Enable level 2 optimisations, set -fmax-simplifier-iterations=20 and -fsimplifier-phases=3.

Cabal seems to [override this by default](https://www.haskell.org/cabal/users-guide/installing-packages.html#miscellaneous-options):

    --enable-optimization[=n] or -O[n]

        (default) Build with optimization flags (if available). This is appropriate for production use, taking more time to build faster libraries and programs.

        The optional n value is the optimisation level. Some compilers support multiple optimisation levels. The range is 0 to 2. Level 0 is equivalent to --disable-optimization, level 1 is the default if no n parameter is given. Level 2 is higher optimisation if the compiler supports it. Level 2 is likely to lead to longer compile times and bigger generated code.

Didn't know about `--cabal-verbose`. Thanks for the hint!

**Comment by mgsloan** [comment]
Hmm, yeah, could be!  In that case we have a bit of non-clarity in the ghc manual [here](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/options-optimise.html)

> These flags turn on and off individual optimisations. Flags marked as Enabled by default are enabled by -O, and as such you shouldn't need to set any of them explicitly. 

I guess when it says "enabled by default" it really means "enabled by -O1".
