### ISSUE TITLE
Check that `extra-deps` and `packages` are disjoint

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2136]
[This Travis job](https://travis-ci.org/commercialhaskell/stack/jobs/130172044) failed only during the compilation of `stack` itself because the used version of `hpack` was [the one defined in the `packages` section](https://github.com/commercialhaskell/stack/blob/872ff1eae6ff58851361de9335fc1d82539b66f7/stack-8.0.yaml#L48) (0.12) while the intended version was 0.14 as defined in the `extra-deps` section.

I think we should simply make sure that no dependency is defined both in the `extra-deps` and `packages` section and throw an error early on if necessary.

**Comment by mgsloan** [comment]
Makes sense!  Note that extra-deps will soon be equivalent to specifying a custom snapshot.  It still makes sense to do this check, though.

**Comment by kanishka-azimi** [comment]
Allowing for overlap between the two sections with priority given to `packages` might be useful. I am considering using it so that I can use either a local development version, or fallback to a version of a package from either a public hackage or private hackage.

**Comment by sjakobi** [comment]
@kanishka-azimi Sacrificing clarity and robustness for a small convenience doesn't sound like a good tradeoff to me.

**Comment by kanishka-azimi** [comment]
Okay, I could understand prioritizing clarity. 

I mostly ran across this issue as I was reading up on possibilities for using private hackage instances for our closed source repos. I was brainstorming how to use one stack.yaml file instead of introducing a homegrown shell script to generate stack.yaml files. I don't know what Snoymen is using currently. I found this old post - http://www.yesodweb.com/blog/2010/12/announcing-yackage.

**Comment by snoyberg** [comment]
This now generates an error message, closing
