### ISSUE TITLE
ghc 8 workaround for dependencies

### ISSUE THREAD

**Issue by ilovezfs** [commercialhaskell/stack#2192]
To get the `haskell-stack` formula building under GHC 8.0.1 for Homebrew (we only typically support the latest GHC), I've needed to add a "cabal.config" file at the root of the package containing "allow-newer: base,transformers", at which point everything builds as expected. Without this, I get

```
clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries'
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: stack-1.1.2 (user goal)
trying: base-4.9.0.0/installed-4.9... (dependency of stack-1.1.2)
trying: transformers-0.5.2.0/installed-0.5... (dependency of stack-1.1.2)
next goal: retry (dependency of stack-1.1.2)
rejecting: retry-0.7.2 (conflict: base => ghc-prim==0.5.0.0/installed-0.5...,
retry => ghc-prim<0.5)
rejecting: retry-0.7.1, retry-0.7.0.1, retry-0.7, retry-0.6 (conflict:
transformers==0.5.2.0/installed-0.5..., retry => transformers<0.5)
rejecting: retry-0.5.1, retry-0.5, retry-0.4, retry-0.3.0.0, retry-0.2.0.0,
retry-0.1.0.1, retry-0.1.0.0 (conflict: stack => retry>=0.6 && <0.8)
Dependency tree exhaustively searched.
```

**Comment by borsboom** [comment]
Yeah, hopefully now that GHC 8.0.1 has been released the dependencies will get updated soon.  Stackage nightly has switched to GHC 8.0.1 and the curators are getting in touch with everyone whose packages are broken by this to get them updated (until then, ~600 packages have been removed from Stackage nightly).

**Comment by borsboom** [comment]
We've actually hit an issue where Homebrew's `stack` behaves differently than other builds, likely due to cabal-install's solver choosing different versions of dependencies.  Building with GHC 8.0 will likely only exacerbate these sorts of problems (we're unlikely to switch official Stack builds to GHC 8.0 for a few months at least).  We're discussing how to resolve this in a general way over in #2182, and would value your input.

**Comment by ilovezfs** [comment]
Does the problem still occur with the latest version we just pushed out? https://github.com/Homebrew/homebrew-core/commit/e5e8ca89a6d60e86c4442f99e10bb14ac73afcc8

If not, and there is an explicit configuration that does work as expected with GHC 8, I can install a cabal.config at the root of the sandbox to bend it however it needs to be using this method:

https://github.com/Homebrew/legacy-homebrew/pull/49427/files

If it truly MUST be built with GHC 7 to behave as expected, it might be possible to have that as a non-default option (assuming other Homebrew folks besides me think it's an acceptable option). GHC 7 is likely to be moved to the `homebrew/versions` tap, which is a separate repository, and we have a rule that the default configuration (i.e., the "bottled" binary version) cannot have any so-called cross-tap dependencies, but optional configurations (which then must be built from source by the user) are permitted to have cross-tap dependencies. So something like `depends_on "homebrew/versions/ghc7" => [:optional, :build] ; depends_on "ghc" => :build if build.without? "ghc7"`, and then the user does `brew install --with-ghc7 stack`, which triggers a source build. But it's *much* preferred to find a working GHC 8 configuration, even if I have to force it with the cabal.config.

**Comment by borsboom** [comment]
I'll see if out Stackage nightly-based GHC 8 build exhibits the same problem.  If not, we can build a cabal.config based on that to force the dependencies.  That said, I think the suggestion in https://github.com/commercialhaskell/stack/issues/2182#issuecomment-221856727 is going to be the most general way to avoid this class of problem because it means the Homebrew build will be identical to the official build in all cases now and in the future.

**Comment by borsboom** [comment]
We got this sorted our in Homebrew.
