### ISSUE TITLE
Stop using system-ghc silently…or at all.

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#2221]
![screen shot 2016-05-31 at 3 54 34 pm](https://cloud.githubusercontent.com/assets/320177/15690234/40e46136-2748-11e6-836e-74de31fa99c4.png)

This happens a fair bit, and not just in connection with `ghc-mod` although it's the most common culprit. While doing the training at LambdaConf we had a beginner get _very_ confused because their system installed GHC was pre-FTP and the Stack provided GHC was 7.10.3. From there, they didn't understand `ghci` and `stack ghci` would be from _substantially_ different versions of GHC.

I'd really like Stack to stop implicitly using system-installed versions of GHC without explicit direction from the user.

**Comment by mgsloan** [comment]
Agreed, I'm tired of asking whether or not the user is using a custom ghc install.  Another source of reproduction difficulty is whether stack was built via stack or cabal - I've opened [this ticket](https://github.com/commercialhaskell/stack/issues/2222) on that.

**Comment by sjakobi** [comment]
For context, @mgsloan's comment from #1901:

> Some discussions of why the system ghc is preferred:

> * https://groups.google.com/forum/#!topic/haskell-stack/-XaXiq5Wdo8
> * #1129

>I'm not sure if I buy it, I'm leaning towards making "system ghc" usage opt-in, but this would be a breaking change...

**Comment by bitemyapp** [comment]
I got bit by system-ghc being the default last week when I tried to switch to profiling libraries. Remembered I might accidentally be using system-ghc which was causing the dependency failures. Lost a half hour or more to that and I know Stack pretty well. Imagine it'd be a hard stop for a new person trying to profile their project.

**Comment by sjakobi** [comment]
Ok, so I'm totally in favor of switching to `--no-system-ghc` by default in one of the next few releases.

I don't have a good idea of the breakage that could result from changing the default behaviour, and currently use stack-provided compilers exclusively, so I'd like to do the switch with sufficient time before a release, so it can be beta-tested thoroughly.

This means that the switch can only happen once the `store` version-hash issue (https://github.com/commercialhaskell/stack/issues/2296) has been resolved because I'd feel really bad about all the beta-testers wasting their time while their extra-deps compile…

@mgsloan: Any idea when #2296 might be resolved?

**Comment by sjakobi** [comment]
This FAQ entry will need to be edited once the switch is done:

https://docs.haskellstack.org/en/stable/faq/#i-already-have-ghc-installed-can-i-still-use-stack

**Comment by shanemikel** [comment]
First attempt at profiling Haskell today.  I've been digging around for hours now, and I've finally got something to compile (with --no-system-ghc).  Until this is fixed, would somebody mind adding a note to the docs section on profiling?

**Comment by sjakobi** [comment]
> First attempt at profiling Haskell today. I've been digging around for hours now, and I've finally got something to compile (with --no-system-ghc).

@shanemikel: What were the symptoms of using the wrong GHC? Feel free to make a PR for that note!

**Comment by bitemyapp** [comment]
Just to add to this, I just got bitten by `profiling <> system-ghc` _again_
