### ISSUE TITLE
Allow DownloadInfo be a file

### ISSUE THREAD

**Issue by cblp** [commercialhaskell/stack#2224]
I'm trying to make fully offline environment for building a stack project.

I've managed to substitute all parts of stack, except GHC download source. It would be nice if it may be a local file instead of HTTP URL.

Bad solution: run a local web server.

Ugly solution: setup stack in /opt/stack, copy all bazillion files on other machine at /opt/stack, and use it as STACK_ROOT.

Good solution: copy ghc.tar.xz and give it to stack with stack-setup.yaml.

**Comment by mgsloan** [comment]
> I've managed to substitute all parts of stack, except GHC download source.

What's that look like?  Ideally we'd have this in stack itself.  I would love to have a better offline mode: https://github.com/commercialhaskell/stack/issues/1594

> Good solution: copy ghc.tar.xz and give it to stack with stack-setup.yaml.

Definitely feasible.  It should be a straightforward change [here](https://github.com/commercialhaskell/stack/blob/7f7cead556f6bcb7ff3fe15af31e0f8c47149b71/src/Stack/Setup.hs#L631) which skips doing the download and instead provides the file directly to the install step.

PRs appreciated! :D

**Comment by cblp** [comment]
If I understand right, #1594 is about _not_ building in case if connectivity is needed. My goal is to _do_ build even if there will be no connectivity.

> What's that look like?

It will be in https://github.com/cblp/stack-offline soon.

**Comment by mgsloan** [comment]
The goal of #1594 is to have a flag to skip attempts at internet access.  It is true that most of the time when stack tries to download things, it needs to.  In the event that we add some stuff to check for a more recent stack version, then the offline flag will be more relevant.

We do want to have full support for offline use.  Would you be keen on merging this with stack, or deprecating it once stack has direct support?  That way more people will benefit rather than needing to know about `stack-offline`.

**Comment by cblp** [comment]
My first milestone is a stand-alone utility, and the second milestone is to integrate it to the stack.

**Comment by mgsloan** [comment]
Awesome, sounds good!  Thanks for working on this!

**Comment by cblp** [comment]
#2232

**Comment by Blaisorblade** [comment]
Should this be closed now that #2232 is merged, or do we still have sth. to track?

**Comment by mgsloan** [comment]
I think it's done!
