### ISSUE TITLE
--upgrade-cabal wants write access to system ghc installation

### ISSUE THREAD

**Issue by jwaldmann** [commercialhaskell/stack#2230]
I tried 

```
stack setup --upgrade-cabal
```

in a project directory (that has `stack.yaml` with (default) `system-ghc: true`). It failed with

```
/opt/ghc/stable/new-cabal: createDirectory: permission denied (Permission denied)
```

That was unexpected. I think it should not want to do that.

```
$ which ghc
/opt/ghc/stable/bin/ghc

$ stack --version
Version 1.0.4.3 x86_64
```

**Comment by sjakobi** [comment]
I don't think that I've heard about this issue before.

Could you still check whether it still occurs with `stack-1.1.2`, just in case it has already been fixed?

**Comment by jwaldmann** [comment]
it's the same with
```
$ stack --version
Version 1.1.2 x86_64 hpack-0.14.0

$ stack setup --upgrade-cabal
Trying to upgrade Cabal library on a GHC not installed by stack.
This may fail, caveat emptor!
Installing Cabal-1.24.0.0 to replace 1.22.5.0
Cabal-1.24.0.0: download
... [compiles 84 modules]
Linking Setup ...
Configuring Cabal-1.24.0.0...
Building Cabal-1.24.0.0...
Preprocessing library Cabal-1.24.0.0...
... [compiles 86 modules]
/opt/ghc/stable/new-cabal: createDirectory: permission denied (Permission
denied)
Exit code ExitFailure 1 while running ["/tmp/stack-cabal-upgrade17711/Cabal-1.24.0.0/Setup","install"] in /tmp/stack-cabal-upgrade17711/Cabal-1.24.0.0/
```

**Comment by mgsloan** [comment]
It's likely because of

> Trying to upgrade Cabal library on a GHC not installed by stack.
> This may fail, caveat emptor!

Though, I'm not sure exactly why that's expected to be something that can fail.  I think we have to change the defaults to not use system ghc by default - https://github.com/commercialhaskell/stack/issues/2221

**Comment by ju1m** [comment]
I've hit the same problem using Debian's `ghc` `7.10.3-6~bpo8+2` and `stack` `1.1.2-0~jessie`.
Here, in order to:

> Installing Cabal-1.24.0.0 to replace 1.22.5.0

`stack setup --upgrade-cabal` wants to write in:
- `/usr/`: for `/usr/new-cabal/`
- `/usr/lib/ghc/package.conf.d/`: for `/usr/lib/ghc/package.conf.d/Cabal-1.24.0.0-IVPBR8CshIb24I8NwtoMDO.conf`

If possible I would prefer to have it installed in `.stack-work/` or `~/.stack/`, if not possible I guess the permissions problems is to be expected in such system-wide paths, and maybe can be worked around by running `stack setup` as `root`, however writing in `/usr/new-cabal/` looks ugly.

This being done, `stack build` still failed to compile my custom `Setup.hs`, conflicting with the `Cabal` installed by `cabal`, and even after `ghc-pkg unregister Cabal-1.22.5.0`, still conflicting with another `Cabal-1.24.0.0`:

>     /home/julm/work/lol/1/typing/Setup.hs:5:30:
>         Couldn't match expected type ‘Distribution.Simple.UserHooks.UserHooks’
>                     with actual type ‘Cabal-1.24.0.0@Cabal_8cmQ8p2Uz0jD2qRNDMFwWV:Distribution.Simple.UserHooks.UserHooks’
>         NB: ‘Distribution.Simple.UserHooks.UserHooks’
>               is defined in ‘Distribution.Simple.UserHooks’
>                   in package ‘Cabal-1.24.0.0@IVPBR8CshIb24I8NwtoMDO’
>             ‘Cabal-1.24.0.0@Cabal_8cmQ8p2Uz0jD2qRNDMFwWV:Distribution.Simple.UserHooks.UserHooks’
>               is defined in ‘Distribution.Simple.UserHooks’
>                   in package ‘Cabal-1.24.0.0@Cabal_8cmQ8p2Uz0jD2qRNDMFwWV’
>         In the first argument of ‘defaultMainWithHooks’, namely
>           ‘(uuagcLibUserHook uuagc)’
>         In the expression: defaultMainWithHooks (uuagcLibUserHook uuagc)

I tried to remove `.stack-work/`, to no avail.
But then removed `.stack-work/`, `cabal.sandbox.config`, and… `~/.cabal/lib/x86_64-linux-ghc-7.10.3/Cabal-1.24.0.0-8cmQ8p2Uz0jD2qRNDMFwWV`; since that `stack build` works.

FYI, the `stack.yaml`:
```
flags: {}
extra-package-dbs: []
packages:
- '.'
- ../calculus
extra-deps:
- Cabal-1.24.0.0
- monad-classes-0.3.1.1
- peano-0.1.0.1
- uuagc-0.9.52.1
- uuagc-cabal-1.0.6.0
- uulib-0.9.22
explicit-setup-deps:
  '*': true
resolver: lts-6.12
```

And the `.cabal`:

```
build-type: Custom
cabal-version: >= 1.24
…
Custom-Setup
   setup-depends:
     base >= 4.6 && < 5
     -- , Cabal >= 1.24
     , uuagc >= 0.9
     , uuagc-cabal >= 1.0.6.0
```

Unfortunately (because it's quite slow), `stack build` reinstalls `Cabal-1.24.0.0` in `.stack-work/`.
But removing `Cabal-1.24.0.0` from `extra-deps`, downgrades to (and reinstalls anyway too) `Cabal-1.22.8.0` (not quite the old version coming with Debian's `ghc`, which was `Cabal-1.22.5.0`).

Also unfortunate at this point, `stack sdist` fails on missing packages:

> % stack sdist

> Getting file list for /home/julm/work/lol/1/calculus/
> Cabal file warning in /home/julm/work/lol/1/typing/lol-typing.cabal: Ignoring unknown section type: custom-setup
> Cabal file warning in /home/julm/work/lol/1/typing/lol-typing.cabal: This package requires at least Cabal version 1.24
> Cabal file warning in /home/julm/work/lol/1/typing/lol-typing.cabal: Ignoring unknown section type: custom-setup
> Cabal file warning in /home/julm/work/lol/1/typing/lol-typing.cabal: This package requires at least Cabal version 1.24
> Building sdist tarball for /home/julm/work/lol/1/calculus/
> Checking package 'lol-calculus' for common mistakes
> Package check reported the following warnings:
> 'ghc-options: -main-is' is not portable.
> Wrote sdist tarball to /home/julm/work/lol/1/calculus/.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/lol-calculus-1.20160822.tar.gz
> Cabal file warning in /home/julm/work/lol/1/typing/lol-typing.cabal: Ignoring unknown section type: custom-setup
> Cabal file warning in /home/julm/work/lol/1/typing/lol-typing.cabal: This package requires at least Cabal version 1.24
> Getting file list for /home/julm/work/lol/1/typing/
> Cabal file warning in /home/julm/work/lol/1/typing/lol-typing.cabal: Ignoring unknown section type: custom-setup
> Cabal file warning in /home/julm/work/lol/1/typing/lol-typing.cabal: This package requires at least Cabal version 1.24
> Cabal file warning in /home/julm/work/lol/1/typing/lol-typing.cabal: Ignoring unknown section type: custom-setup
> Cabal file warning in /home/julm/work/lol/1/typing/lol-typing.cabal: This package requires at least Cabal version 1.24
> 
> --  While building package lol-typing-1.20160822 using:
>       /usr/bin/ghc --make -odir /home/julm/work/lol/1/typing/.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/setup -hidir /home/julm/work/lol/1/typing/.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/setup -i -i. -package=Cabal-1.24.0.0 -clear-package-db -global-package-db -package-db=/home/julm/.stack/snapshots/x86_64-linux/lts-6.12/7.10.3/pkgdb /home/julm/work/lol/1/typing/Setup.hs -o /home/julm/work/lol/1/typing/.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/setup/setup
>     Process exited with code: ExitFailure 1
>     Logs have been written to: /home/julm/work/lol/1/typing/.stack-work/logs/lol-typing-1.20160822-sdist.log
> 
>     
>     /home/julm/work/lol/1/typing/Setup.hs:2:8:
>         Could not find module ‘Distribution.Simple.UUAGC’
>         Perhaps you meant
>           Distribution.Simple.UHC (from Cabal-1.24.0.0@IVPBR8CshIb24I8NwtoMDO)
>           Distribution.Simple.GHC (from Cabal-1.24.0.0@IVPBR8CshIb24I8NwtoMDO)
>           Distribution.Simple.JHC (from Cabal-1.24.0.0@IVPBR8CshIb24I8NwtoMDO)
>         Use -v to see a list of the files searched for.
>     
>     /home/julm/work/lol/1/typing/Setup.hs:3:8:
>         Could not find module ‘UU.UUAGC’
>         Use -v to see a list of the files searched for.

Hope this is not too confusing and helps a bit :-]

**Comment by mgsloan** [comment]
Closing as an old support ticket. 

I believe the custom-setup issue is resolved in recent stack.
