### ISSUE TITLE
Migrate --nix support to use haskell.compiler.ghcXYZ attributes instead of haskell.packages.lts_X_Y

### ISSUE THREAD

**Issue by peti** [commercialhaskell/stack#2259]
The `haskell.packages.lts_X_Y` package sets will disappear from Nixpkgs in the foreseeable future and `stack` should  not rely on them any longer. Instead, please access the appropriate compiler using the `haskell.compiler.ghcXYZ` attributes instead. http://permalink.gmane.org/gmane.linux.distributions.nixos/20505 has more details about the motivation behind that upcoming change.

**Comment by YPares** [comment]
Ok, so what would be the cleanest way to get the required GHC version from the LTS?

**Comment by mgsloan** [comment]
I do not see the reason for this change, and it will break existing stack versions and build configurations.  This seems like a frustration with a variety of non-endemic issues.  Please consider this more carefully.
 
> 1. Stackage does not "maintain" any of its LTS releases. Rather, the
> Stackage volunteers compile a list of package versions, test and verify
> them to the best of their abilities, release that list, and then they
> never touch it again.

How about bringing up this issue on stackage, or integrating the nix feedback into the curation of stackage?

> 2. Following LTS strictly may deprive us of important security updates.

Ok, this seems to be more like "I don't want stable package sets".  It turns out that people do.

It sounds like you want the ability to retroactively patch a package set.  We tend not to allow this because it affects build determinism.  However, for careful patches I can see the value.  It's certainly something to consider adding to stackage, perhaps in the form of minor lts versions (`lts-5.1.1`)

> 3. Stackage Nightly is not a stable package set.

So we do want stable package sets!  :)

This seems like an impedence mismatch between how nightlies have been exposed to nix users.  If "haskellPackages" is always the latest nightly, then yes, you shouldn't do that if you want reliable builds.

If you want something stable, use lts.  If you want something unstable, use nightly.  It's that simple.

> Stackage releases come out only after a complete test build of all
> packages has succeeded. Unfortunately, those tests don't always catch
> all issues we might run into, because we compile packages in a different
> environment.

Ok, lets work with you guys to curate stack via feedback from nix.

IMHO, none of the reasons given justify this drastic action.  That said, I am not a nix user.

**Comment by mgsloan** [comment]
> Ok, so what would be the cleanest way to get the required GHC version from the LTS?

The snapshot specifies a compiler version, so stack knows that once it's loaded.  Do you need to get the GHC version outside of stack itself?

**Comment by peti** [comment]
@mgsloan, to the best of my knowledge, adapting Stack to use the compiler attributes rather than the (obsolete) LTS package set attributes should be a harmless change that won't pose any serious problems. I realize it's inconvenient having to make that switch, and I am sorry about that. We did not take that decision lightly and there was a discussion with various Stackage team members beforehand. Alas, things turned out such that the level of support Nix used to offer seems clearly unsustainable, hence the change.

**Comment by YPares** [comment]
@mgsloan Nope, I meant within stack's code actually.

**Comment by mgsloan** [comment]
Gotcha!

`asks (envConfigCompilerVersion . getEnvConfig) :: (MonadReader env m, HasEnvConfig env) => m CompilerVersion`

**Comment by YPares** [comment]
@mgsloan The problem is that right now it seems the EnvConfig isn't accessible from outside the "inner" computation (the one started inside the nix shell, see https://github.com/commercialhaskell/stack/blob/master/src/main/Main.hs#L893 ).
That's where envConfig is created and used to run the `(MonadReader env m, HasEnvConfig env) => m` monad.

**Comment by YPares** [comment]
Okay, it required a bit of working around as the monad outside the shell wasn't an `HasEnvConfig`,
so I submitted a PR so people may review the solution I'm proposing:
https://github.com/commercialhaskell/stack/issues/2270.

**Comment by YPares** [comment]
@mgsloan Ok, so it isn't fixed, sorry.
I can't use `setupEnv` to get the wanted GHC version because it _expects_ GHC to be already installed.

**Comment by YPares** [comment]
@mgsloan Okay, I found another (simpler) way. I think it's good now.

**Comment by peti** [comment]
LTS package sets will disappear from Nixpkgs `master` this week. We'll keep the haskell.packages.lts_x_y.ghc attributes around for a while though to remain backwards compatible.
