### ISSUE TITLE
Don't fallback silently to LTS

### ISSUE THREAD

**Issue by cocreature** [commercialhaskell/stack#228]
I find it extremely unintuitive that it falls back to lts with no warning.

I tried it on a project where I had a too new lens dependency so it chose lts and started downloading ghc-7.8 while I need a nightly snapshot and 7.10.

There should be a big warning pointing out that no snapshot matched and also what caused problems and then the snapshot should be chosen by the user instead of defaulting to lts.

**Comment by snoyberg** [comment]
Possibly related: #215 asks the question about whether we should automatically install GHC if it's missing. If that was turned off, then the behavior in the case you just described would be to generate a stack.yaml that points at LTS and then ask you to run stack setup, which seems like it would be an improvement.

Agreed on the warning and diagnostics, that seems like a clear advantage. Perhaps we should also exit `stack` after writing a stack.yaml that we know doesn't work so that the user can get a chance to fix things.

**Comment by andrewthad** [comment]
Agreed, the fallbacks are pretty counter-intuitive. At the least, some kind of prompt would be nice for users. Because 99% of the time, I don't want `stack` to start building against a different version of LTS than the one I specified.

**Comment by snoyberg** [comment]
I've opened #253 to try and discuss this and other related topics together

**Comment by snoyberg** [comment]
This is resolved now on master. Check out https://github.com/commercialhaskell/stack/issues/253#issuecomment-112535147 for more details.
