### ISSUE TITLE
"stack setup 7.10.3" on Arch Linux: Multiple errors

### ISSUE THREAD

**Issue by nd2s** [commercialhaskell/stack#2284]
First one was a strange problem with `cmake`:

    Running /usr/bin/gmake install in directory /tmp/user/stack-setup19831/ghc-7.10.3/ exited with ExitFailure 1
    
    
    CMake Error: The source directory "/tmp/user/stack-setup19831/ghc-7.10.3/install" does not exist.
    Specify --help for usage, or press the help button on the CMake GUI.

Solution was to uninstall the `cmake` package from Arch (no idea why that helped).

And now it requires `libtinfo.so.5` which apparently *was* in `libtinfo-5` in AUR, but this package is gone now and I don't know how to get it, or where that lib is now.

Can anyone tell me how to make this work?

**Comment by borsboom** [comment]
You might try installing [libtinfo](https://aur.archlinux.org/packages/libtinfo/) or [ncurses5-compat-libs](https://aur.archlinux.org/packages/ncurses5-compat-libs/).  I'm not an Arch user myself, and the AUR packages have a habit of changing, but `libtinfo` used to work.

As for CMake, I'm not sure why it installs a `gmake` executable since that's usually what GNU make is named on systems that don't use it as their native `make`.  Stack tries `gmake` first.  I suppose Stack should check the `gmake --version` output before it actually tries to run it.

**Comment by nd2s** [comment]
I think `libtinfo` has a newer version now, but `ncurses5-compat-libs` worked. Thanks for that!

**Comment by borsboom** [comment]
Ok, I've updated the documentation to say that `ncurses5-compat-libs` is required instead of `libtinfo-5`.  I'll open a separate issue about checking `gmake --version`.
