### ISSUE TITLE
Allow restraining snapshot selection

### ISSUE THREAD

**Issue by cocreature** [commercialhaskell/stack#229]
I'd like to have an option to select the snapshot when running `stack build` instead of relying on stack to figure it out for me and if it is wrong cancelling, editing the yaml file and rerunning it.

**Comment by snoyberg** [comment]
I think the solution here will end up being very close to what we do for #228, so the two issues should be considered together (possibly even merged into a single issue actually).

**Comment by cocreature** [comment]
Feel free to merge/close this issue if it's covered my #228.

**Comment by gregwebs** [comment]
This issue is potentially asking for a `stack init` command that creates a `stack.yaml` that can be edited before any dependencies are downloaded. Right now #228 seems focused on the ghc part.

**Comment by snoyberg** [comment]
Adding a `stack init` is a really easy first step to take here, and we can iterate from there.

**Comment by snoyberg** [comment]
Bikeshedding: do we have a problem with the command `init` due to its preexisting meaning with cabal (initialize a package)? There's also some naming overlap with the proposed `stack new` from #137.

**Comment by chreekat** [comment]
There could be a single command that does the right thing. If `stack build` would build packages, `stack init` would simply create the yaml. If `stack build` would fail with **`PackageNoCabalFileFound "/home/b/tmp/foo/"`**, `stack init` would ask to set up a new project.

`stack build` already manages the second scenario, sort of, since it still creates a stack.yaml even if there is no cabal file found. Could be improved.

There's also a question of what to do when creating a multi-package project. Right now `stack build` ignores that scenario, but perhaps it and  `stack init` could just snoop one subdirectory level down on the hunt for cabal files.

**Comment by snoyberg** [comment]
I've pushed a simple commit to the 229-stack-init branch that implements the basics of an init command.

One thing I'm concerned about is trying to make `init` too smart. When it comes to large, multi-package projects, is very unlikely that stack will *ever* guess correctly what you want to do. In fact, as we're seeing in this issue and #228, it's very difficult for it to guess right now what the user would want to do in even somewhat complicated cases.

I think instead of becoming too magical, it would make more sense to generate a basic stack.yaml and explain to the user (via docs on the website and comments in the generated file) how to proceed.

**Comment by gregwebs** [comment]
Sure, it might make sense to give it a different name. I am wondering if `init` should be used for #137 and this should be called `new`. Or this could be `stack config`. `stack config` would end up being a sub command, but with no extra options when there is no `stack.yaml` it would generate a `stack.yaml`.

**Comment by snoyberg** [comment]
Hmm I like that.

**Comment by gregwebs** [comment]
Another thing I have been thinking about is that `stack setup` seems to be focused on ghc. I would actually expect this to be what `stack setup` should do (in addition to stating: I can't find GHC, you can install it with `stack setup --ghc`).

There are different points in the design space, good thing we are still in beta :)

**Comment by snoyberg** [comment]
I've opened #253 to try and discuss this and other related topics together

**Comment by snoyberg** [comment]
Solved by the `--resolver` flag, see https://github.com/commercialhaskell/stack/issues/253#issuecomment-112535147. Closing.
