### ISSUE TITLE
Cannot build posix-paths

### ISSUE THREAD

**Issue by andrewthad** [commercialhaskell/stack#2315]
When I try to build packages that have `posix-paths` as a dependency (the specific package I am trying to build is `udev`), I get the following error:

    Progress: 2/3/tmp/stack9817/pax_global_header: setFileMode: does not exist (No such file or directory)

If there is any additional information that I can provide, let me know. Thanks.

**Comment by phadej** [comment]
Do you build in virtual machine or somehow different filesystem?

**Comment by mgsloan** [comment]
Did you build stack via cabal?  In that case, you can get behavior which don't affect other stack users, because of different package versions.

In this, case you likely have an old version of the tar package.  See:

* https://github.com/haskell/cabal/issues/3390
* https://github.com/haskell/tar/commit/6c0acf8edb9c5006a8fa1e1c555177df4cfa2d18
* https://github.com/haskell/tar/pull/17

I have updated the tar lower bound to `0.5.0.3`.

Closing, reopen if there's something I'm missing, and this isn't the issue.
