### ISSUE TITLE
Add `stack setup --install-cabal VERSION` in addition to `stack setup --upgrade-cabal`.

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2386]
This should make it easier to test `stack` with different versions of `Cabal`, as required for e.g. #2350.

**Comment by sjakobi** [comment]
A few pointers:

* Most (all?) of the related code lives in either `Stack.SetupCmd` or `Stack.Setup`.
* I'd suggest generalizing `Stack.Setup.ugradeCabal` to `installCabal` so it can accept a concrete version or default to the newest available version of `Cabal`

**Comment by Blaisorblade** [comment]
What about picking a fixed `cabal-install` version for each stack version, and installing it in isolation? Ideally, the newest one for the supported cabal library.
(Why is stack not yet on Cabal 1.24 BTW?)

**Comment by borsboom** [comment]
Stack doesn't use cabal-install for much (just the solver AFAIK) so not really any need to have cabal-install match the Cabal library version it was built with.  For building Stack, we stick with the versions of packages that are in the current LTS snapshot unless there's a really compelling reason to add an extra-dep, so once LTS 7 is released Stack will upgrade to a newer Cabal library version (along with building with GHC 8.0.1). And we haven't been in a rush to have Stack use Cabal-1.24 because we don't need any of its new features.

**Comment by lwm** [comment]
Can be closed off now that #2995 went in.

**Comment by mgsloan** [comment]
Indeed! Closing
