### ISSUE TITLE
On OS X stack --nix doesn't need to set --extra-{lib,include}-dirs

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#2419]
On all platforms, Stack sets `--extra-{lib,include}-dirs` automatically for each system package listed in the `nix` section. That's because otherwise Cabal has trouble finding those system libraries when building. But on OS X, this is not necessary: Cabal finds the system libs just fine without it. But worse, passing these flags can be actively harmful. The following example fails with a link error:

```
$ stack new --bare
# add extra-libraries: ssl libpq to executable section of .cabal.
$ stack --nix --nix-packages "openssl zlib postgresql95" --resolver lts-6.0 build
```

Will paste the actual error in a comment once I can reboot on an OS X machine. But essentially the issue is that we're overriding the default search path.

**Comment by YPares** [comment]
The thing is that systematic removing of --extra-{lib,include}-dirs on OSX is impossible because it is needed at times.
Indeed, a dependence on postgresql95 is an example of a case when you _don't_ need explicit --extra-lib-dirs.
But you are right: after checking, in the case of `libpq`, _not_ explicitely passing --extra-lib-dirs to stack _when it tries to build libpq_ (so if it's already built, you should remove your snapshots) solves the linking problem.

**Comment by YPares** [comment]
@mgsloan Do you have an idea regarding this libpq problem?

**Comment by mgsloan** [comment]
I'm not very familiar with the nix side of things.  What if there was an option to omit the automatic generation `--extra-lib-dirs`?  Issue is, you may only want it on OS X.

I'm not sure what priority `-Ldir` and `-Idir` have when provided via `--ghc-options`, but that's also worth a try.

**Comment by YPares** [comment]
Maybe it's fixed now thanks to https://github.com/commercialhaskell/stack/pull/2444

**Comment by mboes** [comment]
Yup, thanks.
