### ISSUE TITLE
Allow stack exec ghc --version

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#2601]
Currently `stack exec ghc --version` doesn't work as the flag `--version` goes to `stack`, not `ghc`. Several programs (e.g. `runhaskell`) consider any flag after the first non-flag non-mode argument to be flags passed on, so you can do `runhaskell --version foo` to ask `runhaskell` for its version, or `runhaskell foo --version` to ask `foo` for its version. If Stack followed the same logic the `--` would be mostly redundant.

**Comment by borsboom** [comment]
Yeah, that makes sense.  Now we'll have to see how to wrangle optparse-applicative into doing this hopefully without any terrible hacks.

**Comment by harendra-kumar** [comment]
Yes the extra `--` is annoying and not intuitive to figure out. It will be much more intuitive if we can get rid of it. This is badly needed. The same complaint was seen in stack test drive report in the Haskell community emails. This is minor but important for good user experience.

**Comment by harendra-kumar** [comment]
Should the priority be raised from optional?

**Comment by mgsloan** [comment]
Ideally we don't introduce breaking changes.  I'm not sure how we can implement this change, though.  I recall it being tricky to do this with `optparse-applicative`.

**Comment by harendra-kumar** [comment]
Breaking changes are not good and should be avoided but this may be worth it. Otherwise it remains a continuous angst forever. We can have a deprecation cycle where we keep issuing warning whenever the old way is used. I have not thought about the implementation though.

**Comment by mgsloan** [comment]
True!  I do find the exec syntax to be mildly annoying, but I'm used to it.

**Comment by ndmitchell** [comment]
As someone with a steady supply of beginners at the moment this leads to about 3 profanities per user. It's certainly the "worst" thing users hit.

**Comment by mgsloan** [comment]
Thanks for the feedback!  I think that's certainly evidence enough to bump this to `P2: Should`.  I'm certainly in favor of fixing it.  Should be possible to fix it while still supporting the old style.

**Comment by mgsloan** [comment]
I don't think we're going to address this one, folks are just going to need to know how to use `stack exec`.

**Comment by mitchellwrosen** [comment]
@msloan Any word on why it won't be fixed?

**Comment by tolysz** [comment]
`stack exec -- ghc --version`

Simply always write `stack exec -- ` or have some alias for it...

**Comment by borsboom** [comment]
@mgsloan @mitchellwrosen: I'm curious about that too.  Is there a reason supporting this is a bad idea?  It's actually one of my biggest pet peeves about Stack and I'm the one who implemented much of the options parsing in the first place.

I'd welcome a pull request that fixes this, so we could keep this open as a "help wanted" issue.

In an earlier incarnation of an internal stack-like tool I actually had it working, but the problem was that it needed some ugly hacks to work around optparse-applicative not supporting it, and those hacks ended up breaking other corner cases.  optparse-applicative is being more actively maintained now so it may be possible to add support to it (or it may already be there; I haven't checked).

**Comment by mitchellwrosen** [comment]
@borsboom I poked around `optparse-applicative` a bit, and this seems really tricky to implement with the current API. The "--" thing is baked in, not implemented by stack. So, since (I believe) the ideal UI would be something like:

```
stack <stack && stack exec options> exec <command> <command args>
```

I believe the only way to really implement this is to intercept all the args yourself with `getArgs`, do some manual parsing and such to intercept calls to `stack exec` and replace the above with

```
stack <stack && stack exec options> exec <command> -- <command args>
```

then feed it back into `optparse-applicative`. BARF!

**Comment by borsboom** [comment]
That was basically how the "ugly hacks to work around optparse-applicative not supporting it" I mentioned did it.

**Comment by ndmitchell** [comment]
> Simply always write stack exec -- or have some alias for it...

So you are left with the options to either educate every user, or have an alias for `stack exec` - which is what I've done at `$WORK` - since teaching every single user quickly got tiresome. I note both the solutions proposed work great for expert users, and terribly for beginners, which is why I still think this issue is worth fixing.

That's distinct from if it's a pain because the command line parser doesn't make it easy...

**Comment by tolysz** [comment]
@ndmitchell by no means I wanted to suggest that we need to give up hope!
After writing it I found a nice way of implementing it, with using 2 scans i.e. you look for `--` in the first pass  and if it is there you use the current behavior and if it is not, you insert it before something without `-` (i.e. the program name) and retry the first pass. If it is possible or not medono. But it creates context dependent parsing as is a big enough change to go with the next 1.4 release.

All that said someone would need to take some time to implement it.

Just be careful if someone would  use names starting with dashes... as you can not make everyone happy

**Comment by borsboom** [comment]
That's an approach with potential, but I really think we'd be better off actually implementing proper support in optparse-applicative rather than trying to work around it.  Here's another example of a tricky case (in addition your "just be careful" example):

    stack exec grep -- --foo

This greps for the pattern `--foo`.   It already contains a `--`, so with your logic of parsing the command-line as-is, it would end up executing `grep --foo` which is not what we want.  We want it to execute `grep -- --foo`.  So maybe it's ok to say "just run `stack exec -- grep -- --foo`" in this case, but it means people will run into unexpected behaviour and have to understand the implementation in order to know what to do about it.
