### ISSUE TITLE
Using stack programmatically

### ISSUE THREAD

**Issue by burz** [commercialhaskell/stack#2625]
Perhaps this is not the best place to post this, but I wasn't exactly sure where else this would be appropriate. If this is in err, I apologize and hope I might be pointed to where this is a better place to bring up.

I came upon a use case where I would like to be able to install the results of a `stack build` into a certain directory. In Haskell form, I originally tried to see if I could figure out how to invoke a `stack install --local-bin-path=some-dir` within the tool that I was trying to build. Since I was able to use the `Cabal` provided library for parsing `*.cabal` files, I had hoped that `stack` might also allow me to use its library to invoke some command to do the equivalent of the what I had mentioned above. Unfortunately, it does not seem as though this workflow is either (1) possible, or (more likely) (2) simple enough to do at the moment without too much knowledge about how `stack` works internally.

It would be fantastic if some library API were exposed so that programmers who wish to create tools that leverage the `stack` infrastructure would be able to do common `stack` workflows programmatically without having to use the likes of `System.Process` to invoke the tool.

**Comment by mgsloan** [comment]
Feel free to dig into the code and open some PRs that would make stack more accessible as a library.  I bet that this will just consist of moving some stuff out of `Main.hs`.  Otherwise, stack is already setup to be usable as a library, it just isn't our primary usecase, and as such is not high on our priority list.

One reason to not do this is that then it will be harder to ensure that your application is using the same version of stack as the user's version of stack.  While there is usually a high degree of compatibility amongst versions, it is still advisable to stick to a consistent version.  In particular, recently the format of our caches changed, and so switching stack versions could lead to re-building things unnecessarily.
