### ISSUE TITLE
packages with `extra-dep: true` aren't treated as extra-dep

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/stack#2648]
There are at least two issues, I can split them if they aren't caused by the same root problem:
- `--pedantic` makes build fail
- `stack solver` includes `extra-dep: true` packages' test dependencies, although `stack test` doesn't run them.

**Comment by mgsloan** [comment]
Thanks for the report!  I'm not sure if there is anything we can do about this, depends on the capabilities of cabal.  In particular:

* For hackage packages with `extra-dep: true`, they can be soft / hard constraints.

* For git repos, we need to pretend like they are goal packages.  Does the solver let us specify we only care about the library?

Pinging @harendra-kumar , as he wrote the new solver stuff.

**Comment by harendra-kumar** [comment]
@phadej build and solver are independent implementations, you should raise a separate issue for `--pedantic` otherwise it might just get lost here.

@mgsloan it might be possible to create a custom index and specify that as an additional index in the temporary cabal config created for solver (`getCabalConfig`). This index will consist of all the `extra-dep: true` packages and these packages will no longer be treated as source/goal packages.

**Comment by snoyberg** [comment]
We've removed the solver support in #4670
