### ISSUE TITLE
Retry package downloads

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#279]
Related to [this blog post](http://www.yesodweb.com/blog/2015/06/cabals-does-not-exist-error-message), @radix [commented](http://www.reddit.com/r/haskell/comments/39fc17/explanation_cabals_does_not_exist_error_message/cs34wke):

> Python's `pip` package manager also doesn't retry, and I don't really understand why not. (this is one of the most common reasons for a travis job to fail for me, on my Python projects). It seems to me some conservative number of retries should definitely be done, say, 3.

Adding retry logic on download shouldn't be difficult, and ideally would be done with some kind of a config option to control the number of retries (and possibly the delay between them).

**Comment by DanBurton** [comment]
`verifiedDownload` now retries a given number of times (with no delay) when it gets an HttpException. Future work: use Control.Retry.

Something to note is that, due to this change, the `progressSink` might be run multiple times. Any code that uses `verifiedDownload` with a `progressSink` should make sure that the sink will behave correctly in the case of a partial run followed by a retry. (e.g. the sink should initialize and keep its own state, rather than relying on outside state, when possible.)
