### ISSUE TITLE
`stack build` installing executables in different locations

### ISSUE THREAD

**Issue by mitchellwrosen** [commercialhaskell/stack#2845]
```
Version 1.2.1, Git revision e4cceaf00b8e5b5eec6fbacbf979aa9fd1b9693f (dirty) (4136 commits) x86_64 hpack-0.14.1
```

Hi, I came across odd behavior and I'm not sure if it's a bug or not.

Using the following `stack.yaml`:

    docker:
      enable: true
    resolver: lts-7.12
    packages: []

I can install `bench`, which ends up in `.stack-work`:

    $ stack build bench
    ...
    $ find .stack-work -name bench -type f
    .stack-work/install/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/lts-7.12/8.0.1/bin/bench

But if I install `yesod-bin`, it ends up in `~/.stack`:

    $ stack build yesod-bin
    ...
    $ find .stack-work -name yesod -type f
    $ find ~/.stack -name yesod -type f
    /home/mitchell/.stack/snapshots/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/lts-7.12/8.0.1/bin/yesod

Why is that? Thanks!

**Comment by lwm** [comment]
Is this resolved via the conversation in #2849? Not sure, just triaging :beers:

**Comment by wolftune** [comment]
I'm not sure if this is resolved or not. The other issue was specific to extra-dep settings. This seems, based on what's above, to be unrelated to that.

**Comment by mgsloan** [comment]
Hi!  Sorry for the delay in answering this.  The reason is that `yesod-bin` is a package in the snapshot.  `bench` isn't in the snapshot, so it installs the latest one locally.

**Comment by wolftune** [comment]
Hah, I should have read this issue carefully. I actually knew the answer from the beginning and should not have referenced this with the other real bug (which has been addressed since). I was too wrapped up in the other issue to realize that this was unrelated. I didn't know offhand that bench wasn't in the snapshot, so I guess I assumed the report wasn't about that issue, since that seems more obvious to me at least. Ah well. :P
