### ISSUE TITLE
`stack clean` does a clone if the stack.yaml has changed

### ISSUE THREAD

**Issue by silky** [commercialhaskell/stack#2847]
i'd expect that `stack clean` should just delete things; not re-clone some `package` deps if i happened to change the commit version that they come from just before executing `stack clean` ...

**Comment by mgsloan** [comment]
The resolution of https://github.com/commercialhaskell/stack/issues/2811 should apply to `stack clean` as well.  Does this still occur with stack-1.3?

**Comment by silky** [comment]
it does

sorry, i should've listed the version of stack in the report:

```
04:44 PM noon ∈ src@master>stack --version
Version 1.3.1, Git revision 737ee751654cba4b2547b50628c9a5a78ddc6f8b x86_64 hpack-0.15.0
```

**Comment by mgsloan** [comment]
Ah, I looked into the code, and it turns out to be quite nontrivial to support this.  For example, `stack clean target1 target2` requires loading up all the local cabal files.

In theory it would be possible, but would require quite a bit of code for this special case.  As such closing as wontfix.  Thanks for bringing it up, but I think this is an acceptable deficiency.
