### ISSUE TITLE
stack version weirdness, lack of removal instructions

### ISSUE THREAD

**Issue by wolftune** [commercialhaskell/stack#2848]
I first did the curl thing for install to /usr/local/bin/stack and that worked, had v 1.2.0. Now, others are having an issue related to 1.3.0 so I went to upgrade. First, I tried the repo, but the old version seemed to override the 1.3.0 apt installed version (I'm on Ubuntu 16.04). Then I tried `stack upgrade` and that did a ton of building and put a binary in my own home directory but:

```
~$ curl -sSL https://get.haskellstack.org/ | sh
Stack Version 1.3.0 already appears to be installed at:
  /home/aaron/.local/bin/stack
Use 'stack upgrade' or your OS's package manager to upgrade.
~$ stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0
```

Is stack reporting its version wrong?

Also, there should be instructions on how to *remove* stack when installed via the curl thing instead of package manager.

**Comment by wolftune** [comment]
`sudo rm /usr/bin/stack && sudo rm /usr/local/bin/stack` worked, and I was then able to do the curl command again, but this isn't a good way to upgrade.

**Comment by lwm** [comment]
> Is stack reporting its version wrong?

You were using the other executable.

Sorry you had a bad upgrade experience. I haven't noticed this behavior either but it is definitely a bug. Stack should know which executable it should be replacing and not just fire a new one into `$HOME/.local/bin`.

**Comment by mgsloan** [comment]
Logic for replacing the current stack executable could be tricky.  Namely, upgrade uses `stack install` underneath and there's no way to rename it to a different executable name than `stack`.  We could vary `local-bin-path`, but that seems a bit hacky.  It'd also need to have logic to check whether it can write to that path (otherwise it'd fail at the very end).

So, closing this as a support ticket.
