### ISSUE TITLE
`readelf` error when building with profiling enabled

### ISSUE THREAD

**Issue by borsboom** [commercialhaskell/stack#2851]
Encountered by @dysinger.  Additional info from him:

> what may have triggered this bug above is that I had profiling enabled for libraries & exes
> yep. If I comment out the profiling options in my stack.yaml then it works fine.
<img width="720" alt="screen shot 2016-12-16 at 7 24 42 am" src="https://cloud.githubusercontent.com/assets/2164261/21267800/c52b73a8-c360-11e6-820a-18aa4655c887.png">

Possible culprit: https://github.com/commercialhaskell/stack/pull/2801/files#diff-eda6dc79c51b46a15020a1b28b794f50R97

Likely related: #2829

**Comment by borsboom** [comment]
ping @SASinestro

**Comment by SASinestro** [comment]
It's guessing the path wrong... I don't have access to a computer to test it, but if I was guessing, it seems like the problem is probably the `-ghc7.10.3` part at the end of the filename.

Perhaps just getting rid of the `"-ghc", ver` bits in `hasDebuggingSymbols` would fix it.

**Comment by SASinestro** [comment]
Okay, I have a fix for the issue at hand (along with a general prettying up of the heuristic code). In addition, this should never have come up in the first place, because `stack` was only checking if the debugging symbols were present when they weren't needed (and ignoring their absence when they were).

The fix process did reveal a bigger problem that I hadn't thought about earlier – All of the bindists currently have the core libraries built stripped, which means that there are the two following options, neither good:
1. Make all new bindists with [stripping disabled](https://ghc.haskell.org/trac/ghc/ticket/10601).
2. Keep a list of the non-rebuildable packages wired into GHC and exclude those from the check, leaving users unable to follow their debugging trail into `base`.

I'm just testing it a bit more, and then I'll open a PR.
