### ISSUE TITLE
stack list-dependencies --license is wrong for base

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#2871]
Running `stack list-dependencies --license` I see:

```
base <unknown>
ghc-prim <unknown>
integer-gmp <unknown>
template-haskell <unknown>
```

However, running `stack exec -- ghc-pkg describe base` correctly states that `base` is `BSD3`. I guess it's because these packages are "built in" - if so, hardcoding knowledge for them might not be too bad.

**Comment by mgsloan** [comment]
I've investigated this a bit, and I think it is due to the line after [this one](https://github.com/commercialhaskell/stack/blob/ccd5994ab6687fbc890d0f29f6298f47d3b611e2/src/Stack/Build/Source.hs#L175).  Not sure why wiredInPackages are removed from the source map, but I'm assuming there's a good reason for it.

I've modified the function to optionally include wired in packages, so now `stack list-dependencies --license` works as expected!
