### ISSUE TITLE
[Website] Explain what stack is actually *for*. Explain *why* one would want to use it.

### ISSUE THREAD

**Issue by Evi1M4chine** [commercialhaskell/stack#2951]
The website currently does a poor job in explaining what the point of stack is. The idea behind it.

As it stands, it says it’s for developing “commercial” (whatever that is… I hope it doesn’t mean Imaginary Property Mafia) Haskell software, yet isn’t an IDE.

Then it lists ”features” that one either already has, or that only cause more hassle without any advantages.
- _Installing GHC automatically, in an isolated location._ → Why would I create that mess? Why not use the GHC installed with my package manager, that actually has all the optimizations for and is integrated into my system?
- _Installing packages needed for your project._ → Ditto. That’s what the OS package manager is for.
- _Building your project._ → You mean running a build automation tool? Why do I need stack to do that?
- _Testing your project._ → Ditto. And how could it even test properly, without me actually creating tests and the parameters for them?
- _Benchmarking your project._ → Again, how would it do that, and what does it offer that the available tools don’t already do?

All of this can be achieved with the existing tools and a make script with different targets.
What exactly is the thing that it offers to make it special? Its unique selling point. Its _point_.

There is the (somewhat hidden-away) section “Why stack?”, yes…
But it only contains the _who_ and _where_, and not the _why_ that its title implies. The only other thing it contains, is meaningless empty phrases that basically all go: “Explanation for this tool that helps developers: It is a tool that helps developers.” _That’s not an explanation! That’s a “Microsoft Help”planation! It is just saying the same thing that was implied as known for the question in the first place!

As you can see from my complaints, this is quite enraging, given the complete obviousness of what is wrong here, and how the site always juuust dances around actually answering anything, as if to deliberately tease and troll you. All it made me do, is strongly dislike it, and its community. Not that I’m surprised, given that it mainly targets things that smell like they are problems on _Windows_, and given how “commercial” usually means Imaginary Property Mafia, aka organized crime that wants to steal hard-earned money from humans, and not work (aka profit) to actually earn it too. (Not that it can’t mean good things too. Like treating work as the service that it is, and not acting as if information can be “owned”. But that’s unfortunately a rare case when the word “commercial” is used.)

I’d rather have a site that doesn’t do that, and tells me why I would want to use stack. As the Haskell community, until now, has always shown a high level of intelligence and friendliness, that is the refreshing opposite of the usual “industry” standard practices.

**Comment by lwm** [comment]
> All it made me do, is strongly dislike it, and its community.
> As the Haskell community, until now, has always shown a high level of intelligence and friendliness

?

Please submit a PR improving the documentation. Your contribution would be most welcome :+1:

**Comment by Blaisorblade** [comment]
I agree these questions should be answered somewhere. I'd suggest to answer them in the FAQs, though I'm not sure they're very frequent. I don't think they should all be answered in the homepage though; we might want a link to a comparison with alternatives, but see below.*

> As you can see from my complaints, this is quite enraging, given the complete obviousness of what is wrong here, and how the site always juuust dances around actually answering anything, as if to deliberately tease and troll you.

What's "obvious" to one isn't necessarily to others.
In particular, most versions of libraries and GHC are not available on most package managers, and during development you can't be sure you can work with the versions included on your distro—or assume other developers have compatible versions. Also because of this, few use Make for Haskell these days.
However, if you ship an application to final users then, by all means, maintaining packages for distros of your choice is an option.

In fact, even just building packages incrementally is trickier than what's done by Make or by Makefiles generated by most Make frontends: you only have to rebuild a file if the *extracted interface* of any dependency *changes* (not just if its timestamp is updated). I know how that can be implemented over Make.

Also, FWIW, people also use language-specific tools like Stack over Make (for package management and, where appropriate, building) for Java, Scala, JavaScript, Ruby, Python, (IIUC) Perl, Rust, PHP... some for installing libraries, and others for managing together multiple versions of the relevant environments for when multiple apps have different requirements. And many C/C++ projects also use other tools like autotools or CMake (though there, at least, people generate Makefiles), so I guess for many the question "why not just Make" isn't asked much these days. But it's not a matter of fashion.

*There is *one* thing the site doesn't say though, possibly on purpose (though I didn't write those docs). This part:

> A large impetus for the work on stack was a large survey of people interested in Haskell, which rated build issues as a major concern. The stack team hopes that stack can address these concerns.

is a diplomatic version of "everybody used cabal-install before and there were tons of problems, so we built stack" (or something like that). But it'd be bad style to bash competitors on the homepage. Also, the homepage tries to simply explain stack, not to compare it with cabal since there's lots of contention on what's the right approach.

> commercial... Imaginary Property Mafia

In our community, "commercial" just means professional developers (as opposed to hobbyists), for which build tools shouldn't be a bottleneck, and where the producer might want to support the software. Whether the software is then proprietary or open source is an orthogonal concern, of no relevance to the build tool. In fact, stack is an open source tool supported commercially, like most Haskell libraries. (Many commercial users also need convenient deployment options).

> given that it mainly targets things that smell like they are problems on Windows

Stack was introduced to solve "cabal hell”. The fact that pure Haskell builds (with both cabal and stack) are automatically portable to Windows, but also *BSD, OS X with their non-Linux-like tools is a great advantage, but even if only Linux existed Make wouldn't cut it IMHO.

**Comment by lwm** [comment]
For anyone coming this way, it seems @Blaisorblade's above comment has some actionables.
