### ISSUE TITLE
More control over ghcjs-boot

### ISSUE THREAD

**Issue by mikusp** [commercialhaskell/stack#2952]
I am working on a project involving ghcjs. Right now, ghcjs-boot can be very time-consuming.

As I found in the stack sources, it's executed with `--clean` option (https://github.com/commercialhaskell/stack/blob/master/src/Stack/Setup.hs#L1190), but ghcjs-boot supports more.

I'd be particularly interested in speeding up booting by using parallel compilation (`-jN` option) and disabling profiling (`--no-prof` option). I think other options would be of interest to other users.

**Comment by tolysz** [comment]
maybe generic `--ghcjs-boot-foo` ? in a generic way... `ghcjs-no-boot-clean`

On 26 Jan 2017 11:28 a.m., "Marcin Mikołajczyk" <notifications@github.com>
wrote:

I am working on a project involving ghcjs. Right now, ghcjs-boot can be
very time-consuming.

As I found in the stack sources, it's executed with --clean option (
https://github.com/commercialhaskell/stack/blob/master/src/Stack/Setup.hs#
L1190), but ghcjs-boot supports more.

I'd be particularly interested in speeding up booting by using parallel
compilation (-jN option) and disabling profiling (--no-prof option). I
think other options would be of interest to other users.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/commercialhaskell/stack/issues/2952>, or mute the thread

**Comment by mikusp** [comment]
It could be named `--ghcjs-boot-options`, to be consistent with current `--ghc-options`.

**Comment by tolysz** [comment]
I will add 2 new options: `--ghcjs-boot-options --foo --ghcjs-boot-options bar` and `--[no-]ghcjs-boot-clean true` 
will give `ghcjs-boot --foo bar --clean`

**Comment by mgsloan** [comment]
Merged, so closing.  Thanks @tolysz !

**Comment by tolysz** [comment]
@mikusp Could you check if it gives enough flexibility for you?

**Comment by mikusp** [comment]
Yes, it's great. Thank you!
