### ISSUE TITLE
Wrong Cabal version warnings

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#3029]
While trying to build stack itself, I see the following warning:

> Cabal file warning in /home/b/src/Haskell/stack/stack/stack.cabal: Ignoring unknown section type: custom-setup

I'm not sure if this is related to other problems I'm having (deps failing to build with no error message in build logs), but it seems like it's probably a bad thing.

Plus, if I add update stack.cabal to have the appropriate cabal-version>=1.24, I get the additional warning

> Cabal file warning in /home/b/src/Haskell/stack/stack/stack.cabal: This package requires at least Cabal version 1.24

Shouldn't that be a critical error?

Also, I see there's a --upgrade-cabal option to stack-setup. However, after running that I still get the same warning.

### Stack version

> Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0

### Misc

    $ stack exec ghc-pkg list Cabal
    /home/b/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/package.conf.d
       Cabal-1.22.5.0
       Cabal-1.24.2.0
    /home/b/.stack/snapshots/x86_64-linux/lts-6.25/7.10.3/pkgdb
    /home/b/src/Haskell/stack/stack/.stack-work/install/x86_64-linux/lts-6.25/7.10.3/pkgdb
       Cabal-1.24.2.0

**Comment by m4lvin** [comment]
Same thing happening here: https://travis-ci.org/m4lvin/HasCacBDD/builds/208776933#L226 

Also `stack sdist` fails with `This package description follows version 1.23 of the Cabal specification. This tool only supports up to version 1.22.8.0.` -- My guess is that "this tool" is the cabal version used by stack? But both globally installed and in the project and in the stackage snapshot I have 1.24.

Will this be fixed with #2866?

**Comment by mgsloan** [comment]
Stack version 1.3.2 is indeed built with Cabal-1.22.8.0, which is where the message is coming from.

Happily, the HEAD version / draft release of version 1.4 both will use Cabal-1.24, and so this is already fixed.

> Shouldn't that be a critical error?

Not necessarily, things might work just fine, since we're just using it to parse the package's description.  It is an indication that things might go wrong, though.

For example, one of the main differences with 1.24 is support for `custom-setup` stanzas.  Quite often, older stack can build packages without knowledge of `custom-setup` stanzas.
