### ISSUE TITLE
GHC 8.0.2 not available on OS X

### ISSUE THREAD

**Issue by mewa** [commercialhaskell/stack#3058]
When running `stack setup` with `resolver: lts-8.5` (or any resolver which implies ghc > 7.10) an error occurs saying there's no ghc version compatible with it. 
```
>stack setup
No information found for GHC version 8.0.2.
Supported GHC major versions for OS key 'macosx': 7.8, 7.10
```
You can certainly download a package directly from haskell.org or via homebrew, so it's probably a matter of uploading the proper package.

**Comment by mgsloan** [comment]
I'm betting your stack version is old, and still using the old setup info format which only has info for <= 7.10: https://github.com/fpco/stackage-content/blob/master/stack/stack-setup.yaml

The other possibilities are if you are using a custom `setup-info` or `--setup-info-yaml`

**Comment by mewa** [comment]
```
>stack upgrade
Current Stack version: 1.3.2, available download version: 1.3.2
Skipping binary upgrade, your version is already more recent
```
Apparently stack is up to date. 
I'm not using anything custom too, just basic boilerplate stuff stack handles by itself.

**Comment by mgsloan** [comment]
Hmm, well that's a real mystery since the list of supported versions should come directly from `stack-setup-2.yaml`: https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml#L344

Are you 100% sure you're using the right stack version?  Try `stack --version`.  The error message seems to be from an old stack.  See the code for the message in 1.3.2: https://github.com/commercialhaskell/stack/blob/v1.3.2/src/Stack/Setup.hs#L175

It should just say "Supported versions for OS key ..." and not "Supported GHC major versions for OS key ..."

**Comment by mewa** [comment]
Actually, it might've been an old stack version. When trying to fix it I installed a new version of ghc, and used the uninstall-hs and rm-rf later on. 

While I'm sure it did occur after downloading the latest version, now that I think of it, it must've been some link clash resulting in using the old stack instead of the new one. I hadn't checked stack version earlier, so I can't tell if that's the case (but it probably is).
