### ISSUE TITLE
--local-bin-path with an absolute path fails with --docker

### ISSUE THREAD

**Issue by utdemir** [commercialhaskell/stack#3090]
When you use `--docker --local-bin-path <absolute-path>`, it fails the locate the directory even if the directory actually exists on the host machine. It works if you don't use `--docker` or with a relative path.

### Steps to reproduce

```
$ stack new test simple
…
All done.
$ cd test
$ mkdir bin/
$ stack install --docker --local-bin-path $(pwd)/bin/
No directory could be located matching the supplied path: /var/folders/fh/7xt8k4r14dsfksbsfm261nh00000gn/T/tmp.XZIJNIGk/test/bin/
```

But it works fine with a relative path(omitting `$(pwd)/`), or without `--docker`.

### Expected

`--local-bin-path` to behave just as without `--docker`.

### Actual

It failed with `No directory could be located matching the supplied path`, probably it was looking in the container instead of the host.

### Stack version

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

### Method of installation

* homebrew

**Comment by borsboom** [comment]
Does it work without `--local-bin-path` (e.g. `stack install --docker`)?  It looks like you're trying to build outside your home directory, which is unlikely to work on macOS since only your home directory is available to the Docker VM.  BTW, Stack's Docker integration is not officially supported on macOS (many edge cases like this don't work).
