### ISSUE TITLE
Missing binary distributions for `linux64-gmp4-nopie`, needed on RHEL 6 with upgraded GCC

### ISSUE THREAD

**Issue by akuhlens** [commercialhaskell/stack#3112]
### General summary/comments (optional)
Running stack setup returns error output. I couldn't find any documentation on how to handle debugging such problems. 
```
$stack setup
Unable to find installation URLs for OS key: linux64-gmp4-nopie
```

### Steps to reproduce
I am not sure this will be reproducible.
Here is a gist that documents the output with debugging information:
```
[akuhlens@h3 ~]$ uname -a
Linux h3.karst.uits.iu.edu 2.6.32-696.el6.x86_64 #1 SMP Tue Feb 21 00:53:17 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
[akuhlens@h1 Dynamizer]$ stack setup -v
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
2017-04-06 13:13:25.968449: [debug] Checking for project config at: /gpfs/home/a/k/akuhlens/Karst/Dynamizer/stack.yaml
@(Stack/Config.hs:935:9)
2017-04-06 13:13:25.987787: [debug] Loading project config file stack.yaml
@(Stack/Config.hs:960:13)
2017-04-06 13:13:26.141765: [debug] Trying to decode /gpfs/home/a/k/akuhlens/Karst/.stack/build-plan-cache/x86_64-linux/lts-8.0.cache
@(Data/Store/VersionTagged.hs:68:5)
2017-04-06 13:13:26.243327: [debug] Success decoding /gpfs/home/a/k/akuhlens/Karst/.stack/build-plan-cache/x86_64-linux/lts-8.0.cache
@(Data/Store/VersionTagged.hs:72:13)
2017-04-06 13:13:26.248841: [debug] Run process: /sbin/ldconfig -p
@(System/Process/Read.hs:306:3)
2017-04-06 13:13:26.250574: [debug] Process finished in 1ms: /sbin/ldconfig -p
@(System/Process/Read.hs:306:3)
2017-04-06 13:13:26.312643: [debug] Run process: /N/soft/rhel6/gcc/4.9.4/bin/gcc -v
@(System/Process/Read.hs:306:3)
2017-04-06 13:13:26.404092: [debug] Process finished in 91ms: /N/soft/rhel6/gcc/4.9.4/bin/gcc -v
@(System/Process/Read.hs:306:3)
2017-04-06 13:13:26.404275: [debug] PIE disabled
@(Stack/Setup.hs:577:17)
2017-04-06 13:13:26.404463: [debug] Found shared library libtinfo.so.5 in 'ldconfig -p' output
@(Stack/Setup.hs:553:29)
2017-04-06 13:13:26.404955: [debug] Did not find shared library libtinfo.so.6
@(Stack/Setup.hs:567:38)
2017-04-06 13:13:26.405080: [debug] Did not find shared library libncursesw.so.6
@(Stack/Setup.hs:567:38)
2017-04-06 13:13:26.405164: [debug] Did not find shared library libgmp.so.10
@(Stack/Setup.hs:567:38)
2017-04-06 13:13:26.405231: [debug] Found shared library libgmp.so.3 in 'ldconfig -p' output
@(Stack/Setup.hs:553:29)
2017-04-06 13:13:26.405288: [debug] Using gmp4-nopie GHC build
@(Stack/Setup.hs:603:9)
Unable to find installation URLs for OS key: linux64-gmp4-nopie
```

### Stack version

```bash
$ stack --version 
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

### Method of installation

```bash
wget https://www.stackage.org/stack/linux-x86_64-static
```

**Comment by borsboom** [comment]
What Linux distribution are you using?  I wouldn't have thought there would ever be an environment that uses both an ancient libgmp version _and_ nopie.

**Comment by akuhlens** [comment]
Red Hat Enterprise Linux Server release 6.9 (Santiago)
It is a big compute cluster at my university.

**Comment by Blaisorblade** [comment]
> What Linux distribution are you using? I wouldn't have thought there would ever be an environment that uses both an ancient libgmp version and the quite new no-pie.

We *might* want to support RHEL 6 (see below). But the above is not just RHEL 6.9, but it's RHEL 6.9 with an upgraded compiler. The above uses GCC 4.9, the latest from the GCC 4.x series (https://gcc.gnu.org/gcc-4.9/)-GCC 5 has a different ABI.

Crucially: unless these people rebuilt the whole system, it should be possible to use the default compiler (without this `nopie` stuff) by changing the `PATH`, so that `stack` can use a `linux64-gmp4` bindist instead.

In my old department, still using a related distro (Scientific Linux 6.8, a variant of RHEL 6.8), the default compiler is GCC 4.4, and `gcc -v` doesn't mention `pie`-relevant stuff I think:

```
$ which gcc
/usr/bin/gcc
$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
```

### RHEL support cycle

RHEL installs have very long support cycles and are updated slowly — RHEL 6 came out on November 10, 2010 and is supported for at least 3 more years (search "End of Production Phase" at https://access.redhat.com/support/policy/updates/errata for details). RedHat "just" released RHEL 7 (2 years ago)—no RHEL 8 exists yet.

**Comment by borsboom** [comment]
We are definitely still supporting RHEL 6 at least as long as GHC continues to release bindists for it (that's why there's all the libgmp4 detection and stuff).  A new enough GCC to need nopie with a distro old enough to need libgmp4 is a weird combination though, and I don't think we're going to put a lot of extra effort into that.

The good news, however, is that there's a good chance this is really easy to support and only needs some additional metadata in [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml).  You can try it by making a local copy of this file, and then adding a `linux64-gmp4-nopie` section based on the `linux64-nopie` section but pointing to the same bindists referenced by the `linux-gmp4` section.  Then you can use `stack setup --stack-setup-yaml=<PATH-TO-LOCAL-COPY>` to try it out.  If that works, please make a PR against [fpco/stackage-content](https://github.com/fpco/stackage-content) to it supported out of the box.

**Comment by Blaisorblade** [comment]
> The good news, however, is that there's a good chance this is really easy to support and only needs some additional metadata in stack-setup-2.yaml. You

👍
If that wasn't clear: if that doesn't work, I suggested an (inferior but easier) workaround—switch to the compiler that came with the distro locally (at least as long as it's installed). If yours work, it's of course better.

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time. RHEL 6 was end of life on 30 November 2020.
