### ISSUE TITLE
A project named 'interactive' fails to build

### ISSUE THREAD

**Issue by th0br0** [commercialhaskell/stack#3172]
### General summary/comments (optional)
A project called 'interactive' causes a silent error while constructing the build plan:

```
Error: While constructing the build plan, the following exceptions were encountered:

Plan construction failed.
```
### Steps to reproduce
1. `stack new interactive`
2. `cd interactive`
3. `stack build`

### Expected
Stack builds the project

### Actual
Stack fails to create the build plan without printing an error
### Stack version

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

### Method of installation
* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by Blaisorblade** [comment]
The log with `-v` doesn't help, and my cabal builds the project successfully:
https://gist.github.com/Blaisorblade/ce104829aad5260823d82bf44fbd4af9

And the generated files look fine.

But "interactive" is a wired-in package according to sources of both Stack (see src/Stack/Constants.hs) and Cabal, both in 7.10.1 and 8.0.2:

https://downloads.haskell.org/~ghc/7.10.1/docs/html/libraries/ghc/src/Module.html#integerPackageKey
https://downloads.haskell.org/~ghc/8.0.2/docs/html/libraries/ghc-8.0.2/Module.html

I'm not sure what "interactive" is supposed to be; since other wired-in packages seem GHC dependencies, I'm guessing this might have to do with ghci. Maybe the name is outdated. No real clue.

If `interactive` is not a real wired-in package, maybe removing the mention of "interactive" from src/Stack/Constants.hs would allow the package to build without other changes, but I'm somewhat clueless.

**Comment by mgsloan** [comment]
Not sure what it is used for either, but it's probably best to be consistent here.  `stack new interactive` (and other wired in packages) will now fail with

```
The name "interactive" is used by GHC wired-in packages, and so shouldn't be used as a package name
```

For build, the output is now

```
Error: While constructing the build plan, the following exceptions were encountered:

Can't build a package with same name as a wired-in-package: interactive

@(Stack/Build/ConstructPlan.hs:227:13)
Plan construction failed.
*** Exception: ExitFailure 1
```
