### ISSUE TITLE
--jobs doesn't seemed to be passed to gmake

### ISSUE THREAD

**Issue by marmalodak** [commercialhaskell/stack#3174]
stack --stack-root /mnt/myth/john/projects/jupyter/haskell//stack --no-system-ghc --jobs 8 --color auto --verbosity debug setup
    Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
...

    2017-05-13 15:03:08.125290: [debug] Run process: /usr/bin/gmake install

I would have expected to see:

    2017-05-13 15:03:08.125290: [debug] Run process: /usr/bin/gmake --jobs=8 install

**Comment by Blaisorblade** [comment]
I see what you mean, but Stack mainly uses --jobs when building Haskell programs. You omit lots of context from logs, but since it's stack setup I assume that make is just installing a binary distribution of GHC, and I've never heard that parallel installations are faster. If they are (maybe on SSDs), the thread count seems unlikely to relate to the processor count.

I searched through the stack codebase, and it seems gmake is only ever used to install GHC.

There might be a few packages with native components where make is used for nontrivial parts of the build—but I think those calls to make are done by the cabal library.

Hence, if you find cases where `-j X` would speed up make but is not passed, the issue would probably be with the cabal library—though it might depend on how Stack uses it, not sure.

Please don't be offended, but closing for now. Feel free to reopen if you feel appropriate.
