### ISSUE TITLE
ghc-8.2.1-rc2 issue on Arch linux

### ISSUE THREAD

**Issue by dawei-dev** [commercialhaskell/stack#3177]
I have followed this guide:
http://taylor.fausak.me/2017/05/17/testing-ghc-release-candidates-with-stack/

It works on Windows
But on Arch Linux I get:

> No information found for ghc-8.2.0.20170507.
> Supported versions for OS key 'linux64-ncurses6': GhcVersion 7.10.3, GhcVersion 8.0.1, GhcVersion 8.0.2
>

**Comment by borsboom** [comment]
Arch uses different GHC bindists than the default because it uses libncurses6 (whereas stock GHC bindists are build to dynamic link with libtinfo5).  So there are two ways to progress:

1. Build your own GHC 8.2.1-rc2 bindist from source on Arch and reference that in the setup-info (replacing `linux64` with `linux64-ncurses6` as the key).

2. Install [ncurses5-compat-libs from AUR](https://aur.archlinux.org/packages/ncurses5-compat-libs/) and then force Stack to use the standard GHC bindist by doing something like `stack --ghc-build=standard setup`.
