### ISSUE TITLE
stack build fails to clone new commit on docker image if git is not on the docker image

### ISSUE THREAD

**Issue by silky** [commercialhaskell/stack#3196]
it fails with:

```
Executable named git not found on path: ["/home/noon/.stack/snapshots/x86_64-linux-dkd1ce2ff9c9560b648268df668d177711/lts-8.15/8.0.2/bin","/home/noon/.stack/programs/x86_64-linux-dkd1ce2ff9c9560b648268df668d177711/ghc-8.0.2/bin","/opt/host/bin","/home/noon/dev/deep-scite/deepscite-hs/.stack-work/docker/_home/.local/bin","/usr/local/sbin","/usr/local/bin","/usr/sbin","/usr/bin","/sbin","/bin"]
```

a workaround is to just to a `stack build`, which does the clone, then cancel that when it gest to the actual building stage, and do a `stack --docker --docker-image=... build` again.

stack version:
`Version 1.4.1, Git revision f2cbb71a20dca0b793744cb678a1b18495613dd6 x86_64 hpack-0.17.0`

on ubuntu

**Comment by borsboom** [comment]
The Docker image needs to have the same tools installed as are generally required to run Stack.  That includes `git`.

**Comment by silky** [comment]
why can't the git executable from the host be used?

alternatively, if it shouldn't ever be used, then it shouldn't be possible to use the workaround?

**Comment by borsboom** [comment]
When Stack runs with Docker enabled, the host Stack just reads the configuration up to the point where it knows it needs to switch to Docker, and then re-executes itself in a Docker container, and from that point all the rest of Stack runs within the container where it no longer has the ability to use the host's `git`.

I suppose it would, in theory, be possible to re-architect Stack so that these kinds of functions are split up and that it did all the preparatory work on the host before using Docker to perform the actual build, or for the container-Stack to communicate with the host-Stack to ask it to perform certain tasks on the host, but that would be a major undertaking.  It's architecturally much simpler to just have everything run in the container context.

**Comment by silky** [comment]
okay; fair enough.

i ask partially because i think there is a related issue; which is that if i set the commit hash in the stack.yaml to `master`, then it actually doesn't give an error when building at all, even if there is an update to that branch since the last build; it just silently continues on as-if it's using the latest; but maybe that's a quirk of using `master` as the commit instead of a commit hash.

**Comment by borsboom** [comment]
[The docs](https://docs.haskellstack.org/en/stable/yaml_configuration/#complex-package-locations-location) say

> Note: it is highly recommended that you only use SHA1 values for a Git or Mercurial commit. Other values may work, but they are not officially supported, and may result in unexpected behavior (namely, stack will not automatically pull to update to new versions).
