### ISSUE TITLE
Failure to locate binary while installing cabal-helper

### ISSUE THREAD

**Issue by Pastafarianist** [commercialhaskell/stack#3202]
```
$ stack install cabal-helper
...
Couldn't find executable cabal-helper-wrapper in directory <project-directory>/.stack-work/install/x86_64-linux/lts-8.5/8.0.2/bin/

$ find -name '*cabal-helper*'
...
./.stack-work/install/x86_64-linux/lts-8.13/8.0.2/libexec/x86_64-linux-ghc-8.0.2/cabal-helper-0.7.3.0/cabal-helper-wrapper
...
```

Steps to reproduce:

1. `git clone https://github.com/input-output-hk/cardano-sl.git`
2. `cd cardano-sl`
3. `stack install cabal-helper`

Output on my machine (with `--verbose` flag): https://gist.github.com/Pastafarianist/8ed6eec3f0d891e1fdb2def97c8a5187

See also https://github.com/DanielG/cabal-helper/issues/28 (a mirror of this issue in the `cabal-helper` repository).

### Stack version

I am using `stack-1.3.2` (because of https://github.com/commercialhaskell/stack/issues/3151) which I installed from the Arch repository (`sudo pacman -U https://archive.archlinux.org/packages/s/stack/stack-1.3.2-64-x86_64.pkg.tar.xz`). My [`stack --version`](https://gist.github.com/Pastafarianist/0d543e6afa78445ff90a81e6e177efd2).

**Comment by snoyberg** [comment]
This appears to be due to very special logic in the `Setup.hs` file for `cabal-helper`, which prevents the `cabal-helper-wrapper` executable from being copied to the appropriate directory. There are potential workarounds in Stack, but overall the metadata we're able to read from the .cabal file is simply misleading in this case. I'd recommend just using the `stack build` command instead of `stack install`.

**Comment by mgsloan** [comment]
Closing as a support issue.
