### ISSUE TITLE
ghc crashes because api-ms-win-core-localization-l1-2-2.dll isn't found.

### ISSUE THREAD

**Issue by arrowd** [commercialhaskell/stack#3216]
I'm using stack 1.4.0 on Windows Server 2012 R2. When building https://github.com/haskell/haskell-ide-engine/ and specifically `Language.Haskell.LSP.TH.ClientCapabilities` from haskell-lsp, the GHC process dies, because api-ms-win-core-localization-l1-2-2.dll wasn't found.

There is indeed no such dll in my Windows/system32 directory, but the source of the problem still isn't clear.

**Comment by Mistuke** [comment]
`api-ms-win-core-localization-l1-2-2.dll` is part of the `"API set"` feature introduced in Windows 8, where the  kernel redirects api calls based on namespaces to different dlls. This in order to amongst other reduce the memory footprint of applications (loading smaller dlls instead of big monolitical ones.).

Anyway, with the introduction of Windows 8 (Windows server 2012) the api sets were versioned `-0.dll` with Windows 8.1 (Windows Server 2012 R2) they were `-1.dll` and with I believe Visual Studio 2015 came the `-2.dll` api sets.

I don't believe we link directly to any of these. or at least we shouldn't be, that would be wrong. But in this case I think the kernel has somehow decided to use the newer api sets but they're missing.

You could try updating the UCRT files https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows and see if that works, but unless we actually do accidentally link directly to these files, I don't think it's a ghc bug, more an install issue.

**Comment by arrowd** [comment]
> You could try updating the UCRT files

Nope, unfortunately that didn't work. My system is up-to-date so these updates aren't applying.

**Comment by arrowd** [comment]
Upgrading nightly-2017-06-12 to nightly-2017-06-14 resolved the problem. I guess this can be close.

**Comment by arrowd** [comment]
Now I'm getting this error with nightly-2017-06-14. But! Upgrading to nightly-2017-06-16 fixes the problem again. As if it works only when compiling the package for the first time.

**Comment by mgsloan** [comment]
Sounds like there's at least a partial workaround.  Either way, I don't think there's much stack itself can do about this.  Closing as upstream issue / support.

**Comment by arrowd** [comment]
In case anyone also stumble on this, the final workaround was:

```
stack clean
stack setup --reinstall
```
