### ISSUE TITLE
Child processes spawned by benchmark fail to receive POSIX signals

### ISSUE THREAD

**Issue by tebello-thejane** [commercialhaskell/stack#3250]
### General summary/comments (optional)

Benchmark code which attempts to kill child processes fails to do so, but the same code in an executable works.

### Steps to reproduce

I created a new project with `stack new zombie simple` using `stack 1.4.0` and LTS-8.21.

`.cabal` file:
```
name:                zombie
version:             0.1.0.0

homepage:            https://github.com/githubuser/zombie#readme
license:             BSD3
license-file:        LICENSE
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
build-type:          Simple
cabal-version:       >=1.10
extra-source-files:  README.md

executable zombie
  hs-source-dirs:      src
  main-is:             Main.hs
  default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5, process, unix
  ghc-options:         -threaded -with-rtsopts=-N -with-rtsopts=-T -with-rtsopts=-qg -rtsopts

benchmark zombie-bench
  type: exitcode-stdio-1.0
  hs-source-dirs:      bench
  main-is:             Main.hs
  default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5, process, unix
  ghc-options:         -threaded -with-rtsopts=-N -with-rtsopts=-T -with-rtsopts=-qg -rtsopts
```

`src/Main.hs` and `bench/Main.hs` both look like this:
```haskell
module Main where

import System.Environment (getEnv)
import System.Process.Internals
import System.Process
import System.Posix.Signals
import Control.Concurrent

main :: IO ()
main = do
  (_, _, _, ph) <- createProcess (shell "sleep 20")
  putStrLn "stuff"
  threadDelay 100
  putStrLn "more"
  withProcessHandle ph $ \ph_ ->
    case ph_ of
      OpenHandle pid -> do
        signalProcess sigKILL pid
        signalProcess sigINT pid
        signalProcess sigTERM pid
        signalProcess sigKILL pid
      ClosedHandle _ -> error "shouldn't happen"
```

I then run `stack bench`.

### Expected

I expect the benchmark to kill the spawned `sleep 20` process and exit almost immediately.

### Actual

The benchmark waits for 20 seconds before exiting. That is, the child is not killed.

Note that in a larger project, replacing `sleep 20` with `stack test` produces the same behaviour, thus the fact that `sleep` is built-in might be moot.

Similar behaviour is not observed with `cabal sandbox init && cabal bench`, using `cabal-install` version 1.24.1.0, and version 1.24.1.0 of the library.

### Stack version

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

On Ubuntu 16.04.

### Method of installation
Binary was installed eons ago, and I have been using `stack upgrade` ever since.

**Comment by Blaisorblade** [comment]
Your bug report looks careful, but it's not obvious that what you're using is guaranteed to work. And when it works, it probably does for reasons trickier than you're describing.
Which is why I've marked this as `Support`, though I might be wrong.

While wondering about it I might have figured out some not unreasonable hypotheses—see below.

> I expect the benchmark to kill the spawned sleep 20 process and exit almost immediately.

I tried to figure out what should happen, but gave up. This involves too many layers of non-compositional stuff^H^H pitchforks. If you could avoid signals, that would be great for you.

Tip: Can you compare the behavior of running `zombie-bench` directly with `stack bench`? I expect running `zombie-bench` directly might work "better".

In general, I expect potentially different results.

Issues:
- sleep is NOT a shell builtin (see `man builtins` and `man bash`), and it seems that `createProcess (shell "sleep 20")` will run at least two processes, one for the shell and one for `sleep`.

- You're only killing one PID, and I guess it's the shell, and probably only once (because it should die after the first SIGKILL, unless it's multithreaded). I'd be surprised if the other signals do anything, but this whole things looks tricky. After the first signal, children might or might not be killed depending on a bunch of things. Stack seems to redirect the output—and if the shell output does not go to a terminal, I think different rules apply. Switching from `shell "sleep 20"` to using `proc` correctly might make things a bit more robust—but then again, `stack test` is a tower of processes, so again tricky.

- More threads/processes might be created by the `process` implementation, by `stack bench`/`cabal bench` monitoring the process, by the GHC runtime itself, and what not. At least, it seems `delegate_ctlc` is not set in your scenario, so there's one less layer of wrapping involved, see https://hackage.haskell.org/package/process-1.6.0.0/docs/System-Process.html#g:4 and maybe https://www.cons.org/cracauer/sigint.html.

**Comment by tebello-thejane** [comment]
Thanks for the response, @Blaisorblade.

The general form of the code essentially comes from here: [Guaranteed termination of external process in Haskell](https://stackoverflow.com/questions/33446996/guaranteed-termination-of-external-process-in-haskell). At first `terminateProcess` didn't work, and I thought that might be the issue. I'm demonstrating here that I'm trying by all means to kill the child process, and it still hangs around.

Running `zombie-bench` directly indeed does **not** exhibit this behaviour. It behaves exactly as if I had run `stack exec -- zombie`.

This is not merely a toy experiment -- it popped up when I was trying to do something less trivial. The [`tmp-postgres`](https://hackage.haskell.org/package/tmp-postgres) library functions by spawning some PG process and then [killing it at the end with `terminateProcess`](https://github.com/jfischoff/tmp-postgres/blob/1d07a83e29f6ece45939b2a7d0f2686356c922f5/src/Database/Postgres/Temp/Internal.hs#L191). Right now, I cannot use it in a `stack` benchmark (and `cabal sandbox init && cabal install --only-dependencies && cabal bench` runs into dependency issues I don't have the patience to try and fix on such a large project), and I'd rather this code not run every time I run tests. If all else fails, I at least still have the option to build it as an executable...

I shall now attempt the following:
* Using `proc` instead of `shell`, and 
* Fiddling about with `delegate_ctlc`,

and report back.

Thanks, hey. :smiley_cat:

**Comment by Blaisorblade** [comment]
Thanks for the reference and motivation! That helps. I  think both you and the StackOverflow answer are just killing the shell, which might or might not kill its children. IIRC, if the shell runs on a terminal, by default children are killed. If I/O are connected to a file, by default children are not killed.

Falsifiable predictions from this working hypothesis:
- the PID you're sending signals to belongs not to `sleep` but to a parent shell process
- `proc` should help compared to `shell`, by removing this extra process. But might not be enough for multi-process commands.
- redirecting input/output (as in `stack exec -- zombie < /dev/null &> zombie.log`) should break your current version of `zombie`.
- manipulating process groups or sessions might fix the problem, and maybe `stack` could even do something about it.

----------

I forget details and can't find good references right now—the underlying reason might be job control, which is only enabled for shells connected to a terminal. This is dark magic I don't fully understand—I don't do this life anymore, but I look it up when these issues arise:
https://www.gnu.org/software/libc/manual/html_node/Orphaned-Process-Groups.html#Orphaned-Process-Groups.
https://www.gnu.org/software/libc/manual/html_node/Initializing-the-Shell.html#Initializing-the-Shell

Searching "killing process tree linux" finds also a few ideas that might be used as hacks here.

**Comment by tebello-thejane** [comment]
I can confirm that replacing `shell "sleep 20"` with `proc "sleep" ["20"]` indeed makes this problem go away. I will do a PR for the `tmp-postgres` library so I can at least use it further.

In my unqualified opinion, though, this is a bug. At least in that it differs from `cabal`'s behaviour, is undocumented, and unexpected. At least, what is the reason for this behaviour? I understand that `stack bench` has to spawn the executable as a process and wait for it to finish, but is there a *reason* why signals between child processes (the benchmark sends `SIGKILL` to *it's* child processes) are being interfered with? Is it a technical limitation, an unfortunate hack, or undefined behaviour?

Thanks once again, especially for the references. :smile:

**Comment by Blaisorblade** [comment]
The StackOverflow answer you cited is certainly at fault.

It kills a process (the shell) and expects a different one (the shell's child) to die. There's no guarantee that should happen. That code is *Bad(Tm)*. This is not quite undefined behavior, but this works only under very restrictive conditions, and that answer mentions no such caveat. That's why I said you're dealing with fragile tools, and I meant the Unix APIs. (I could comment or propose changes to the answer).

That's why using `proc` fixes the problem: one less process is involved. If you use `stack test` or something else though, I won't bet things will stay that simple.

IIUC, stack does nothing with signals, it just monitors I/O of the child process (they're redirected in some way, I'm not quite sure of the details). So the benchmark is not attached to a terminal directly. I'd bet we never promise otherwise 😄 

You wonder why redirecting I/O affects signals? That's *nix APIs for you. And if one complain with some *nix people, they might blame you for not having enough clue. (I'm serious, they can be mean).

Again, not sure Stack can fix this.

For a (not-so-related) example on how tricky signals can get, here's what Stack had to do to deal with a different scenario
https://www.fpcomplete.com/blog/2016/10/docker-demons-pid1-orphans-zombies-signals

**Comment by tebello-thejane** [comment]
For the record, I can confirm that this code seems to work as expected:
```Haskell
(_, _, _, ph) <- createProcess $ proc "stack" ["test"]
threadDelay 5e6      
terminateProcess ph
```

It will start building the test, and then abruptly stop after 5 seconds:
```
...
Registering foo-1.2.3...
foo-1.2.3: benchmarks
Running 1 benchmarks...
Benchmark bar-bench: RUNNING...
foo-1.2.3: unregistering (dependencies changed)
foo-1.2.3: configure (lib + exe + test)
Configuring foo-1.2.3...
foo-1.2.3: build (lib + exe + test)
Preprocessing library foo-1.2.3...
Preprocessing executable 'baz' for foo-1.2.3...
Preprocessing executable 'zap' for foo-1.2.3...
Preprocessing executable 'bazinga' for foo-1.2.3...
Benchmark order-full: FINISH
Completed 2 action(s).
```

I agree. This definitely feels very fragile, and the POSIX API is frustratingly arcane. It works for me for now, though, but I will continue keeping an eye out if this crops up again. :+1:

**Comment by Blaisorblade** [comment]
Great to hear! Was a pleasure collaborating with you :-)

Last note on your snippet: probably there should be a `waitForProcess ph` after `terminateProcess ph`, to avoid zombies hanging around (see `process` docs).

While I hinted at changes to Stack, I'm afraid I don't have anything actionable, so in the end I'm closing this ticket, at least for now.

Bye!
