### ISSUE TITLE
Binary download links giving "Deceptive site ahead" security message on Google Chrome

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#3291]
### Steps to reproduce

For example:

1. Open haskellstack.org from Chrome Browser
2. Click to download Windows installer from https://www.stackage.org/stack/windows-x86_64-installer
3. You'll get security red page

### Expected

Not to happen and to download it directly.

![image](https://user-images.githubusercontent.com/6051718/28566931-5762cd08-7139-11e7-98bf-f10417dd387c.png)

![image](https://user-images.githubusercontent.com/6051718/28566958-7890b558-7139-11e7-9e1c-d9625c45263d.png)

**Comment by borsboom** [comment]
Huh, seems to happen with all the direct bindist links on https://docs.haskellstack.org/en/stable/install_and_upgrade/ as well.  This is rather unfortunate when we're about to release 1.5.0

**Comment by borsboom** [comment]
It also happens when following the download links from Github's releases page.  Furthermore, it also happens when following links from Github's releases page for other (totally unrelated) projects.  For example, try downloading `kops-darwin-amd64` from https://github.com/kubernetes/kops/releases.  So I think this is a general Github releases issue rather than anything Stack-specific.

**Comment by borsboom** [comment]
I'm going to close this since it's not Stack-specific and there's not really anything we can do about it (short of not using Github releases).  We'll have to hope that Github, Google, and Amazon work it out soon...

**Comment by borsboom** [comment]
I just tried again, and it appears to be fixed now.  @varosi can you confirm?

**Comment by varosi** [comment]
Yes, it's fixed, thanks!
