### ISSUE TITLE
Search doesn't work on readthedocs

### ISSUE THREAD

**Issue by alexanderkjeldaas** [commercialhaskell/stack#3298]
Searching in
https://docs.haskellstack.org/en/stable/build_command/

Loads this page, where no search term will work
https://readthedocs.org/search/?q=stack&type=file&project=stack&version=stable

**Comment by borsboom** [comment]
Looks like an upstream bug in readthedocs, which hosts docs.haskellstack.org: https://github.com/rtfd/readthedocs.org/issues/1487, since July 2015 (two years)!  And the suggested workaround seems to be converting the docs to reStructuredText.  Um, no thanks.

readthedocs is convenient in many ways, but it also has a history of important issues like this languishing for ages and having to do weird workarounds.  I think the best course of action might be for us to self-host the docs or use Github Pages.

**Comment by lwm** [comment]
Closing based on comments and detective work by @borsboom.
