### ISSUE TITLE
`stack script --optimize` clutters the current directory with *.hi and *.o files.

### ISSUE THREAD

**Issue by crocket** [commercialhaskell/stack#3371]
### Steps to reproduce

Save the following snippet as `hello.hs`

```haskell
#!/usr/bin/env stack
-- stack script --resolver lts-9.1 --optimize

main :: IO ()
main = putStrLn "hello"
```

Execute `hello.hs`

### Expected

There is no clutter after executing `hello.hs`

### Actual

`hello.o` and `hello.hi` are generated.
`hello` is also generated.

### Stack version

```
$ stack --version
Version 1.5.1 x86_64
```

### Method of installation

* Haskell gentoo overlay

**Comment by kadoban** [comment]
Just as a clarification, the `.o` and `.hi` files are actually created where the script is, not necessarily in the current directory.

So if I have `~/.local/bin/` on my `$PATH` and move `hello.hs` there and in some random other directory, I run `hello.hs`, it doesn't clutter the current directory. Which might be enough of a workaround for this not to bother you?

**Comment by crocket** [comment]
I will have to go to `~/.local/bin` and edit `hello.hs` at some point.

A workaround would be to use a configuration management system such as SaltStack to edit `hello.hs` outside `~/.local/bin` and copy `hello.hs` to `~/.local/bin`.

**Comment by mgsloan** [comment]
Should be feasible to have a special folder for this stuff in the project level `.stack-work` directory.

**Comment by snoyberg** [comment]
@mgsloan I don't see that as possible. What if we have two different `Main.hs` files in two different directories? The project level `.stack-work` will be shared by all scripts using the same resolver.

**Comment by mgsloan** [comment]
@snoyberg Perhaps by hashing the path?  So the output files would go in `~/.stack-work/script-odir/SHORT_HASH/` or something like that.

**Comment by snoyberg** [comment]
That's possible, yes. It would mean that moving the script around would force a recompile, but that's reasonable. The other downside is that those directories will start to accumulate garbage over time.

**Comment by mgsloan** [comment]
True, but I think it is better to accumulate garbage there rather than in the user's directory!

I don't think garbage concerns should be a blocker here, particularly considering it is per script path.  I suppose if you have lots of scripts and you move the whole directory, that could cause a lot of garbage.  To solve this, just hash relative paths when the script is within the project directory, otherwise hash absolute path. 

Stack has no garbage collection for compilation results, so I don't see it lacking it for scripts to be a substantial problem.  Having some garbage collection would be a good idea at some point.

**Comment by kindaro** [comment]
Why hash file path and not contents?

If we hash file contents, the cached `{hash}.hi` & `{hash}.o` will be matched against that hash wherever the file gets moved to. A haskell script is not supposed to be so large as to make hashing the contents expensive.

**Comment by mgsloan** [comment]
> If we hash file contents, the cached {hash}.hi & {hash}.o will be matched against that hash wherever the file gets moved to. A haskell script is not supposed to be so large as to make hashing the contents expensive.

Because hashing just the filepath will substantially reduce the accumulation of garbage .o files.  Now, you get a new set of .o files per script path, vs getting a new set of .o files every time you change the script.

Also, this way you can get incremental re-compilation.  GHC will check the modification times of the inputs and outputs, and avoid recompilation when possible.

**Comment by hellwolf** [comment]
Any modern solution to this problem (stack script litters .o,.hi and binary output everywhere)?

**Comment by mpilgrem** [comment]
Closing, as this has been dealt with subsequently.
