### ISSUE TITLE
.cabal file changes reverted

### ISSUE THREAD

**Issue by Shagii** [commercialhaskell/stack#3380]
Hello,
Today I created a new Yesod application with everything updated and now the .cabal file is reset when i try to run the application.

### Steps to reproduce
OS: Ubuntu 16.04 LTS 64-bit

1. Install latest Stack (1.5.1) (using the official method)
2. Create a new Yesod app
   2.1 stack new myproject yesod-sqlite && cd myproject
   2.2 stack build yesod-bin cabal-install --install-ghc
   2.3 stack build
3. Add a new library to the cabal file && save the file (I used the async package)
4. Import the library in "src/Handler/Home.hs"
5. Run the app using "stack exec -- yesod devel"
6. See the error "Could not find module ..."
7. If you now reload the cabal file you'll see that the changes have been reverted

**Comment by mgsloan** [comment]
@Shagii That project template uses the hpack package description format - https://github.com/sol/hpack .  You can either edit `package.yaml` instead, or delete `package.yaml` so that `myproject.cabal` doesn't get generated from it.

It's understandable that this is confusing, I've opened up https://github.com/commercialhaskell/stack/issues/3383 about making this clearer.
