### ISSUE TITLE
"Implicitly adding" messages are wrong

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#3398]
I don't have details yet on exactly when this happens, but the simple statement is: we have messages coming from Stack now that say "implicit adding package ...." based on command line flags and the like. The heuristics to generate these messages are completely wrong. We can either fix them, _or_ decide that there's no reason to have these messages and delete them. I'm open to input.

**Comment by mgsloan** [comment]
I believe that happens when you pass `--flag pkg:flagname` and `pkg` is a snapshot package.  I think the reason for the message is related to the old behavior described in https://github.com/commercialhaskell/stack/issues/3374 , which is that a package needs to be listed in extra-deps in order to have a flag applied to it.

Now that the restriction removed, this message indeed doesn't make any sense.  I can't think of any decisions the user would make based on it, so my vote is to remove.
