### ISSUE TITLE
Stack should check current version and warn.

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#3412]
Stack update, setup, other things will sometimes fail if you are running an ancient version. I find myself asking people what version they're running and helping them upgrade from time to time. Often this is because they `apt-get`'d it rather than going to haskellstack.org, but not always.

Ideally Stack would warn you when you're running an old version and tell you how to upgrade from the official website. I think there's precedent for this with Homebrew.

**Comment by borsboom** [comment]
Quite a lot of tools do this.  Terraform and minikube are a couple of others I can think of off the top of my head.  The main thing is that such a check shouldn't slow things down and shouldn't be done too often.

**Comment by mgsloan** [comment]
Yep this is a good idea.  Closing as a duplicate of https://github.com/commercialhaskell/stack/issues/1681

Unfortunately, not much that can be done about the old versions of course, as they will always lack the check.  Makes sense to implement it soon, since a few years from now today's version will be the old version.
