### ISSUE TITLE
Stack package shadowing error

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/stack#345]
Here's how to reproduce:

* check out the `stack` repo at the `v0.0.3-beta` tag (`git checkout v0.0.3-beta`)
* `stack build`
* Now add this extra-dep: `- bytestring-0.10.6.0`
* `stack build`

It gets to rebuilding `binary` and fails. Here's why:

```
$ stack install binary --dry-run
Nothing to unregister

Would build:
binary-0.7.1.0: database=snapshot, source=package index

No executables to be installed
...

It should not be choosing the snapshot database to install binary.

```
$ stack exec ghc-pkg list bytestring
/home/dan/.stackage/environment/ghc/ghc-7.8.4/lib/ghc-7.8.4/package.conf.d/
   bytestring-0.10.4.0
/home/dan/.stack/snapshots/x86_64-linux/lts-2.9/7.8.4/pkgdb/
/home/dan/github.com/commercialhaskell/stack/.stack-work/install/x86_64-linux/lts-2.9/7.8.4/pkgdb/
   bytestring-0.10.6.0
$ stack install binary
    Configuring binary-0.7.1.0...
    Setup.lhs: At least the following dependencies are missing:
    bytestring ==0.10.6.0
```

It fails because the modified bytestring is in the local database, and is therefore unavailable for building things in the snapshot database.

**Comment by snoyberg** [comment]
OK, that was a bit tricky, but not too bad. The problem was that I was not tracking dependencies for core packages, and therefore it didn't realize that recompiling bytestring required recompiling binary (though it obviously figured that out later, at the ConstructPlan phase). This should be resolved now on master, can you test it out?

And thanks @drwebb, I started by adding an integration test for this.

**Comment by DanBurton** [comment]
```
stack install binary --dry-run
Nothing to unregister

Would build:
binary-0.7.1.0: database=local, source=package index, after: bytestring-0.10.6.0
bytestring-0.10.6.0: database=local, source=package index

No executables to be installed
```

I also confirmed that `stack build` worked on this scenario.
