### ISSUE TITLE
`stack sdist` fails silently when no stack.yaml is present

### ISSUE THREAD

**Issue by chris-martin** [commercialhaskell/stack#3504]
If you run `stack sdist` in an empty directory, it does nothing and produces no output. It probably should at least print some kind of warning.

It also takes a *suprising* amount of time to do nothing:

```
chris@cubby /t/abc ❯❯❯ time stack sdist
1.01user 0.15system 0:01.14elapsed 102%CPU (0avgtext+0avgdata 170644maxresident)k
0inputs+0outputs (0major+78143minor)pagefaults 0swaps
chris@cubby /t/abc ❯❯❯ stack --version | head -n 1
Version 1.5.1 x86_64
```

**Comment by mgsloan** [comment]
@chris-martin That is because it is using the global project, which has no packages.  Good point, this should be clearer.  I've pushed a fix and it will now output the following:

```
Error: stack sdist expects a list of targets, and otherwise defaults to all of the project's packages. However, the
       configuration at /home/mgsloan/.stack/global-project/stack.yaml contains no packages, so no sdist tarballs will be
       generated.
```

We cut a release today, but it is still an early candidate, so this may more may not make it into the upcoming release.
