### ISSUE TITLE
Can stack delete unused folders in `.stack-work/downloaded`?

### ISSUE THREAD

**Issue by mitchellwrosen** [commercialhaskell/stack#3567]
Is it possible for stack to compare the current `stack.yaml`'s packages to the contents of `.stack-work/downloaded` and remove the unused folders? These tend to accumulate when working on a project with fast-moving GitHub-hosted dependencies. Thanks.

**Comment by mgsloan** [comment]
Indeed, it'd be good to garbage collect those.  One tricky thing here is that users may have multiple stack.yaml files that refer to different git repos.  I suppose one approach could be to read all `*.yaml` in the dir, and GC based on those.

Could potentially have an explicit command to clean up such things - https://github.com/commercialhaskell/stack/issues/133 - note that `stack clean --full` is one approach, but that's a rather big hammer since it throws away everything.

**Comment by snoyberg** [comment]
With Pantry, we're no longer writing this directories at all, closing
