### ISSUE TITLE
Documentation on adding dependencies doesn't mention hpack/package.yaml

### ISSUE THREAD

**Issue by kadoban** [commercialhaskell/stack#3633]
https://docs.haskellstack.org/en/stable/GUIDE/#adding-dependencies mentions how to add dependencies, but it only talks about the `.cabal` file.

Since the default template has been updated to use hpack, it really should at least mention `package.yaml`. With people on older versions of `stack` (v1.5.1 for example) this is especially confusing because it just silently overwrites the .cabal file they just changed.

In v1.6.1 it's not so bad really, but it'd still be nice if they didn't have to get that warning from modifying the `.cabal` file when they really should be editing the `package.yaml` file.

**Comment by kadoban** [comment]
> > In v1.6.1 it's not so bad really, but it'd still be nice if they didn't have to get that warning from modifying the .cabal file when they really should be editing the package.yaml file.
>
> Hmm, what would be better?  The intent of that warning is to recommend editing the package.yaml

Ah, sorry I should have worded that better. I think the hpack-ish behavior is quite nice in 1.6.1. I was just reiterating that even so, it'd be better if the docs said to modify package.yaml originally, so they don't have to:

1) Follow the docs, modify the .cabal
2) Get yelled at by a warning.
3) Then do the actual thing they should have (edit package.yaml).

The first two steps are a bit of a run-around when you're a user, you'd really rather just be told the actual thing you should have done in the first place.

**Comment by mgsloan** [comment]
Oh true, yes, I definitely agree with fixing the docs for this!

**Comment by dukedave** [comment]
Hi, I was about to open a new issue, but I'll just add here since this is still open:

FYI the section on [Listing Dependencies](https://github.com/commercialhaskell/stack/blob/98c51cafb038bf09b58d5607956fb199d3660735/doc/GUIDE.md#listing-dependencies) still needs updating to reference `package.yaml` instead of the `.cabal`, i.e: https://github.com/commercialhaskell/stack/commit/6a091f8dfc7e2d821a2c065517833ecbc5fd0285#diff-4f532e9d254305a02dab50da05285712R318

At the moment it's a bit confusing because it suddenly jumps from one style to the other when reading it straight through.

**Comment by mgsloan** [comment]
@dukedave Feel free to open a PR, that'd be appreciated even if you're new to it!  Someone that knows what they're talking about can review :D  I have opened https://github.com/commercialhaskell/stack/issues/3755 to track this.
