### ISSUE TITLE
stack init --solver pulls down mingw

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3643]
If I do `stack init --solver` on a fresh machine in a directory with a cabal file it downloads Mingw, while a normal `stack init` doesn't. I think that's a bug. Stack 1.6 32bit on Windows.

**Comment by snoyberg** [comment]
Do you mean the `msys2` distribution?

This doesn't seem unreasonable to me, `--solver` needs to run `cabal-install`, which requires GHC be available for checking the global database. In fact, it's only through some clever tricks (using global package hints) that `stack init` itself is able to bypass the need to install GHC. We only do that so that, in the common case, Stack doesn't need to install multiple different versions of GHC to test the latest nightly and LTS.

**Comment by ndmitchell** [comment]
I do mean `msys2`. Fair enough, that sounds reasonable. It was mostly problematic because #1212 means that installing GHC/msys2 is incredibly verbose, which was choking my CI engine, as the verbosity was coming from a new place, interspersed with essential messages I couldn't miss.
