### ISSUE TITLE
LTS-10.0 failure on ARM

### ISSUE THREAD

**Issue by dustin** [commercialhaskell/stack#3680]
### General summary/comments (optional)

Upgraded to latest LTS and tried building some of my stuff.  Failed on ARM.

### Steps to reproduce

I have a docker image running that works if you have qemu set up.

1. docker run --rm -i -t -v $HOME/stuff/dockarm:/root dustin/armstack
2. cd /tmp && stack new project
3. cd project
4. stack build

### Expected

Success!

### Actual

```
root@56caefb67252:/tmp/project# stack build                                                                                                                                                                          
No information found for ghc-8.2.2.                                                                                                                                                                                
Supported versions for OS key 'linux-armv7': GhcVersion 7.10.2, GhcVersion 7.10.3, GhcVersion 8.0.1, GhcVersion 8.0.2, GhcVersion 8.2.1
```

### Method of installation

stack upgrade

**Comment by borsboom** [comment]
I don't think the ARM bindists were available yet when GHC 8.2.2 was announced so we never added the metadata.  I've now added them in https://github.com/fpco/stackage-content/commit/d5b0d1b1084565fd8e378e646e0aadafa36ba18a so `stack setup` should now be able to find it.  Note that you may have to esure your system has the correct version of LLVM installed.

**Comment by dustin** [comment]
Also, this seems to be missing:  https://www.stackage.org/stack/linux-arm

**Comment by borsboom** [comment]
@dustin ARM isn't an "officially" targeted platform for Stack, but we do make an effort.  It takes about a week of 100% usage of one my cores on my laptop to build a Stack binary for ARM, and I don't like to delay the new releases while waiting (especially since I can't _always_ have my laptop plugged into the mains so have to stop and start the build a fairly often).  I would still _love_ to hear from a volunteer who can take on building these binaries instead -- it's definitely my least favourite part of the release process.

**Comment by dustin** [comment]
Oh.  How can I help?  I have some compute resources.
