### ISSUE TITLE
Cannot build using cabal-install

### ISSUE THREAD

**Issue by lspitzner** [commercialhaskell/stack#3693]
stack-1.6 does not compile cleanly using cabal-install and the same ghc associated with the resolver used in the current stack.yaml (ghc-8.0.2) out of the box. This is due to missing version bounds on several packages. This is using new-build, so hopefully the same as in a fresh sandbox.

I think any users that require or want to bootstrap stack would appreciate if this was fixed upstream.

For completeness, the first error encountered roughly looks like

~~~~
[1 of 1] Compiling Main

/stack/dist-newstyle/build/x86_64-linux/ghc-8.0.2/stack-1.6.1/setup/setup.hs:15:1: error:
    Failed to load interface for ‘Distribution.Types.PackageName’
    Use -v to see a list of the files searched for.

/stack/dist-newstyle/build/x86_64-linux/ghc-8.0.2/stack-1.6.1/setup/setup.hs:16:1: error:
    Failed to load interface for ‘Distribution.Types.UnqualComponentName’
    Use -v to see a list of the files searched for.

/stack/dist-newstyle/build/x86_64-linux/ghc-8.0.2/stack-1.6.1/setup/setup.hs:18:31: error:
    Module ‘Distribution.Version’ does not export ‘showVersion’
~~~~

I will also add that `stack` seems to have been broken in this respect for more than a year. I find this rather disappointing.

**Comment by lwm** [comment]
We seem to have stopped checking this since https://github.com/commercialhaskell/stack/blob/master/.travis.yml#L22 due to time outs on Travis side - which is a big problem here. We need to get this back on the go. Thanks for the report!

**Comment by borsboom** [comment]
The source repository does not have any bounds on dependencies in its `package.yaml`, since `stack.yaml`'s resolver and extra-deps specify the exact package versions.  If you're building from the source repo, use `stack` to do so.  If you need to bootstrap `stack` using cabal-install, you can download the latest sdist (which includes a `.cabal` file with bounds) from Hackage or https://github.com/commercialhaskell/stack/releases.

**Comment by lspitzner** [comment]
@borsboom good point! I was using the tagged `v1.6.1.1` commit from the repo instead of the corresponding hackage sdist. Is there a way to obtain/generate these bounds automatically (some magic hpack flags..) ?

Now I run into

~~~~
src/Stack/Options/Completion.hs:47:17: error:
    • Exception when trying to run compile-time code:
        ghc: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
      Code: (>>=)
              runIO (readProcess "ghc" ["--show-options"] "") (.) lift lines
    • In the untyped splice:
        $(runIO (readProcess "ghc" ["--show-options"] "") >>= lift . lines)
~~~~

presumably because I have no `ghc` in global default `PATH`. But I _did_ modify `PATH` in the terminal session used to initiate the build. Not sure if this a `cabal new-build`, a `stack` or a `template-haskell` bug.

**Comment by hvr** [comment]
Fwiw, code which assumes that the compiler executable is reachable via `$PATH` and is called `ghc` is operating under unjustified assumptions. Cabal won't guarantee that.

**Comment by borsboom** [comment]
@ lspitzner: `stack sdist --pvp-bounds=both` will do this, although there is a known issue in stack-1.6.1 that causes it to generate a .cabal file that's missing some fields (see #3549).

**Comment by borsboom** [comment]
I'm not sure why you're running into that `ghc` issue.  I make sure `stack` is buildable using cabal-install (although I use `cabal sandbox init` and `cabal install` rather than `cabal new-build`) as part of the pre-release checks, and I also do so by adding ghc to the PATH in the terminal where I run the build.

**Comment by mgsloan** [comment]
I have opened https://github.com/commercialhaskell/stack/issues/3699 .  Thanks for pointing out the faulty assumption here, @hvr !

**Comment by lspitzner** [comment]
@borsboom you are right. my observation seems to be reproducible only by

- start the compilation without `ghc` on `PATH`, by using `--with-compiler` passed to `cabal` in the usual fashion. this fails "ghc: ... does not exist".
- modify `PATH` so (the same) `ghc` is on it.
- restart the build. this still fails, even though `ghc` is now on `PATH`.

Presumably something caches `PATH` (at "setup" time?).

But

1) set `PATH`
2) clean
3) build

works and finishes cleanly. Thanks for all the replies!

(Not sure if this last observation warrants any action (or if #3699 already is that action); otherwise this issue seems resolved.)

**Comment by mgsloan** [comment]
> Presumably something caches PATH (at "setup" time?).

Correct, Cabal caches the `PATH` used by `configure`, but current stack does not reconfigure if PATH changes https://github.com/commercialhaskell/stack/issues/3138 .  It would be great to fix this, PRs appreciated!

Sounds like the issue has been resolved, so closing as a support ticket.  Work spun off from this issue is tracked by #3699 and #3138
