### ISSUE TITLE
Unable to build a project with stack ..

### ISSUE THREAD

**Issue by barnabyrobson** [commercialhaskell/stack#370]
Not sure if this is the right place to post this but I'm trying to build something with stack
and hitting a wall. The thing I'm trying to build can be built with cabal build.

After installing stack, running stack update, stack init then stack setup which all seem to go
fine then I run stack build which builds all the dependencies great .. then it tries to build
the local library I want and ...

$ stack build
....
MoodlerLib-0.1.0.0: configure
sh: configure: No such file or directory

--  While building package MoodlerLib-0.1.0.0 using:
      /Users/test/.stack/programs/x86_64-osx/ghc-7.8.4/bin/runhaskell -package=Cabal-1.18.1.5 -clear-package-db -global-package-db -package-db=/Users/test/.stack/snapshots/x86_64-osx/lts-2.14/7.8.4/pkgdb/ /private/var/tmp/haskell/Moodler/MoodlerLib/Setup.lhs --builddir=.stack-work/dist/x86_64-osx/Cabal-1.18.1.5/ configure --user --package-db=clear --package-db=global --package-db=/Users/test/.stack/snapshots/x86_64-osx/lts-2.14/7.8.4/pkgdb/ --package-db=/private/var/tmp/haskell/Moodler/MoodlerLib/.stack-work/install/x86_64-osx/lts-2.14/7.8.4/pkgdb/ --constraint=base==4.7.0.2 --constraint=bmp==1.2.5.2 --constraint=containers==0.5.5.1 --constraint=either==4.3.4.1 --constraint=filepath==1.3.0.2 --constraint=free==4.11 --constraint=lens==4.7.0.1 --constraint=mtl==2.1.3.1 --constraint=unix==2.7.0.1 --libdir=/private/var/tmp/haskell/Moodler/MoodlerLib/.stack-work/install/x86_64-osx/lts-2.14/7.8.4/lib --bindir=/private/var/tmp/haskell/Moodler/MoodlerLib/.stack-work/install/x86_64-osx/lts-2.14/7.8.4/bin --datadir=/private/var/tmp/haskell/Moodler/MoodlerLib/.stack-work/install/x86_64-osx/lts-2.14/7.8.4/share --docdir=/private/var/tmp/haskell/Moodler/MoodlerLib/.stack-work/install/x86_64-osx/lts-2.14/7.8.4/doc
    Process exited with code: ExitFailure 127

And sure, there's no configure file in this directory ... It's a copy of this repo:
https://github.com/dpiponi/Moodler/tree/master/MoodlerLib

I'm not sure if I'm supposed to supply a configure file, or it should make
one for me.

**Comment by snoyberg** [comment]
On my phone so a short answer. The Setup.us file has the wrong contents for a simple build.

**Comment by chreekat** [comment]
I poked at this a little. First I ended up using `stack init --resolver` to create the stack.yaml, and had to install a couple system libraries. Then I was able to build MoodlerLib with this change:

    diff --git a/MoodlerLib/Setup.lhs b/MoodlerLib/Setup.lhs
    index a6e7e3f..5ca9a8f 100755
    --- a/MoodlerLib/Setup.lhs
    +++ b/MoodlerLib/Setup.lhs
    @@ -1,3 +1,3 @@
     > module Main where
    -> import Distribution.Make (defaultMain)
    +> import Distribution.Simple (defaultMain)
     > main = defaultMain

I wasn't able to build the Moodler project, though. Distribution.Make expects a 'configure' script to exist. I created a nullary one (just runs true), and then stack bails with:

    Moodler-0.1.0.0: configure
    /home/b/tmp/Moodler/Moodler/.stack-work/dist/x86_64-linux/Cabal-1.18.1.5/stack-config-cache: openBinaryFile: does not exist (No such file or directory)

At this point, I'm not sure if that's because `configure` should be smarter, or because `stack` should be smarter.

https://github.com/chreekat/Moodler/tree/with-stack

**Comment by snoyberg** [comment]
OK, now that I'm awake and on my computer again: this is a bug in the Moodler codebase, but one that we can work around. The problem is with the way the Cabal build system works. In a .cabal file, you can specify multiple build types: Simple, Custom, etc. Simple is supposed to correlate to a Setup.hs file that looks like this:

```haskell
import Distribution.Simple
main = defaultMain
```

However, Moodler has a Setup.hs of:

```lhaskell
> module Main where
> import Distribution.Make (defaultMain)
> main = defaultMain
```

I'd definitely recommend fixing the Setup.hs in Moodler, as stack is not the only tool that runs Setup.hs files directly.

The additional fix we can make is to say: if the build type is Simple, ignore the Setup.hs file and just use our own. I think I'll implement that since it's easy and corresponds to the behavior that cabal-install seems to have (I say "seems to" since the configuration method in cabal varies depending on whether you run in parallel or non-parallel mode).

**Comment by snoyberg** [comment]
Alright, this workaround is now on master, if you rebuild stack from there it should be able to build Moodler unmodified.

**Comment by barnabyrobson** [comment]
Thanks for looking at this, yes a simple fix to the Setup files is all that was required ! Thanks for going the extra mile and providing a work around for other people who have bad Setup files.

**Comment by barnabyrobson** [comment]
hi @chreekat .. can you tell me a bit more detail about how you built the master stack.yaml file ? Using your yaml file and the Setup.lhs fix everything builds (in your test you just forgot to also fix Setup.lhs in the Moodler folder)
Firstly you may have forgotten a word but I assume you meant `stack init --resolver ghc7.8` as that matches the yaml file ?  Out of interest why did you pick that resolver ? If I do that and then but then attempt to run `stack build` and follow the "recommended actions" I don't get any closer to being able to build.  I'm interested in your process; how did you get the right list of packages and their versions .... I'm also interested why this project gives the resolver such a tough time ... thanks !

**Comment by snoyberg** [comment]
@barnabyrobson Running `stack init -v` gives a lot more information about why a build plan was rejected (arguably that information should be displayed by default actually). With the new `stack solver` command, getting something working seems a lot easier:

    stack init --resolver lts-2.15 && stack solver --modify-stack-yaml

The reason this project gives trouble is that it depends on 4 packages that aren't in Stackage:

- PortMidi-0.1.4
- gloss-1.0.0.0
- gloss-juicy-0.1.2
- hosc-0.14.1

My recommendation: add them to Stackage so that this isn't a problem in the future.

**Comment by chreekat** [comment]
@barnabyrobson Sorry, but I don't remember how I got there. Guess and check, mostly.
