### ISSUE TITLE
Hlint rules to prevent regressions

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3700]
To prevent regression of #3628 it would be nice to specify that the user shouldn't use some functions directly from HttpClient.  Here's where this is suggested: https://github.com/commercialhaskell/stack/pull/3682#issuecomment-353453913

Would be good to consider this for other aspects of the code too.  In particular:

1. Encourage efficient file IO that is correct with regards to locale.
2. Encouraging the use of process utilities.  This will be particularly important once there is generic support for `--with-PROG` flags

**Comment by igrep** [comment]
FYI.
I've added these lines to try hlint can distinguish functions with the same de-qualified name, but it didn't complain the `Network.HTTP.StackClient` module.

```yaml
- error: {lhs: "Network.HTTP.Simple.httpJSON", rhs: "Network.HTTP.StackClient.httpJSON"}
- error: {lhs: "Network.HTTP.Simple.httpLbs", rhs: "Network.HTTP.StackClient.httpLbs"}
...
```

I guessed hlint should cause an error because `Network.HTTP.StackClient` is not configured to be ignored.

So currently hlint can't distinguish functions with the same de-qualified name.

**Comment by igrep** [comment]
Oops, sorry.
My hlint was too old: v1.9.35.
It actually detected it!

**Comment by mgsloan** [comment]
Great!  Keeping this open to track applying this to other areas of the code.

**Comment by mpilgrem** [comment]
I am going to close this issue, given the passage of time and no further activity.
