### ISSUE TITLE
Invalid downloaded files don't redownload

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#372]
I had some problem on my system that corrupted a tarball during download. The next time I ran `stack build`, it complained about a hash mismatch. When I manually deleted that tarball, everything worked. I would have expected the download code to delete the old file for me and then retry.

**Comment by DanBurton** [comment]
This (passing) test case covers part of what is described here:

```haskell
    it "does redownload when the destination file is wrong" $ \T{..} -> withTempDir $ \dir -> do
      examplePath <- getExamplePath dir
      let exampleFilePath = toFilePath examplePath
      writeFile exampleFilePath exampleWrongContent
      doesFileExist exampleFilePath `shouldReturn` True
      let go = runWith manager $ verifiedDownload exampleReq examplePath exampleProgressHook
      go `shouldReturn` True
      doesFileExist exampleFilePath `shouldReturn` True
```

Particularly, `go shouldReturn True` should indicate that the file *was* redownloaded. I'll see if I can craft a failing test case.

**Comment by DanBurton** [comment]
I'm not able to reproduce. I expect the following behavior:

1. If a download is corrupted, an error message is displayed and the program exits.
2. If the same file is required via `download` or `verifiedDownload` in a later invocation, a redownload is triggered due to detecting the present file as corrupted. (There should be no need to manually delete.)

Arguably 1. could be enhanced by automatically retrying a couple times, but if I understand correctly, that's not what this issue is about.

@snoyberg Can you give me some more information about the corrupted tarball? E.g. was this specified via `extra-deps`, or via `packages`?

**Comment by snoyberg** [comment]
I can't reproduce this right now. Closing until I find a repro.
