### ISSUE TITLE
Duplicating dependencies in stack.yaml and package.yaml

### ISSUE THREAD

**Issue by corpix** [commercialhaskell/stack#3766]
Hello. I have added a new dependency(`strings`) into `package.yaml` file and when run `stack build` I got this:

```
$ stack build                                                        ✖ 1 (2s 979ms)
Error: While constructing the build plan, the following exceptions were encountered:
In the dependencies for mammoth-0.0.0:
    strings must match -any, but the stack configuration has no specified version (latest matching version is 1.1)
needed since mammoth is a build target.
Some potential ways to resolve this:
  * Recommended action: try adding the following to your extra-deps in /home/user/projects/<redacted>/stack.yaml:
- strings-1.1
  * Set 'allow-newer: true' to ignore all version constraints and build anyway.
  * You may also want to try using the 'stack solver' command.
Plan construction failed.
```

> I am a haskell beginner. I understand, many haskell programmers are PhDs... but let's just keep things simple for mere mortals :)

1. This error is very confusing, the part `strings must match -any` makes me continuously screaming "wat? wat? wat?" because I don't understand what is this `-any` thing stands for
2. I don't thing this is a good idea to duplicate dependencies across configuration files(stack.yaml, package.yaml) but stack suggests me to `try adding the following to your extra-deps in .../stack.yaml`, I already have package.yaml, I don't want to "copy-paste"
3. Second recommendation is strange `Set 'allow-newer: true' to ignore all version constraints and build anyway`... we have `no specified version` but we could `ignore all version constrains`... wat?

**Comment by kadoban** [comment]
Yeah, the `allow-newer` advice does not apply in this situation, so that is a tad not ideal. That could maybe be improved.

The rest is working as designed mostly. The error message is a bit hard to read at first, but you get used to it. It's a bit hard to be both concise there and also have the message make sense to stack beginners. It could likely me improved, but I have yet to think of a better wording for it.

As for why you need to duplicate the dependency in the packages.yaml and the stack.yaml file, that has to do with their different responsibilities.

The package.yaml file just declares what dependencies you have in terms of package names and their version ranges (or you are allowed to leave out the version ranges).

The stack.yaml file tells stack *where* to get those dependencies from. Often you won't have to explicitly mention a bunch of dependencies in stack.yaml, because they are implicit in the `resolver` setting. For example, this page lists every package that's in the lts-10.3 resolver: https://www.stackage.org/lts-10.3  Any package that's in there, you won't have to mention in stack.yaml. When you start using packages that *aren't* in a resolver though, stack wants to know where to get them from and what exact version to use. This is for reproduceable builds. So you'll be able to build your project just as successfully a few years from now as you can today.

Also, there's a bit of "historical reasons" going on here, or at least an effort to make things work with other build systems like cabal-install. cabal-install does not care at all about your stack.yaml file, it only cares about the .cabal file that is generated from the package.yaml file. So that's a bit more why it's split up into separate files instead of being one slightly-more-cohesive thing.

**Comment by mgsloan** [comment]
@corpix We actually recently wrote a doc about this, it hasn't been merged quite yet, but here's the current version: https://github.com/commercialhaskell/stack/blob/stack-vs-cabal-config/doc/stack_vs_cabal_config.md

> This error is very confusing, the part strings must match -any makes me continuously screaming "wat? wat? wat?" because I don't understand what is this -any thing stands for

You're right!  `-any` is something that comes from the Cabal library, and I agree that it is a really weird and surprising way of writing down "any package version".  

> Second recommendation is strange Set 'allow-newer: true' to ignore all version constraints and build anyway... we have no specified version but we could ignore all version constrains... wat?

Great point.  That suggestion should only be made when there are only dependency errors.

I have taken these into account and opened https://github.com/commercialhaskell/stack/pull/3780 .  With that PR as it currently is, the output is

![2018-01-15_1449x440_scrot](https://user-images.githubusercontent.com/22570/34936258-907b0030-f995-11e7-8879-1231c961eb38.png)

**Comment by corpix** [comment]
Ah, this is awesome!
@kadoban thank you for clean explanation, now I understand a bit more :)
@mgsloan thank you for the error message fix! I think it could be closed :tada:
