### ISSUE TITLE
stack repl exits on ctrl+c with error <stdin>: hGetChar: hardware fault (Input/output error)

### ISSUE THREAD

**Issue by kindaro** [commercialhaskell/stack#3821]
### General summary/comments (optional)

`stack repl` terminates when I repeatedly press `ctrl+c`. Two times is enough. Termination is observed on each of 5 consecutive runs. If there is other activity between the `ctrl+c` presses, still terminates on the second `ctrl+c`.

In the same situation, `stack exec ghci` does not terminate.

There is an error log in [the gist](https://gist.github.com/kindaro/aa18ee8dfbb9be792cca3e4304e8e13c).

[This issue elsewhere](https://github.com/haskell/cabal/issues/1448) may be related, as the error is the same.

### Steps to reproduce
```
% stack repl
λ {- repeatedly press ctrl+c -}
% <stdin>: hGetChar: hardware fault (Input/output error)
%
``` 
### Expected

A new clear prompt is offered, the same as with `stack exec ghci`.

### Actual

`stack repl` terminates, an error is printed to `stderr`.

### Stack version

```
% stack --version
Version 1.7.0, Git revision 2631803b9c502fa5225eac3536acda9d1d314aa7 (5619 commits) x86_64 hpack-0.20.0
```

### Method of installation

ArchLinux AUR [haskell-stack-git](https://aur.archlinux.org/packages/haskell-stack-git)

**Comment by tswelsh** [comment]
I also see this on `Version 1.7.0, Git revision 0d848deac8e541aa40c5ab5bc784bb9d3ec2928a x86_64 hpack-0.20.0`.  I'm debugging a very slow test and need to kill the running test with Ctrl+c very often, but with this bug I have to restart things constantly, making it not really feasible to use.

**Comment by mgsloan** [comment]
Good catch!  I've noticed this too, but didn't realize that `stack exec ghci` had better behavior.  It'd been a long time since I used plain old `ghci` so forgot that it worked better for spamming Ctrl-C.  I've implemented some changes that fix this, in https://github.com/commercialhaskell/stack/pull/3869

To make it happen, it needed to leave around the generated files.  This has the nice consequence that if you do `stack ghci -v`, and then exit the process, you can copy paste the ghci invocation out.  It has the downside of potentially creating garbage, but it's stored in `/tmp` and is based on hashes.  So, it only writes out new files if the contents have changed.  So, running `stack ghci` multiple times in a row shouldn't create any new files.

**Comment by snoyberg** [comment]
PR #3869 has been merged into master, so this should now be resolved.
