### ISSUE TITLE
stack upgrade --git fails on Windows, with a segmentation fault

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#3843]
As discussed in #3797, `stack upgrade --git` fails on Windows (Window 10, version 1709) with an error about a segmentation fault: 
```
[ 78 of 129] Compiling Stack.Build.Cache ( src\Stack\Build\Cache.hs, .stack-work\dist\ca59d0ab\build\Stack\Build\Cache.o )
Segmentation fault/access violation in generated code
Completed 38 action(s).
```
This appears to be due to a bug in GHC 8.0.2 [#13112](https://ghc.haskell.org/trac/ghc/ticket/13112) which may not occur in GHC 8.2.2 (`stack` can be built using GHC 8.2.2 - currently, `Version 1.7.0, Git revision 07bdb09b76a73b207fecb8a5ee53854dd33bc57f (5651 commits) x86_64 hpack-0.20.0`).

`stack` can also be built in GHC 8.0.2 using `stack build --ghc-options -fexternal-interpreter`.

**Comment by mgsloan** [comment]
So, what should be done here?  If I'm reading correctly, bumping the resolver version in stack.yaml will fix it?  Feel free to open a PR for it.

**Comment by mpilgrem** [comment]
As you have suggested, I have opened a pull request.

**Comment by borsboom** [comment]
It's a bit late to comment, but this may turn out to be problematic for the release process since LTS-10 is based on GHC 8.2.2, and Alpine Linux appears to still be on GHC 8.0.2 and that's what we use to build static binaries (there may be third-party APK repositories that have GHC 8.2.2, but it's unclear how well they work).

**Comment by mgsloan** [comment]
@borsboom Hmm, perhaps the alpine release should use an alternative stack.yaml?  Perhaps a bit confusing to deviate on the dependency versions of the same release, though. Hmm!

**Comment by borsboom** [comment]
Yes, especially since the static binary built on Alpine is the standard for all Linux distros (it's what get.haskellstack.org and `stack upgrade` use).

**Comment by mgsloan** [comment]
Seems worthwhile to try building the alpine binaries with 8.2.2, and if
that proves problematic, then it likely makes sense to revert this change.

**Comment by borsboom** [comment]
I've had confirmation that there is not currently a way to use GHC 8.2.2 on Alpine Linux.  Another option is to switch back to dynamically linked binaries, since GHC on Alpine just doesn't seem to be very stable.  There are a few other issues with the static binary (such as issues with DNS lookups on some distros) so there is a case to be made for it.
