### ISSUE TITLE
integer-simple bindists

### ISSUE THREAD

**Issue by leohaskell** [commercialhaskell/stack#3939]
Hello, as GHC-8.4.1 has been released already, let me provide again an [integer-simple bindist for windows](https://drive.google.com/open?id=1P4gy5s3b-IrRysefeI1yuO7eiu94wKw7).

I have a question, though: isn't it possible to integrate building an integer-simple version just like you're building other versions of GHC? I think it's better to be that way, than to rely on 3rd parties

**Comment by leohaskell** [comment]
Are there any issues with the bindist?

**Comment by pjljvandelaar** [comment]
@leohaskell Will you also add GHC 8.6.3? or will it become part of stack and/or LTS support?

**Comment by leohaskell** [comment]
Since noone responded here for almost an year, I started to use local integer-simple bindists, instead of counting on stack. If you're interested, I can share with you instructions for building such bindists yourself (I haven't build for ghc 8.6.3 yet, since this version of ghc doesn't work on windows, by the way)

**Comment by pjljvandelaar** [comment]
I am surprised no one is asking, since on windows you have license issues with all software you make.
Without integer-simple, all your software will be LGPL software!

**Comment by borsboom** [comment]
@leohaskell Sorry for failing to respond to this at the time, it slipped through the cracks.  Not sure if there's much point adding a GHC 8.4.1 bindist now, since GHC the 8.4 branch is up to 8.4.4, and 8.6 is out, though.

> I have a question, though: isn't it possible to integrate building an integer-simple version just like you're building other versions of GHC? I think it's better to be that way, than to rely on 3rd parties

At this point the Stack team isn't building _any_ bindists.  When new GHC versions are released, we just point to the official bindists provided by the GHC release team (the only thing we do is re-compress the macOS bindists as `bz2` since macOS doesn't have `xz` by default).  We are still happy to accept user-provided bindists as well (for example, we've recently added user-contributed bindists for armv7 and FreeBSD).

It'd be great if the GHC release team could start making integersimple bindists -- not just for Stack users but for everybody.  With their new CI infrastructure, I imagine adding new bindists is easier than it used to be, so might be worth getting in touch with them.

Again, apologies for missing this.  We really appreciate that you've been providing the integersimple bindists.  I, too, am surprised nobody else asked about it until now.

**Comment by pjljvandelaar** [comment]
I don't know why this issue is closed since integer-simple bindists are still not available.
Do we really to use haskell on windows with a BSD3 license have to either 
* make a docker with ubuntu running our haskell code? or
* build the ghc compiler ourselves with the right integer simple flag?

@snoyberg Could you explain? 

@leohaskell Could you please share the instructions for building such bindists yourself? And how did you share the bindist with stack?

**Comment by snoyberg** [comment]
The Stack team does not produce GHC bindists, and we don't intend to begin doing so. If others would like to generate these bindists, I believe we can add them to the stack-setup.yaml file.

**Comment by borsboom** [comment]
> do we really have to either […]

Windows Subsystem for Linux is another option (I know these options are all unsatisfactory, and it would definitely be nice if there were official integer-simple GHC bindists).

**Comment by leohaskell** [comment]
@pjljvandelaar, [here they are](https://gist.github.com/leohaskell/8a815fbdd4f29d86bbe91b476692bd49).
It is possible to use a custom GHC by setting it inside your `stack.yaml`. For example:
```yaml
ghc-variant: integersimple

setup-info:
  ghc: windows64-integersimple:
    8.4.4:
      url: ...
      sha1: ...
```
