### ISSUE TITLE
Provide a simple way to produce opencontainers.org image(s) for executables

### ISSUE THREAD

**Issue by dysinger** [commercialhaskell/stack#401]
Instead of having Dockerfiles all over our Haskell projects, let's find a simple way to package a stack project's executable(s) as container(s).  

The simplest case would be that the user provides a base container (specified in stack.yml).  Stack would then take the base image & layer on top an ENTRYPOINT set to run one executable.  There may be more than one executable in a Haskell project.  There can be only one ENTRYPOINT in a docker container. We may or may not need to produce multiple images from a Haskell project. You would receive 1 container image for each Haskell executable by default. 

If the user wanted to have a VOLUME, EXPOSE ports or add ONBUILD, they would need to include that in the base image.  The base image could generic or be specific to 1 Haskell project. It depends on the user's needs.

We could handle more cases later, but this simple approach of requiring a base container would work for a lot of projects immediately.

**Comment by manny-fp** [comment]
Feel free to assign to me, as this interests me.  I think providing the option to set Dockerfile metadata as well (rather than requiring the base image to have it) would be a big benefit, and wouldn't be difficult to implement (I do something like this in the stack image build tool already).

**Comment by ketzacoatl** [comment]
OMG +1.

**Comment by manny-fp** [comment]
More thoughts: the stack.yaml could specify multiple images to be generated, each with its own base image, ENTRYPOINT and extra metadata.

**Comment by mgsloan** [comment]
+1 this would be quite awesome

**Comment by manny-fp** [comment]
I think this'd be easier to reason about if we know a bit more about what you and @ketzacoatl want to see the Docker image look like, since you have been doing a lot more deploying of images on servers than I have.  Some more unfocused thoughts from me on this include:

- By default, create images based FROM the `fpco/stack-run:lts-x.y` image corresponding to the resolver (and stack-build/stack-full image) in the stack.yaml, since that guarantees any runtime libraries required to run the executable will be available.  However, it's a fairly large base to be starting from, so if small images are your goal this will not be the way. 

- Since the stack-run image is based FROM phusion/baseimage, you might want to use phusion's my_init rather than directly setting the ENTRYPOINT to the executable.  With stack-run, if you set CMD to the executable it'll run under my_init automatically (since the default ENTRYPOINT uses it).

- You may need to augment the stack-run image with some additional data files from the repo, so there should be an easy to to COPY or ADD them.  One way could be that each target can specify a Dockerfile that's used to augment the base image.

- Similarly, you may need to add some OS packages to the image, and having the target point to a Dockerfile would work for that too.

**Comment by ketzacoatl** [comment]
your points here @manny-fp are well noted, and I would say this all basically breaks down into two simple use cases:
1) you have an executable and you want to run it, it has no additional files or system packages, it just needs a runtime container..
2) you have an executable to run, but it needs files / packages / additional stuff. We would be rehashing a lot of what Dockerfile already does, so it might be worth just specifying a dockerfile.. but on the other hand.. it might be simpler to allow our config to take a list of system packages to install with apt and a list of files/dir to COPY to the same place where our executable runs from?

In both cases, I would like to have the smallest/simplest runtime image possible (whatever that means), but having control over the source image should give us all the flexibility needed there.

Let's meet up if the above is not clear enough.. talking in person will likely be the best next step if that is needed.

**Comment by dysinger** [comment]
I would like to do the simplest thing here and have _small_ images that deploy @ 100-200mb. Most applications can fit in an image this size.

The simplest case that @snoyberg & I talked about is:
1) Docker packaging is not the default. If they want it, they use it.
2) User specifies *their* base image(s) for *their* executable(s) in stack.yml
3) User optionally specifies a map of static content from the project to copy into the image [("/source", "/dest")] to accommodate web apps. This is the single Dockerfile-like exception to the rule of not trying to take over for Dockerfile (or Packer).

I would argue that we don't want to concern ourselves with a default image, debian packaging or any specialized knowledge of phusion runtime in stack.  This would create confusion for users IMHO. ("I already have my base image. Why is there an option to add more debian packages at image build-time in stack.yml? My host & image are based on ArchLinux anyway.") 

Adding all these options in stacky.yml gets complicated quickly too. There will be a ticket the very next day to support RPMs ... and then custom repos .... and then .... extended to the end of the yarn ball.

Let the user's dockerfile (or Packer json) for the project be the single place to set up their runtime env.  It's the user's responsibility.  The division of concerns is clearer this way IMHO.

If you wanted to use phusion images here you could prepare them for your project. We could provide an example that shows how to do this.  (We could also show a simpler example with a plain ol' 25mb scratch docker image.) We could make an option so that ENTRYPOINT would not be set if you don't want it set (say you have my_init already setup on your phusion lts-2.15 project image).  This way we are easily accommodating special phusion-like images without making any default set in stack code.
