### ISSUE TITLE
Automatic support for `--nix`.

### ISSUE THREAD

**Issue by aloiscochard** [commercialhaskell/stack#4080]
Hi all,

Stack have integration for Nix/NixOS usinge the `--nix` which is working well and that is good.

OTOH, when running on my NixOS every-time I run a stack command I have to remember to add `--nix`, which is slightly problematic. Worst: every tool that rely on stack (for example `codex`) and use it to resolve the path, will now fail as they won't add `--nix` to the command they run.

I am aware of `nix` options in `stack.yaml` but this does not scales up to team collaboration on GitHub, as some members might not be running NixOS.

Would it be possible to add a global option to enable the Nix mode? (or could we even it simply enabled automatically if running on NixOS?), This would solve many issues.

Thanks

**Comment by nh2** [comment]
Be aware that the `stack --nix` integration has some problems with detecting changes from your nix environment: https://github.com/commercialhaskell/stack/issues/2802

This may be a blocker for you, because it means that after a `stack build`, changes in system dependencies may not be reflected as you expect (e.g. say you put `opencv` into the nix environment, then after changing the opencv version, `stack build` may not pick that change up until you clean everything).

Independent of that, adding an environment variable invoking the same effect as the `--nix` flag might fulfill your request. Usually I think an explicit flag is better than environment variables, but I see the problem you mention with other programs like `codex` calling `stack` and not passing the flag. An environment variable you can set for the entire machine would mitigate that.

**Comment by nh2** [comment]
Actually this change seems to have enabled exactly what you're asking for (the `--nix` flag being automatically enabled on NixOS): https://github.com/commercialhaskell/stack/pull/3938

Maybe you just need to upgrade to a version that has that change in?

**Comment by snoyberg** [comment]
Closing due to merged #3938, please add a comment if this is still a problem.
