### ISSUE TITLE
stack-0.1.0.0 test suite should not depend on network access

### ISSUE THREAD

**Issue by peti** [commercialhaskell/stack#409]
The `stack`  test suite fails in Nix, because our build sandbox does not allow network access:

~~~
Failures:

  src/test/Stack/BuildPlanSpec.hs:50: (best-effort)
  1) Stack.BuildPlan finds missing transitive dependencies #159
       uncaught exception: HttpException (FailedConnectionException2 "raw.githubusercontent.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp))

  src/test/Stack/ConfigSpec.hs:75: (best-effort)
  2) Stack.Config.loadConfig finds the config file in a parent directory
       uncaught exception: HttpException (FailedConnectionException2 "raw.githubusercontent.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp))

  src/test/Stack/ConfigSpec.hs:86: (best-effort)
  3) Stack.Config.loadConfig respects the STACK_YAML env variable
       uncaught exception: HttpException (FailedConnectionException2 "raw.githubusercontent.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp))
~~~

If would be great if the test suite could be split into a part that works without network access and one that doesn't, so that can run at least those tests that succeed without an Internet connection.

**Comment by snoyberg** [comment]
We do quite a few things in the test suite which require internet access, quite on purpose. We need to be aware if builds stop working because internet-based resources are unavailable. Splitting up the test suite in this way is a heavy burden, and provides no benefit to this project that I can see (I had similar reservations about http-client, and those reservations have been true so far).

**Comment by peti** [comment]
Well, as-is, we cannot execute the test suite in NixOS.

**Comment by snoyberg** [comment]
Understood, thanks for letting me know.
