### ISSUE TITLE
"Inconsistent dependencies" bug with packages in custom Setup.hs and extra-deps

### ISSUE THREAD

**Issue by brandon-leapyear** [commercialhaskell/stack#4221]
### General summary/comments (optional)

See https://github.com/brandon-leapyear/stack-inconsistent-deps/blob/master/README.md

### Steps to reproduce

1. Clone the [minimal repo](https://github.com/brandon-leapyear/stack-inconsistent-deps)
1. Run `stack build --only-dependencies --stack-yaml stack-broken.yaml`

### Expected

`stack build --only-dependencies` should collect all of the needed dependencies, regardless of whether the package is in `packages` or `extra-deps` in `stack.yaml`

### Actual

Errored with "Inconsistent dependencies were discovered while executing your build plan. This should never happen, please report it as a bug to the stack team."

I don't think something necessarily went wrong, since we have an atypical package layout, but it might reveal some assumptions that are being made that maybe shouldn't be mode.

### Stack version

```
$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

From `github.com/commercialhaskell/stack/releases`

**Comment by mattaudesse** [comment]
Thanks @brandon-leapyear - nice catch, and rolling everything up into an easily testable repo was pretty awesome of you.

`git shortlog -sn src/Control/Concurrent/Execute.hs` makes me think either @mgsloan or @snoyberg would be good folks to ask about this.

It's pretty easy to pin down [where this comes from](https://github.com/commercialhaskell/stack/blob/3b61926/src/Control/Concurrent/Execute.hs#L121) but I think you're probably right about it being a more general matter of assumptions (although maybe there's a clear answer I'm just not familiar enough to know).

```haskell
117     loop = join $ atomically $ breakOnErrs $ withActions $ \as ->
118         case break (Set.null . actionDeps) as of
119             (_, []) -> do
120                 inAction <- readTVar esInAction
121                 if Set.null inAction
122                     then do
123                         unless esKeepGoing $
124                             modifyTVar esExceptions (toException InconsistentDependencies:)
125                         return $ return ()
126                     else retry

...
```

I'm not sure if this works as intended or is a legit defect, but I've labelled it with the "bug" tag because I agree it seems surprising.

**Comment by snoyberg** [comment]
The backpack oriented changes around component based build plans may help with this. I'm going to add this issue to the pantry project.

**Comment by facundominguez** [comment]
Note that the failure depends on history. e.g. asking to build the dependencies of `bar` first has the command succeed.
```
stack build --only-dependencies --stack-yaml stack-broken.yaml bar
stack build --only-dependencies --stack-yaml stack-broken.yaml
```
If stack builds are supposed to be reproducible, it should always fail or always succeed. It looks like a bug.
