### ISSUE TITLE
Warn on untested GHC version

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4246]
Early in Stack's development, we made the decision to build via calling out to the `Setup.hs` files, which allows us to use the version of the `Cabal` library that ships with GHC itself for performing builds. This means that, for the most part, we automatically get support for newer versions of GHC without any changes to Stack. However, this doesn't always work perfectly:

* There are sometimes changes to how the `Setup.hs` script needs to be called which cause breakage
* The Cabal file format has been changing often recently, and more of these changes have been making their way into Stackage snapshots quickly, causing older Stack versions to break on these snapshots

We could make some requirements on delaying uptake of new Cabal format versions, but that's only delaying the inevitable: some Stack users will ultimately try to use a new snapshot with a new version of the cabal file format, and will file bug reports.

Instead, to address both problems, I propose that when you use Stack with a version of GHC it hasn't been tested against, Stack prints a warning about this and recommends checking if a new version of Stack is available via `stack upgrade`.

Related:

* https://github.com/commercialhaskell/stack/commit/dae7e1efcd315b60652f80af35f16d153ba0971b
* https://github.com/commercialhaskell/lts-haskell/issues/160
* https://github.com/commercialhaskell/lts-haskell/issues/159
* https://github.com/commercialhaskell/lts-haskell/issues/154
* https://github.com/commercialhaskell/lts-haskell/issues/155

**Comment by dbaynard** [comment]
That sounds reasonable. What are the other options, though? Could `stack` install the more recent version of `Cabal`?

Will the warning show when it's a dependency that needs to build, rather than the main package itself?

**Comment by snoyberg** [comment]
> Could stack install the more recent version of Cabal?

Two answers:

* For _building_, the new version of Cabal is automatically available in the GHC global package database, and is already used. Assuming that it keeps the same command line interface, everything works.
* For parsing Cabal files: no, Stack itself needs to be compiled against the new version of the library.

> Will the warning show when it's a dependency that needs to build, rather than the main package itself?

I'm considering the warning for any time you try to use a GHC version that hasn't been tested. It doesn't matter what you're trying to build.

**Comment by snoyberg** [comment]
Yes, though I've already implemented that warning on parse errors here: https://github.com/commercialhaskell/stack/commit/dae7e1efcd315b60652f80af35f16d153ba0971b. I want to broaden this though to even cases where the parse doesn't succeed since there may be other failure cases we don't anticipate.

**Comment by DanBurton** [comment]
I have a counter proposal, though its implementation is more complex. Actually, both could be implemented, but in this case they would solve the same problem.

In a much more general sense, I'd like for stack to be able to consult with some sort of repository of "known failures" and provide recommendations accordingly. For example:

* Stack encounters a build failure due to being unable to parse `foo.cabal` from Stackage snapshot package `foo`
* Stack checks in the known failures repository, and finds that `foo` is known to fail in this way for stack versions < `x`
* Stack reports the suggested remedy (as recorded in the known failures repo) to the user: `stack upgrade`

In general, I think if stack could somehow automatically convey that "we know about this issue, and here is the solution," this would be a very nice usability improvement for users. This doesn't help the first few people who encounter the error, but once the error is reported and a workaround discovered, it helps everyone else who later encounters the same error.
