### ISSUE TITLE
Pass --depth 1 to git

### ISSUE THREAD

**Issue by domenkozar** [commercialhaskell/stack#4345]
Some git repositories can be really big (i.e. amazonka), does stack need anything else from the git history besides the latest revision? This would save bandwidth and time fetching git dependencies.

**Comment by mihaimaruseac** [comment]
It seems that we are already doing this?

https://github.com/commercialhaskell/stack/blob/7574e33f119125f7d2517a13e26489b89696f0ed/src/Stack/Upgrade.hs#L203

**Comment by mgsloan** [comment]
@mihaimaruseac That is the invocation for stack upgrading from its own source repo.  I believe that @domenkozar is referring to the invocations for fetching dependencies from git.

IIRC the reason depth wasn't set to 1 was in order to have sharing of git objects when updating the git dependencies - I believe at some point it would try to reuse the existing repo instead of recloning.  Looks like now it simply reclones each time, though, so indeed `--depth 1` could be used here - https://github.com/commercialhaskell/stack/blob/2c8cdfbd5ece763a1df809d6e3ed0520b2642fd5/src/Stack/PackageLocation.hs#L229

**Comment by mihaimaruseac** [comment]
Makes sense then. i'll do a PR asap in that case.

**Comment by mihaimaruseac** [comment]
Oh, but that file has been dropped from master

**Comment by mihaimaruseac** [comment]
If I understand https://github.com/commercialhaskell/stack/blob/7574e33f119125f7d2517a13e26489b89696f0ed/subs/pantry/src/Pantry/Types.hs#L1318-L1331 correctly then it's now cloning at a specified commit.

Guess I'll just have to trace it when I get some more free time and see how it behaves.

**Comment by domenkozar** [comment]
That is using the tarball without git, which is a good alternative. But using git could have a similar performance, if `--depth 1` was added a few lines above.

**Comment by domenkozar** [comment]
I see, it cloning revision even requires special feature on the server: https://stackoverflow.com/questions/31278902/how-to-shallow-clone-a-specific-commit-with-depth-1

I guess the only thing that can be done then is to make depth an option, so user can hand-pick it.

**Comment by dbaynard** [comment]
Yes, a special feature, though we can pick sensible defaults?

**Comment by snoyberg** [comment]
How about a setting in the `extra-deps` itself saying whether to turn on `--depth 1` or not? Then we can bikeshed on whether on or off is the correct default.

**Comment by snoyberg** [comment]
Moved to wishlist https://github.com/commercialhaskell/stack/wiki/Wishlist
