### ISSUE TITLE
user guide dependencies example is broken

### ISSUE THREAD

**Issue by rlowrance** [commercialhaskell/stack#4432]
I'm new to stack and following the user guide. I'm up to the dependencies section and have added the "-test" dependency as instructed.

My package.yaml file contains these lines:
    dependencies:
    - base >= 4.7 && < 5
    - test # added 2018-12-05 REL

I then run "stack build" and see this error message:
$ stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for helloworld-0.1.0.0:
    test needed, but the stack configuration has no specified version (no package with that name found, perhaps there is a typo in a package's
         build-depends or an omission from the stack.yaml packages list?)
needed since helloworld is a build target.

Some different approaches to resolving this:

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. This can be convenient
    when dealing with many complicated constraint errors, but results may be unpredictable.

* * *
Is there a fix?

**Comment by mattaudesse** [comment]
Hey @rlowrance,

I believe you're referring to [this section of the docs](https://docs.haskellstack.org/en/stable/GUIDE/#adding-dependencies), right? Are you sure you meant *`test`* and not *`text`*?

I'm going to close this issue since it sounds like a typo, but if that's not the case please let me know and we can reopen. Welcome to `stack` by the way!
