### ISSUE TITLE
A regression in "stack templates"

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/stack#4484]
### General summary/comments (optional)

Description of `stack templates` used to just list available templates, and that's what it's said to do when you run `stack --help` still. But now it outputs just some text instead of the list of templates. This breaks tooling.

### Steps to reproduce

Run `stack templates`.

### Expected

List of available templates.

### Actual

Some text is printed.

### Stack version

```
$ stack --version
1.9.3 x86_64 hpack-0.31.1
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by qrilka** [comment]
This was changed in https://github.com/commercialhaskell/stack/pull/4129 and was listed in changelog for the version 1.9.1

**Comment by mrkkrp** [comment]
Well, that’s bad, the useful functionality is now lost.

**Comment by dbaynard** [comment]
The old behaviour does seem useful. Perhaps we could put a list of example templates in stack's `config.yaml`.

**Comment by mihaimaruseac** [comment]
Provided it won't result in people opening PRs to add their templates there

**Comment by dbaynard** [comment]
> Perhaps we could put lists of our favourite templates in our own stack config.yaml

Ah, I think I was unclear. I was suggesting that the config.yaml might have a new field, and that if that field is present `stack templates` lists the templates from that field, otherwise it shows this message.

If you understood me correctly, though, then I don't understand your comment about PRs!

In any case, I'm not particularly bothered by the lack of a templates list, but if this is a desirable feature it might be implemented without much trouble.

**Comment by mihaimaruseac** [comment]
With your explanation then it makes more sense and I agree with that

I'm also not bothered by the lack of the list

**Comment by dbaynard** [comment]
Closing as the documentation explains the new behaviour.

If there's demand for the behaviour suggested in https://github.com/commercialhaskell/stack/issues/4484#issuecomment-452460200 the please reopen the issue (if you want to contribute the PR, even better! But please reopen the issue first).
