### ISSUE TITLE
Why is yaml 0.11.x not supported?

### ISSUE THREAD

**Issue by peti** [commercialhaskell/stack#4485]
stack-1.9.3 compiles and works fine with the latest version of yaml, but the Cabal file won't allow it to be used during the build. Is there a particular reason why that it is so?

**Comment by peti** [comment]
Well, for people who'd like to distribute `stack` such as myself, it would be very helpful if the Cabal file on Hackage would allow yaml-0.11.x since we're not running builds with `cabal-install`. It would be great if you could edit the file on Hackage so that it includes the new version in the range.

**Comment by borsboom** [comment]
I do my best to bump the upper bounds on Hackage to keep up with the version in stackage nightly, but between holidays and major winter storms knocking out power and causing sporadic Internet connectivity, I've fallen behind.  In any case, I've now bumped `yaml`, `hspec`, and and `QuickCheck` upper bounds.

By the way, we always upload revision 0 to Hackage without any upper bounds, and add the bounds to revision 1.  So in future, you can grab revision 0 to get past this sort of problem.  You can also download the sdist without any bounds from https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-sdist-0.tar.gz (this is identical to the sdist uploaded to Hackage).

**Comment by borsboom** [comment]
One other note, though: if you're distributing Stack I'd recommend against using different versions of dependencies than the official binary releases.  If at all possible, use the same versions of dependencies as specified in the source code's `stack.yaml` and its referenced Stackage snapshot.  That way you won't get unexpected divergency of behaviour that can be caused by different dependency versions (we've run into this happening more than once).  We recommend statically linking `stack` with its Haskell dependencies rather than trying to use shared libraries.
