### ISSUE TITLE
Spurious error when loading package into ghci

### ISSUE THREAD

**Issue by dalejordan** [commercialhaskell/stack#449]
I have a package which builds without error but fails to load in
ghci with a spurious parse error:

    [Matrix] $ stack ghci Matrix
    Configuring GHCi with the following packages: Matrix
    GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
    [1 of 2] Compiling MatrixInternal   ( /home/dale/stack/Matrix/MatrixInternal.hs, interpreted )
    [2 of 2] Compiling Matrix           ( /home/dale/stack/Matrix/Matrix.hs, interpreted )

    /home/dale/stack/Matrix/Matrix.hs:114:1:
        Parse error in pattern: (M (_) m v)     --NB. the inner "(_)" is "_" in the source file
    Failed, modules loaded: MatrixInternal.
    𝛌> :q

The code it is complaining about is:

    (!) :: Matrix a -> (Int,Int) -> a
    {-# INLINE (!) #-}
    (M _ m v) ! ij = v V.! encode m ij

If I specify the major source file it just gives me the ghci prompt,
but I can load the load the modules OK.

    [Matrix] $ stack ghci Matrix.hs
    Configuring GHCi with the following packages: 
    GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
    𝛌> :t shape

    <interactive>:1:1: Not in scope: ‘shape’
    𝛌> :l Matrix.hs
    [1 of 2] Compiling MatrixInternal   ( MatrixInternal.hs, interpreted )
    [2 of 2] Compiling Matrix           ( Matrix.hs, interpreted )
    Ok, modules loaded: Matrix, MatrixInternal.
    𝛌> :t shape
    shape :: Matrix a -> (Int, Int)
    𝛌> :q
    Leaving GHCi.

    [Matrix] $ stack --version
    Version 0.1.1.0, Git revision 91fe70306f51eb3d68667a0d6e09a7d7ebbeb2b6

I suppose the latter behaviour is a feature of the stack environment,
but the parse error is mystifying.

**Comment by snoyberg** [comment]
@chrisdone any thoughts?

**Comment by chrisdone** [comment]
Haven't the foggiest what would cause that. I guess you could paste your `stack ghci Matrix -v` output? https://gist.github.com/

**Comment by dalejordan** [comment]
[Output here] (https://gist.github.com/dalejordan/899c520a2300959f4c4f)
[Source code for package] (https://github.com/dalejordan/Matrix)

**Comment by hesselink** [comment]
I've seen this before. It happens because `stack ghci` enables all extensions from the cabal file. In this case the culprit is `BangPatterns` (see [the GHC documentation on this](https://downloads.haskell.org/~ghc/7.8.4/docs/html/users_guide/bang-patterns.html#bang-patterns-sem)), which will cause the code to fail to parse.

I think in this case stack shouldn't add the extensions, since they're in the `other-extensions` field:

```
For packages using 'cabal-version: >= 1.10' the 'extensions' field is
deprecated. The new 'default-extensions' field lists extensions that are used
in all modules in the component, while the 'other-extensions' field lists
extensions that are used in some modules, e.g. via the {-# LANGUAGE #-}
pragma.
```

**Comment by chrisdone** [comment]
@hesselink Thanks for contributing that tidbit. From the Cabal API documentation there isn't explanation as to how the two fields differ. In other words, the `other-extensions` field is ignorable for our purposes.

**Comment by dalejordan** [comment]
@hesselink : Thanks for pointing out that syntax ambiguity with (!).  I changed my code and all is good.  I might want to use BangPatterns in that module in the future.

**Comment by int-index** [comment]
I've run into a more subtle manifestation of this issue because I have `PolyKinds` in my `other-extensions` field, so it caused strange type errors that looked like compiler bugs.

I don't think, however, that `stack` should ignore the `other-extensions` field. It should enforce it: if the field is present in the `.cabal` file then only the listed language extensions should be allowed.

But as a short-term workaround, ignoring `other-extensions` sounds appropriate.
