### ISSUE TITLE
Simplify/clarify/document Stack.Runners behavior around lock files, Nix, and Docker

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4636]
The `Stack.Runners` and related modules have quite a bit of complexity around three related concepts:

* Lock files, to ensure that different invocations of Stack don't trample each other (introduced by @rrnewton)
* Running commands inside a Docker container (introduced by @borsboom)
* Running commands inside a Nix shell (introduced by @mboes)

I'm fairly certain that these features are not currently interacting correctly with each other, and in some cases may not be interacting correctly on their own either. I'm working to clean up and simplify this code. I've started with a number of cleanups which should not change behavior at all to make things easier to see. I intend to next open up PRs which change the behavior, add questions, and/or add explanations of behavior.

Any feedback from those who implemented or are using these features is encouraged.

**Comment by snoyberg** [comment]
Some questions that pop up for me are:

* Is anyone actually using the file locking functionality? It's off by default (enabled with `STACK_LOCK`), and seems to be haphazardly applied right now.
* Is there any use case where Docker and Nix are both used? Would it be reasonable to enforce that only one of those is used at a time?
* What is the expected behavior of the `stack setup` command for the Docker and Nix use cases? I'm guessing it's logical to use `stack setup` inside a Docker container, but I'm less certain of within Nix
* There's a `--plain` flag for `stack exec`, with a comment about it being useful for Docker. But I'm not sure _why_ it's useful for Docker, especially as it seems to have (almost?) identical behavior to the non `--plain` usage
* Are there any commands people are aware of where the behavior for Docker or Nix is particularly surprising that I should be aware of?

**Comment by mboes** [comment]
- I think it's fine to make Docker and Nix either/or.
- I think `setup` should be a no-op in the Nix case (I believe that's currently the case). Though arguably, it could be made to download all dependencies of the nix-shell, so that a `stack build` immediately following a `stack setup` never has to download any system dependency.

**Comment by snoyberg** [comment]
Email sent to Stack mailing list regarding lock file support:

https://groups.google.com/d/msg/haskell-stack/bZgBHYCP2MQ/wqmgFp3iAgAJ

**Comment by snoyberg** [comment]
I've opened up #4647 which I addresses the majority of what I was hoping to achieve here.

**Comment by borsboom** [comment]
> What is the expected behavior of the stack setup command for the Docker and Nix use cases? I'm guessing it's logical to use stack setup inside a Docker container, but I'm less certain of within Nix

As you correctly guessed, `stack setup` (or the implicit setup of GHC when `--system-ghc` is enabled, as it is by default) is common and logical in the Docker case.

> Is there any use case where Docker and Nix are both used? Would it be reasonable to enforce that only one of those is used at a time?

I recall there having been some issues opened by NixOS users wanting to use `--docker`.  This may have stemmed from `--nix` being enabled by default on NixOS, but I'm not sure if that's still the case (I think the default behaviour was changed at some point).  From my point of view as a non-Nix user, I think it makes sense for these to be mutually exclusive since it introduces a lot of extra interaction, as long as there is a clear error message to that effect.
