### ISSUE TITLE
Inform the user why sudo is necessary in get-stack

### ISSUE THREAD

**Issue by jkachmar** [commercialhaskell/stack#4672]
Currently it looks like `get-stack` prompts the user for `sudo` permissions in three broad cases:

- when attempting to perform filesystem operations related to installing `stack` to a target directory
  - e.g. https://github.com/commercialhaskell/stack/blob/master/etc/scripts/get-stack.sh#L529
- when trying to install some generic, required OS dependencies via `try_install`
  - e.g. https://github.com/commercialhaskell/stack/blob/master/etc/scripts/get-stack.sh#L507
- when trying to install some specifically required OS dependencies
  - e.g. (for apt-get) https://github.com/commercialhaskell/stack/blob/master/etc/scripts/get-stack.sh#L158

In each of these cases it would probably be helpful if the script could inform the user why exactly `sudo` is being requested so that they may better understand the implication of supplying these permissions.

**Comment by jkachmar** [comment]
For reference, this was promoted by [a discussion on Twitter](https://mobile.twitter.com/phadej/status/1111354243926102019).

**Comment by borsboom** [comment]
The script prints the `sudo` commands it will run and then uses `sudo -k` in order to force `sudo` to prompt for a password.  We can pretty easily add a description outlining the reason to print beforehand.

However, there's one potential problem: `sudo -k` won't prompt for a password if your user is configured with `NOPASSWD` in `sudoers`.  Which means on such systems you won't get a chance to confirm the commands before they're run.  Of course, having that setting is inherently insecure, so maybe that's OK?  It's probably also desirable if doing an automated installation when there's no interactive terminal available (for example, on a CI system).

**Comment by borsboom** [comment]
PR: https://github.com/commercialhaskell/stack/pull/4697

**Comment by snoyberg** [comment]
Fixed by #4697, closing
