### ISSUE TITLE
Stack should intelligently select a resolver based on a installed GHC version

### ISSUE THREAD

**Issue by drwebb** [commercialhaskell/stack#468]
It would be nice to have resolver automatically prefer a nightly (at the moment until LTS 3.x is rolled out at least) snapshot if GHC7.10 is already installed on the user's system. If multiple versions are present I suppose we could go with what is most stable, i.e. the current LTS version.

**Comment by DanBurton** [comment]
I think "current LTS" is the preferable default, regardless of what is
already installed.

I'm not entirely opposed to a temporary hack to ease people onto ghc 7.10
if they already have it, though, since LTS 3 is so imminent.

-- Dan Burton

**Comment by snoyberg** [comment]
For the record, I asked @drwebb to open this issue. Your point is valid @danburton, it really isn't clear that any change from our current behavior would be a good one. An example of a downside would be a user being pushed to a stale LTS just because he/she has a distribution provided GHC.

Does anyone feel strongly that we should change the default? If not, let's attack this with better documentation.

**Comment by drwebb** [comment]
I agree with the better docs suggestion, I'm not sure how it works at the moment, but `stack init`should do more than just suggesting downloading GHC 7.8 through `stack setup` if the user has GHC 7.10 already, and pose another option to be to use an appropriate nightly resolver. Apologies if this is already the case, I haven't tested on a fresh system.

**Comment by snoyberg** [comment]
We want `stack init` to avoid getting in your face. If it can't find a matching snapshot, it gives you options for choosing one explicitly. You can give it command line parameters to let it know what your preferences are. I think we should include this in #489. I'm going to close this and we'll focus on #489 instead.
