### ISSUE TITLE
Support "last install" symlinks on windows

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#470]
PR #442 adds some directory symlinks to the `.stack-work` directory, but only on posix operating systems.  Ideally, these symlinks would also exist on windows, particularly since scripts might rely on these paths.

An implementation of this would look like running `mklink`.  Unfortunately, it looks like the [creation of symbolic links is rather fiddly on windows](http://security.stackexchange.com/questions/10194/why-do-you-have-to-be-an-admin-to-create-a-symlink-in-windows), so failure to do this on windows should just log a warning, rather than bail out.

**Comment by snoyberg** [comment]
This is adding a lot of finicky behavior for a feature I was already on the fence about. I could be convinced otherwise, but right now I'm -1.

@manny-fp since you seemed interested in this feature, do you have any thoughts?

For the record, I've run up against situations already where presumably this symlink would be useful, and `stack path` worked perfectly for my scripting needs.

**Comment by manny-fp** [comment]
`stack path` works for me too.

**Comment by mgsloan** [comment]
Yup, from a quick google I thought windows had reasonable symlink support, but this turned out to be wrong.  Sad to see a good feature omitted due to Windows, but OS consistency is important.  Closing these issues and the PR.
