### ISSUE TITLE
LTS-13.11 on FreeBSD 12 not working

### ISSUE THREAD

**Issue by tdxiong** [commercialhaskell/stack#4755]
LTS-13.11 is for GHC 8.6.3. By setting LTS-13.11 in stack.yaml, stack will complain that no setup information is found for GHC 8.6.4

My stack is 1.9.3 which is added by pkg install

**Comment by borsboom** [comment]
Please try lts-13.10.  Something went a bit funny with lts-13.11 and it is actually based on GHC 8.6.4 even though https://www.stackage.org/lts-13.11 says otherwise.

@snoyberg Is there any way we can "resync" stackage.org so that https://www.stackage.org/lts-13.11 shows the correct GHC version?  This has caused a fair bit of confusion, especially since GHC 8.6.4 has so few bindists available.

**Comment by snoyberg** [comment]
Actually, I think I better go in the opposite direction: have lts-13.11 say GHC 8.6.3. From what I can tell, the upgrade didn't work correctly on that point release.

**Comment by borsboom** [comment]
But when you use lts-13.11 with `stack` it does actually use GHC 8.6.4.  Would you change lts-13.11 to _actually_ be GHC 8.6.3?  Changing an existing snapshot that people may be using seems like it would be even more confusing.

**Comment by snoyberg** [comment]
The original change was really the problem, it was actually built against 8.6.3 AFAICT. I know changing it back isn't a good call, but leaving it with a set of packages that may not build with GHC 8.6.4 isn't good either.
