### ISSUE TITLE
GPG Download Verification

### ISSUE THREAD

**Issue by onslaughtq** [commercialhaskell/stack#4841]
The current set of binaries for 2.1.0.1 release candidate are missing their ASC files and the SHA256 checksum files are improperly formatted; they are missing the filename next to the SHA256 checksum. Is it possible to post the ASC files for these binaries?

**Comment by borsboom** [comment]
I haven't been doing the signing part for release bindists in the interests of saving some time during the process, but the final release will include them.

I suppose there's no harm in adding the filenames to the contents of the `.sha256` files, even though it's implied by the filename of the `.sha256` file itself.  The only risk is that it could break existing file verification (since we've never included filenames).

**Comment by onslaughtq** [comment]
Thanks for the update.  The filename in the SHA256 file is less of a concern with the assurance that the final release will have it.

**Comment by onslaughtq** [comment]
@borsboom Apologies, but it appears that the signatures were made with your personal public key, and not the public key associated with dev@fpcomplete.com

**Comment by borsboom** [comment]
That is correct, in order to allow sharing the work of making stack releases we are now signing with personal keys.  Note that `dev@fpcomplete.com` has signed my key.
