### ISSUE TITLE
Unable to use stack v.2.2.0 with docker image fpco/lts-13.20 in Darwin

### ISSUE THREAD

**Issue by swamp-agr** [commercialhaskell/stack#4850]
### General summary/comments (optional)

- First, I upgraded `stack` using `stack upgrade --git`. 
- Next, I upgraded my projects to GHC 8.6.5.
- One of my projects requires cross-compilation (host: `Darwin`, target: `Linux`) and its build failed.

It seems, that `stack` tried to obtain `v2.2.0` from github releases, but `v2.2.0` had not been released yet: https://github.com/commercialhaskell/stack/tags (last release on today, 2019-06-04, is `v2.1.0.3`).

### Steps to reproduce

YAML code snippet related to docker part from `linux.stack.yaml`:

```yaml
flags: {}

extra-package-dbs: []

packages:
- '.'

system-ghc: false

docker:
  image: fpco/stack-build:lts-13.20
  enable: true
  run-args:
  - --ulimit=nofile=60000
  set-user: true

resolver: lts-13.21
```

```
$ stack --stack-yaml linux.stack.yaml build --verbose
Version 2.2.0, Git revision f6258124cff9a7e92bcb5704164a70e149080e88 x86_64 hpack-0.31.1
2019-06-04 10:43:07.470473: [debug] Loading project config file linux.stack.yaml
2019-06-04 10:43:07.487755: [debug] SELECT COUNT(*) FROM "last_performed" WHERE ("action"=?) AND ("timestamp">=?); [PersistInt64 1,PersistUTCTime 2019-06-03 07:43:07.485888 UTC]
2019-06-04 10:43:07.489438: [debug] Run process: /usr/local/bin/docker --version
2019-06-04 10:43:07.553349: [debug] Process finished in 64ms: /usr/local/bin/docker --version
2019-06-04 10:43:07.553680: [debug] Run process: /usr/local/bin/docker inspect fpco/stack-build:lts-13.20
2019-06-04 10:43:07.617588: [debug] Process finished in 64ms: /usr/local/bin/docker inspect fpco/stack-build:lts-13.20
2019-06-04 10:43:07.618560: [info] Downloading Docker-compatible stack executable
2019-06-04 10:43:08.594647: [error] Control.Exception.Safe.throwString called with:

Could not get release information for Stack from: https://api.github.com/repos/commercialhaskell/stack/releases/tags/v2.2.0
Called from:
  throwString (src/Stack/Setup.hs:1896:14 in stack-2.2.0-YwVpXcFk6j3r0tzRXEQ9c:Stack.Setup)
```

### Expected

I expected GHC 8.6.5 setup and further build, installation.

### Actual

Build failed. See **Steps to reproduce** for more details.

### Stack version

```
$ stack --version
Version 2.2.0, Git revision f6258124cff9a7e92bcb5704164a70e149080e88 x86_64 hpack-0.31.1
```

### Method of installation

- Stack was installed as official binary, downloaded from stackage.org.
- It was subsequently upgraded to `1.9.1`. 
- A couple weeks ago I decided to upgrade it from Git (see **Problem Summary**).

**Comment by swamp-agr** [comment]
- If it is release-specific issue, could you please provide planned release date for `v2.2.0`, so I could wait for it? 
- It will be automatically resolved after release, I think, since release will be available by requested API URL.
- If we go this way, please be aware that the situation with `release` and `docker` might be repeated in future.

**Comment by borsboom** [comment]
For background: Stack needs a Docker-compatible executable of `stack` in order to run itself within a Docker container.  If your host platform matches the Docker image platform it will use the same `stack` binary as the host, but if it does not (as in the case of a macOS) then Stack will have to retrieve a known-compatible `stack` binary matching the host version.  It can only do that for officially released versions of Stack, since those are the ones where we have official binaries available (the same ones used by the get.haskellstack.org script and `stack upgrade`).

v2.2.0 is the current development branch, so there are no such binaries available.  However, you can use the `--docker-stack-exe` argument to point it to a compatible binary (which you will have to build in Linux).  You _could_ use v1.9.3 with `--docker` to build such a binary for v2.2.0.

To answer your questions:

> If it is release-specific issue, could you please provide planned release date for v2.2.0, so I could wait for it?

There will never be a release of v2.2.0 since it's the development branch, but at some point we'll cut a v2.3 release candidate from it (and move development to v2.4).  There is no current planned release date for v2.3 (I wouldn't expect it for at least six months).  However, we will be releasing v2.1 very soon (most likely within a week unless anyone discovers a major regression).

> It will be automatically resolved after release, I think, since release will be available by requested API URL.

That is correct.

> If we go this way, please be aware that the situation with release and docker might be repeated in future.

Yes, this is how it always works for unreleased versions.

**Comment by mtolly** [comment]
Not a huge blocker but just an FYI that I ran into this when trying to get a Docker build working on Arch (using an older Ubuntu container).

1. I installed the current Arch version of Docker, for which `docker --version` prints `Docker version 19.03.8-ce, build afacb8b7f0`

2. This caused Stack to print `Cannot get Docker version (invalid 'docker --version' output).`

3. After investigating I saw that you guys had fixed this in commit https://github.com/commercialhaskell/stack/commit/427f85f45fdf4ba537ac6406c01d67c8b85d0f6b

4. So, I did `stack upgrade --git` to get this, since it hasn't been in a release yet

5. But then I get `Could not get release information for Stack from: https://api.github.com/repos/commercialhaskell/stack/releases/tags/v2.4.0`

From what I can tell, Stack 2.3 is imminent which will include the parse fix, so I assume I can switch to that and be set once that happens.
