### ISSUE TITLE
`snapshot.yaml` missing from source dist?

### ISSUE THREAD

**Issue by magthe** [commercialhaskell/stack#4860]
### General summary/comments (optional)

I'm trying to build stack 2.1.1, with the pre-built stack 2.1.1.

### Steps to reproduce

1. Download source from hackage
2. Download pre-built binaries from GitHub
3. Run `stack setup`

### Expected

GHC downloaded, no errors.

### Actual

```
$ stack setup --verbose
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
2019-06-13 21:09:02.582459: [debug] Checking for project config at: /hfa/stack/src/stack-2.1.1/stack.yaml
2019-06-13 21:09:02.582949: [debug] Loading project config file stack.yaml
2019-06-13 21:09:02.593459: [debug] SELECT COUNT(*) FROM "last_performed" WHERE ("action"=?) AND ("timestamp">=?); [PersistInt64 1,PersistUTCTime 2019-06-12 21:09:02.593409327 UTC]
2019-06-13 21:09:02.593802: [debug] Not reading lock file
2019-06-13 21:09:02.594472: [error] Exception while reading snapshot from snapshot.yaml:
InvalidYaml (Just (YamlException "Yaml file not found: /hfa/stack/src/stack-2.1.1/snapshot.yaml"))

```

### Stack version

```
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from GitHub

**Comment by borsboom** [comment]
Ah, that is an oversight... but now that I'm trying an sdist that adds `snapshot.yaml` it exposes another problem: the `stack.yaml` refers to packages under `subs` which are also not in the sdist.  But it doesn't seem right to add the source code for those packages as the extra-source-files in the `stack` sdist, since hackage already contains those packages separately.  My inclination is that we should probably remove `stack.yaml` from the stack package on Hackage, since Hackage doesn't really support the concept of a multi-package "project," which is how we're using `stack.yaml` now.

@snoyberg, any thoughts?

**Comment by snoyberg** [comment]
I totally agree

**Comment by magthe** [comment]
The source distribution via GitHub does work, of course.

Just allow me to point out the slight irony in creating a build tool and then distributing it without the configuration required to build it using itself :/

**Comment by borsboom** [comment]
I've uploaded http://hackage.haskell.org/package/stack-2.1.1.1, which no longer has `stack.yaml`.

Irony is noted :).  The Hackage package is for convenience and bootstrapping purposes, but the official release is at https://github.com/commercialhaskell/stack/releases/tag/v2.1.1
