### ISSUE TITLE
Linux 64-bit, libgmp4 link broken

### ISSUE THREAD

**Issue by davidsd** [commercialhaskell/stack#4881]
The link to the Linux 64-bit, libgmp4 download on https://docs.haskellstack.org/en/stable/install_and_upgrade/#linux currently doesn't work.

**Comment by borsboom** [comment]
Good catch.  Removed those links (since we're no longer building gmp4 binaries) and also pointing static bindists where available here: https://github.com/commercialhaskell/stack/pull/4904.  I'll also update the release process to check all the download links in the docs.

**Comment by davidsd** [comment]
Thanks! Can I ask why there are no more gmp4 binaries? I have installed stack dozens of times on dozens of machines, and the gmp4 binaries have been needed EVERY time.

**Comment by borsboom** [comment]
In the case of x86_64, the static `stack` binary should work for you (since it doesn't need any dynamic libgmp on the system).  In the case of i386, the GHC release team stopped releasing gmp4 GHC bindists a couple of years ago, which makes it harder to build `stack` on those platforms. 

Basically, when it comes to platforms to support, we follow what GHC does (since there's little point having `stack` on platforms where it can't install GHC), unless volunteers step in to provide GHC bindists for those platforms (that's why we're still supporting, for example, FreeBSD)

**Comment by borsboom** [comment]
Oh and I tried building a static i386 stack-2.1.1 binary as well, but ran into some problems with dependencies failing in that context and didn't pursue it further.  Might try it again for the next release.
