### ISSUE TITLE
cannot `stack uprade --source-only` from 2.1.1 to 2.1.3 (Yaml file not found)

### ISSUE THREAD

**Issue by jwaldmann** [commercialhaskell/stack#4962]
### Steps to reproduce

```
stack upgrade --source-only -v
Version 2.1.1 x86_64
...
Warning: this is an unsupported build ...
```

### Expected

compile and install stack-2.1.3

### Actual

```
2019-07-15 16:54:49.814065: [debug] No project config file found, using defaults.
2019-07-15 16:54:49.820989: [debug] SELECT COUNT(*) FROM "last_performed" WHERE ("action"=?) AND ("timestamp">=?); [PersistInt64 1,PersistUTCTime 2019-07-14 14:54:49.820950269 UTC]
2019-07-15 16:54:49.839197: [info] Updating index to make sure we find the latest Stack version
2019-07-15 16:54:49.844019: [info] Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
2019-07-15 16:54:49.849609: [info] Downloading timestamp
2019-07-15 16:54:50.474691: [info] No package index update available and cache up to date
2019-07-15 16:54:50.474828: [info] Package index cache populated
2019-07-15 16:54:50.590618: [debug] Loading project config file /tmp/stack-upgrade-99fa4c29a7426ce4/stack-2.1.3/stack.yaml
2019-07-15 16:54:50.597660: [error] Could not parse '/tmp/stack-upgrade-99fa4c29a7426ce4/stack-2.1.3/stack.yaml':
YAML exception:
Yaml file not found: /tmp/stack-upgrade-99fa4c29a7426ce4/stack-2.1.3/stack.yaml
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

### Method of installation

* Via cabal-install

**Comment by dbaynard** [comment]
Thanks for the issue. Related: #4860. @borsboom Would you kindly take a look at this, too?

**Comment by borsboom** [comment]
So this is because we no longer include `stack.yaml` in the archive on Hackage, since that's a _project_ configuration which references a bunch of "sub-packages" in the same repo.  Hackage is not project-oriented but rather package oriented, so these "sub-packages" aren't included in the hackage sdist there but rather uploaded as separate packages (e.g. http://hackage.haskell.org/package/pantry and http://hackage.haskell.org/package/rio-prettyprint).

It's unfortunate that `stack upgrade --source-only` uses hackage to get the source, and then assumes it should contain a `stack.yaml`.  That's not something I realized, and apparently it's not a commonly used code path since this has been a problem since stack-2.1.1 was released and nobody seems to have noticed until now!

As a workaround for now, we could add a special `stack.yaml` that makes remote git references for the sub-packages rather than assuming they're in the distribution.  Or we could actually add all the sub-packages to the sdist as extra-source-files.  Not thrilled with either of these options, but they're the only things I can think of that will make existing versions of stack able to upgrade using `--source-only`.

Longer term, I think `stack upgrade --source-only` should be modified to download the source from, e.g. https://github.com/commercialhaskell/stack/archive/v2.1.3.tar.gz .

Alternatively, it could be modified to run `stack init` first but I think that's a bad idea for a few reasons:
  * The built `stack` would almost certainly have different dependency versions than official binaries, so it would be considered "unofficial."
  * This would miss things like the fork of `filelock` that has an unreleased bugfix that `stack` is currently using (we don't like depending on forks, but sometimes it's unavoidable).
  * It's possible that there wouldn't be _any_ snapshot found that would work, leaving `stack upgrade --source-only` broken.

**Comment by borsboom** [comment]
@snoyberg Any thoughts on :point_up:?

**Comment by snoyberg** [comment]
Aren't all of the subpackages currently uploaded to Hackage? Could we add a `stack.yaml` that refers to the uploaded packages?

It seems overall like the best move to solve a few related problems is to move the subpackages into their own repos, which I think you were already in favor of. What do you think?

**Comment by borsboom** [comment]
> Aren't all of the subpackages currently uploaded to Hackage? Could we add a stack.yaml that refers to the uploaded packages?

That's true, it can refer to the uploaded packages instead of the git repo.

> It seems overall like the best move to solve a few related problems is to move the subpackages into their own repos, which I think you were already in favor of. What do you think?

Yes, that'd definitely help (and would avoid needing yet another error-prone manual step in the release process to craft a special `stack.yaml` and get it into the sdist).

**Comment by dbaynard** [comment]
#4964 relates to this, yes?

**Comment by borsboom** [comment]
> #4964 relates to this, yes?

Yes.

**Comment by borsboom** [comment]
I've uploaded `stack-2.1.3.1` to Hackage which includes a `stack.yaml` and `snapshot.yaml` referencing former sub-packages on Hackage rather than in `subs/`.   `stack upgrade --source-only` seems to work now (see log below).

I still think it'd be better if `stack upgrade --source-only` downloaded the source from Github rather than Hackage, since this still ends up installing something different than `stack upgrade` binary would  since it picks up this hackage-only release (v2.1.3.1 vs. v2.1.3).

```
$ stack upgrade --source-only
Updating index to make sure we find the latest Stack version
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
Downloading snapshot
Updating index
Updated package index downloaded
Calculating hashes to check for hackage-security rebases or filesystem changes
Updating preexisting cache, should be quick
Populating cache from file size 612068864, hash 03f5764fa5f6a908ae0c5af93ce2fddfb4bfd69dec9c555f9cce7d6a5133edb0
Populating package index cache ...
Package index cache populated
Building all executables for `stack' once. After a successful build of all of them, only specified executables will be rebuilt.
stack> configure (lib + exe)
[1 of 2] Compiling Main             ( /private/var/folders/7c/m2fjlt7d27vgbtspfqr6594w0000gn/T/stack-upgrade39204/stack-2.1.3.1/Setup.hs, /private/var/folders/7c/m2fjlt7d27vgbtspfqr6594w0000gn/T/stack-upgrade39204/stack-2.1.3.1/.stack-work/dist/x86_64-osx/Cabal-2.0.1.0/setup/Main.o )
[2 of 2] Compiling StackSetupShim   ( /Users/manny/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /private/var/folders/7c/m2fjlt7d27vgbtspfqr6594w0000gn/T/stack-upgrade39204/stack-2.1.3.1/.stack-work/dist/x86_64-osx/Cabal-2.0.1.0/setup/StackSetupShim.o )
Linking /private/var/folders/7c/m2fjlt7d27vgbtspfqr6594w0000gn/T/stack-upgrade39204/stack-2.1.3.1/.stack-work/dist/x86_64-osx/Cabal-2.0.1.0/setup/setup ...
Configuring stack-2.1.3.1...
stack> build (lib + exe)
Preprocessing library for stack-2.1.3.1..
Building library for stack-2.1.3.1..
[  1 of 110] Compiling Network.HTTP.StackClient
[  2 of 110] Compiling Path.Extra
[  3 of 110] Compiling Path.Find
[  4 of 110] Compiling Paths_stack
...
```

**Comment by mpilgrem** [comment]
Closing given the passage of time.
