### ISSUE TITLE
Exception while reading lts-11.22 snapshot

### ISSUE THREAD

**Issue by NMerkley** [commercialhaskell/stack#4978]
My build server was suddenly unable to build a project using lts-11.22 due to being unable to download the yaml for lts-11.22. This appeared when running `stack build`
```
Exception while reading snapshot from lts-11.22 (7c8b1853da784bd7beb8728168bf4e879d8a2f6daf408ca0fa7933451864a96a,527801):
Download from https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/11/22.yaml was too large.
Expected: 527801, stopped after receiving: 527836
```
I deleted `~/.stack` on my development machine and the problem started appearing there as well. Curiously though, on both machines I was able to change the snapshot to 11.21, build, then back to 11.22 and it started working again.

The problem has been resolved, but I thought I'd put in a report about it. I can no longer reproduce it

**Comment by NMerkley** [comment]
It appears I spoke too soon. The problem comes back on any fresh clone of the project meaning the build server is still not able to build it

**Comment by borsboom** [comment]
I noticed this happen recently too.  Check for a `stack.yaml.lock` file, and try removing it.  The lock file contains the size and checksum of the snapshot that was used when it was written, and appears that the lts-22 snapshot was modified to remove a `publish-time` field (see [history](https://github.com/commercialhaskell/stackage-snapshots/commits/master/lts/11/22.yaml)), which changed the size and checksum.

In fact, if I reset my own `~/.stack`, forcing `stack` to re-download the snapshot, I get the same error you do with the `stack.yaml.lock` in my stack build directory (which uses lts-22).

@snoyberg / @qrilka is this expected behaviour?  Perhaps the snapshot URL in the lock file should include the git commit ID to ensure that _exactly_ the same snapshot file is downloaded instead of whatever is latest in the `master` branch?

**Comment by snoyberg** [comment]
This is expected behavior. The snapshots should never change once published. In this case, the snapshots were changing before the official release of the new Stack 2 release. In retrospect, I should have published those snapshots to an explicitly listed "beta" repo so that there were no modifications in the history of the official repo, but this is where we're at.

**Comment by borsboom** [comment]
Ok, so this would only effect people who used Stack 2 before it was released (or even had a release candidate).  I think we can close this and, for anyone who runs into it, just delete your `stack.yaml.lock` file so a new one gets created (or update the checksum and size in the file).
