### ISSUE TITLE
Binary upgrade of Stack fails due to GitHub API request limit

### ISSUE THREAD

**Issue by koterpillar** [commercialhaskell/stack#4979]
### General summary/comments (optional)

`stack upgrade` hits GitHub API request limit if run from behind a proxy which has enough GitHub API users.

### Steps to reproduce

* Share the IP address with enough GitHub API users, or make enough API calls yourself.
* Run `stack upgrade`.

### Expected

Stack upgrades to the latest published official release.

### Actual

```shell
$ stack upgrade

Warning: Exception occured when trying to perform binary upgrade:
         Control.Exception.Safe.throwString called with:

Could not get release information for Stack from: https://api.github.com/repos/commercialhaskell/stack/releases/latest
Called from:
  throwString (src/Stack/Setup.hs:1896:14 in stack-2.1.1-AFL4re0D1GV4wdhlVT8Mqc:Stack.Setup)


         Falling back to source upgrade
(...)
```

```shell
$ curl https://api.github.com/repos/commercialhaskell/stack/releases/latest
{
  "message": "API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

#1251 was a similar bug where the API calls were removed.

### Stack version

```
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by dbaynard** [comment]
@koterpillar This appears to have fallen through the cracks. I'm checking on it — thanks for your patience.

**Comment by dbaynard** [comment]
Would you be able to post a `--verbose` log (I appreciate it may be tricky to reproduce)?

**Comment by wolverian** [comment]
Here's a `stack build --docker --verbose` run failing:

~~~
% stack build --docker --verbose
Version 2.3.1, Git revision de2a7b694f07de7e6cf17f8c92338c16286b2878 (8103 commits) x86_64 hpack-0.33.0
2020-06-03 14:07:32.559328: [debug] Checking for project config at: /Users/ivacklin/src/bokken/stack.yaml
2020-06-03 14:07:32.560508: [debug] Loading project config file stack.yaml
2020-06-03 14:07:32.573862: [debug] SELECT COUNT(*) FROM "last_performed" WHERE ("action"=?) AND ("timestamp">=?); [PersistInt64 1,PersistUTCTime 2020-06-02 11:07:32.573777 UTC]
2020-06-03 14:07:32.575510: [debug] Run process: /usr/local/bin/docker --version
2020-06-03 14:07:32.937831: [debug] Process finished in 362ms: /usr/local/bin/docker --version
2020-06-03 14:07:32.938204: [debug] Run process: /usr/local/bin/docker inspect fpco/stack-build:lts-15.15
2020-06-03 14:07:33.022236: [debug] Process finished in 84ms: /usr/local/bin/docker inspect fpco/stack-build:lts-15.15
2020-06-03 14:07:33.023037: [info] Downloading Docker-compatible stack executable
2020-06-03 14:07:33.430722: [error] Control.Exception.Safe.throwString called with:

Could not get release information for Stack from: https://api.github.com/repos/commercialhaskell/stack/releases/tags/v2.3.1
Called from:
  throwString (src/Stack/Setup.hs:1813:14 in stack-2.3.1-uJmAnqRCkR1VKbFrmxCOZ:Stack.Setup)
~~~

Since this issue was originally about `stack upgrade`, should I submit this as a new issue?

**Comment by quickdudley** [comment]
I am currently hitting the same issue with `stack new`. The output has a lot of redundant detail but in summary it says the requests for `api.github.com/repos/commercialhaskell/stack-templates/contents/new-template.hsfiles` got back an HTTP 403 error and the response from the server included a link to [Github's API rate limiting information](https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting)

According to that documentation sending authenticated requests would mean a higher rate limit. To do this Stack would need a way to store a Github OAuth token and use it in those requests.

**Comment by mpilgrem** [comment]
@zzantares, a test of whether Stack is reading the environment variable is to try something like `stack new foo`. You should get output like:
~~~text
Using content of GH_TOKEN environment variable to authenticate GitHub REST API.
~~~

**Comment by zzantares** [comment]
@mpilgrem thanks! turns out it wasn't even an issue with GH API rate limits, but my DNS! Not sure why but there's a lot more info in #5063.
