### ISSUE TITLE
stack build --profile fails on a new project

### ISSUE THREAD

**Issue by mgeorgehallg** [commercialhaskell/stack#4986]
When building a new project with the --profile option, `stack exec` fails to find the executable.

### Steps to reproduce
1. `stack new thing`
2. `cd thing`
3. `stack build --profile`
4. `stack exec thing-exe` (or variations thereof, namely `stack exec -- thing-exe +RTS -p`)

Step 4 fails with
```
Executable named thing-exe not found on path: [...]
```

The executable exists and can be called manually with
```
./.stack-work/install/x86_64-osx/7242c30228aef3aec7a64a599b26297fef6f02828e6180b10d3ee5e9ee1b170c/8.6.5/bin/thing-exe
```

OS: macOS 10.14.4
Stack version: 2.1.3, installed via homebrew. 

Because the homebrew installation is officially unsupported, I should also note that first running `stack upgrade --force-download` then running steps 1 through 4 produces the same results.

EDIT: Apparently exec needs the --profile flag as well, as per [this issue](https://github.com/commercialhaskell/stack/issues/4863). 

The official documentation is incorrect, see [here](https://docs.haskellstack.org/en/stable/GUIDE/#debugging), so I think this still counts as an issue.

**Comment by dschrempf** [comment]
I also fought with this issue for an hour now.

Something must have changed, because I was profiling my code perfectly with

    stack build --profile
    stack exec thing -- +RTS -p

until recently.

I also noticed that after running

    stack build
    stack build --profile

Both commands don't do anything anymore. I guess that's why we now have to specify the `--profile` flag also with `stack exec` (because otherwise it wouldn't know which executable to run).
