### ISSUE TITLE
Dockerfiles for stack-build:lts-14, add hvr PPA

### ISSUE THREAD

**Issue by tarleb** [commercialhaskell/stack#5039]
There are docker images for fpco/stack-build:lts-14 on Dockerhub, but the respective Dockerfiles seem not to be part of this repo. It would be nice to have them here to make it easier to see differences to previous versions.

This feature request is sparked by the fact that it became more difficult to use the stack-build image as a general Haskell build image, due to the hvr PPA being no longer available by default. For example, the pandoc CI pipeline has been affected by this (jgm/pandoc#5692).

**Comment by dbaynard** [comment]
The image has been updated (5 hours after your post) — does that fix the actual issue?

There have been some changes to the docker base, recently — I've pinged the author.

**Comment by borsboom** [comment]
The Dockerfile is for the LTS-14.x images is here: https://github.com/commercialhaskell/stack/tree/stable/etc/dockerfiles/stack-build/lts-14.0

As always, it uses [the Stackage server bootstrap script corresponding to the Stackage LTS release](https://raw.githubusercontent.com/fpco/stackage/d4143f1845f26e8e99d0a1a8134d6ff535ab98b2/debian-bootstrap.sh) to set up the contents of the image.  That script switched over to having Stack manage the GHC installation rather than using the hvr PPA for LTS-14.

Generally, a new major LTS release means that breaking changes may be introduced, and the same is true for the Docker images (this one also moved to being based on Ubuntu 18.04 rather than 16.04).  To avoid surprising changes, it's a good idea to use the `lts-NN` tag to pin it to one major version.

At this point there's no reason for us to use the hvr PPA since Stack is able to do that work itself.  We're not planning to add it back in.  That said, CI scripts can use `apt-add-repository` to add it themselves.  I'd also be amenable to adding a `cabal` binary to future images, if that would be helpful (we had removed it because `stack solver` has been removed from stack-2.x, and that was the only Stack feature that needed a `cabal` binary to be available).

**Comment by tarleb** [comment]
Thank you for your quick replies! I had somehow missed the *stable* branch, thanks for pointing it out.

> At this point there's no reason for us to use the hvr PPA since Stack is able to do that work itself.

That makes sense. We'll update our CI scripts.

Thanks again!
