### ISSUE TITLE
Strange behaviour with docker integration when piping stack run to "less"

### ISSUE THREAD

**Issue by torgeirsh** [commercialhaskell/stack#5064]
### Steps to reproduce

Run "stack run | less" for a project that outputs a lot of text and has docker integration enabled.

### Expected

"less" can be operated normally to scroll the output from the program, etc.

### Actual

The keyboard doesn't work properly in "less", with random keystrokes being ignored or misinterpreted. Could it be related to docker's interactive mode?

```
$ stack run --verbose
...
[debug] Run process: /usr/bin/docker start -a -i 55d6d439bcca7ca3bb897411be0b5557ff00c2906407e8bc8549c537702f7ac0
...
```

### Stack version

```
$ stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mattaudesse** [comment]
Thanks for reporting @torgeirsh.

I've tried to replicate this on my machine but, so far, without success - do you happen to have a repo you could point us to where you reliably see the odd behavior?

Also, what OS + version of `less` are you running?

**Comment by torgeirsh** [comment]
I've made a repo that reproduces the problem: https://github.com/torgeirsh/stack-test

Just run "stack run | less" and try to scroll with the arrow keys and do a regex search or something similar.

I have the problem with Ubuntu 19.10 and less version 487, and also had it with Ubuntu 19.04 and the version of less it comes with.

**Comment by torgeirsh** [comment]
@mattaudesse have you had the opportunity to try the code in the repository? Do you get the same issue?

**Comment by mattaudesse** [comment]
Hey @torgeirsh, thanks for the example repo and sorry it's taken me so long to respond.

I tried `stack run | less` both with and without `docker` enabled on a Debian 9.11 virtual machine + `less 481 (GNU regular expressions)`. 

I can definitely see what you mean now: with `docker` enabled it does seem to glitch out in ways that I didn't observe while running outside of a container.

I think you're also onto something RE: the interactive `-i` flag. Based on a little experimentation, this seems to be an issue with `docker` itself rather than `stack` or anything to do with `Haskell` binaries.

When running a simple shell test without `docker`'s `-i` flag I get what seems to be pretty fluid behavior when piping through `less`:
```
docker run 9adc774bb5e5 bash -c 'while true; do openssl rand -base64 32; done' |less
```

But with `-i` turned on I see the same problems as what you reported above:
```
docker run -i 9adc774bb5e5 bash -c 'while true; do openssl rand -base64 32; done' |less
           ^^  
```

I'm happy to be proven wrong here but I don't think there's anything `stack` can do to fix the issue. 
It makes sense to retain the `-i` flag when engaging "`docker mode`" since some containerized apps will require interactivity.

I know it's not a satisfying answer but I think the `docker` folks are the right people to consult on this one, so I'm going to go ahead and close. Perhaps you could refer them to this thread.

Please let me know if I'm missing something and we can reopen if need be. Thanks again for reporting + providing an example repo.

**Comment by torgeirsh** [comment]
@mattaudesse I'll check with the docker people, but meanwhile, isn't it incorrect for stack to always use -i? Maybe this flag should be set via an option to the stack command instead?

**Comment by mattaudesse** [comment]
I suppose you could make a decent argument in either direction, but personally I'd lean toward always using `-i` (or at least leaving it as the default) to avoid expanding `stack`'s surface area and confusing casual users.

Configuration knobs wind up becoming a large portion of our open issues.

I don't have particularly strong feelings (nor ownership) around this, though - if other folks want to lobby for changing it and are willing to submit a PR that's fine too.
