### ISSUE TITLE
Change recommendation: include generated cabal files

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#5210]
For details of the proposal, see the blog post: https://tech.fpcomplete.com/blog/storing-generated-cabal-files

If you are in favor of this change, please press thumbs up below. If you are opposed, please press thumbs down. Of course, feel free to include additional comments below.

**Comment by gromakovsky** [comment]
One problem with this approach that I encountered is that rebases become more painful. We have [a repo](https://gitlab.com/morley-framework/morley) with many packages, each one has `package.yaml` and we store `.cabal` files in the repo. If someone updates `.cabal` file(s) in master and you update something different in `.cabal` files in your branch by updating `package.yaml` and regenerating them (e. g. you both add a new dependency), you will get unnecessary conflicts because hpack adds a line with a hash.

It's not something critical, I just wanted to warn people about this inconvenience.

**Comment by cdornan** [comment]
I have been getting feedback from non-stack users complaining about repos with no cabal files. From their perspective it is frustrating so I am delighted with this proposal even if it might be a little more inconvenient. N retrospect Cabal files form the basis of the package system so it is better to include them directly.

**Comment by snoyberg** [comment]
OK, I'm going to move ahead with this. Thanks for the responses all. Closing as the discussion is done, will be merged to `master` fairly soon.

**Comment by simonmichael** [comment]
Agreeing with gromakovsky that this can very often cause conflicts and pain when merging/cherry-picking/switching branches/trying different stack/hpack versions. I think it's worth changing hpack to fix this - if you agree, consider helping https://github.com/sol/hpack/issues/380.

**Comment by ulidtko** [comment]
Hi! Let me just describe one failure mode collateral from this change. Hopefully, it'll make searching for it easier and speed up resolutions. No response required.

First, the error message:
> 2020-07-30 10:18:19.050984: [error] Aeson exception:
> Error in $.packages[19].completed: failed to parse field 'packages': failed to parse field 'completed': Could not parse a UnresolvedPackageLocationImmutable from: Object (fromList [("size",Number 294200.0),("url",String "https://github.com/private-company/vendor-fork-redacted/archive/fcbaf261368b7f63708351fb1b04eb7f5f0793a3.tar.gz"),("name",String "vendor-fork-redacted"),("version",String "0.9.1"),("sha256",String "54974f6f9851376292cb6f081eef2cd907396899a04af5776da2d2cc45e80fc6"),("pantry-tree",Object (fromList [("size",Number 5039.0),("sha256",String "bc3f1c77c2797f0d0915f5ffff38d5e3cf8cdc613507fe1ace9463bc2492aafc")]))])

Now the cause. In my case, local-development Stack v2.3.1 has produced unintended change to `stack.yaml.lock` which wasn't understood by Stack v2.1.3 on CI:
```diff
@@ -154,9 +140,6 @@ packages:
 - completed:
     size: 294200
     url: https://github.com/private-company/vendor-fork-redacted/archive/fcbaf261368b7f63708351fb1b04eb7f5f0793a3.tar.gz
-    cabal-file:
-      size: 4079
-      sha256: a24d964776e360d0545500c8b28ec254aa323fdf28fa55692a282a25b6ac652c
     name: vendor-fork-redacted
     version: 0.9.1
     sha256: 54974f6f9851376292cb6f081eef2cd907396899a04af5776da2d2cc45e80fc6
```

Reverting this unintended change fixes the error (as well as updating Stack on CI).

The error reporting could perhaps be better; but this behavior change is well-documented on the [ChangeLog](https://docs.haskellstack.org/en/stable/ChangeLog/). Hope that helps

**Comment by robertmassaioli** [comment]
@snoyberg I don't think that this proposal works with`pvp-bounds` yet. My "case-in-point" is the https://github.com/dzhus/snaplet-redis repository that has not commited the `.cabal` file AND uses `pvp-bounds: upper`. If I were to commit the generated cabal file for that repository then we would have a cabal file comitted that is completely different from the cabal file that gets published to Hackage. In terms of reproducability, I think that is a large issue, it means that the same source code, accessed different ways, could give you different results.

Ideally, the `stack build` command would perform the pvp-bounds logic in the generated cabal file so that we could commit an accurate cabal file. Ping @dzhus

**Comment by dzhus** [comment]
> Ideally, the stack build command would perform the pvp-bounds logic in the generated cabal file so that we could commit an accurate cabal file

Yeah in the world where you commit .cabal files I'm not sure I see the utility of `--pvp-bounds` being used only for `sdist`, if (any) file is generated by tooling it should generated once per immutable and reproducible version of the project, not modified via a conveyor belt of commands.

On a side note, reading up on this very proposal (that I was not aware of):

> people using build tools without hpack support are still out of luck with these repos.

In my view that's an issue of individual workflow, not projects or ecosystem as a whole. Just like using chains of `git:` dependencies is just a choice to organise one's workflow (where as I understand the issue of "generating .cabal-s for deps become prohibitively expensive" comes from), the utility of which is slowly fading as CI resources become cheaper. As such I hope that this remains a recommendation, as the choice to commit .cabal files or not doesn't affect whether a library can be pushed to Hackage / included in Stackage.

**Comment by Javran** [comment]
Should this issue be revisited? The decision was made allowing only 4 days and with only a handful of votes - I'm not convinced that this represents a majority of users.

The blogpost says more about implementation details that I'm relunctant to dive deep (my apologies if any of my concerns below has been addressed in the blogpost), but from user's point of view, why I have to suffer this deprecation notice which is not even my fault? If reproducibility is the concern, I don't see `git+commit` doing any worse than package with digest. If space is the concern, yes hpack is an extra dependency, but does this really matter when `~/.stack` usually accumlates to two digit gigabytes?

In addition, the reason why I choose `git+commit` over package with digest is because the dependency is under development and resides under a different repo, for fast prototyping that requires modifying both main project and dependency library, it's counterproductive to go through this `cabal sdist`-then-update route as suggested alternative in the blogpost. Sure when it comes releases I'll make sure it ships with a cabal file, but I don't see the reason to check in a generated file for **source** version control.

A potential workaround I can think of for now is to have both main project and library reside under the same repo, this might not be applicable to all use cases, unfortunately.
