### ISSUE TITLE
stack build always reconfigures the package

### ISSUE THREAD

**Issue by ezyang** [commercialhaskell/stack#541]
When running `stack build` on `Cabal`, it always seems to configure before building. Intentional?

**Comment by snoyberg** [comment]
I'm not able to reproduce. What evidence are you seeing of it reconfiguring?

Note that `stack build` may be quite suboptimal for the `Cabal` library case because it's going to use `runghc` on `Setup.hs`, resulting in the Cabal library being interpreted from scratch each time. It works, but may be annoyingly slow.

**Comment by ezyang** [comment]
I guess I'm observing that when I `stack build` and `stack test`, It has to reconfigure. But I thought this was fixed? This is Stack 0.1.2.0.

**Comment by snoyberg** [comment]
Well, yes, but that's a Cabal limitation ;). When you switch between `stack build` and `stack test`, it has to switch the options to `--enable-tests` and back.

**Comment by ezyang** [comment]
OK, I guess I'll close this for now then.

**Comment by snoyberg** [comment]
Just taking a guess about what you actually want: does `stack test --no-run-tests` help you out at all? Or `stack test Cabal:lib`?

**Comment by ezyang** [comment]
`stack test --no-run-tests` is helpful. A bit of trouble is that stack test doesn't actually work with Cabal https://github.com/haskell/cabal/issues/2711 . So I guess I can use `stack test --no-run-tests` to build the test executables and then run it manually with the right dist dir
