### ISSUE TITLE
Fail to build gi-gtk on Windows

### ISSUE THREAD

**Issue by jokusi** [commercialhaskell/stack#5423]
Since all posts and comments in issue #3619 get ignored, I repost the bug here.

When compiling `gi-gtk` on Windows with `stack` I get the following error:
```
** (process:14012): WARNING **: 17:21:48.726: Failed to load shared library 'libcairo-gobject-2.dll' referenced by the typelib: 'libcairo-gobject-2.dll': The specified procedure could not be found.
Could not resolve symbol "cairo_gobject_context_get_type" in namespace "cairo-1.0"
CallStack (from HasCallStack):
  error, called at lib\\Data\\GI\\CodeGen\\LibGIRepository.hs:188:16 in haskell-gi-0.23.1-Ip2HIAnJpNoJ01fWNpYQph:Data.GI.CodeGen.LibGIRepository
```

> The problem seems to be stack only. [This](https://github.com/haskell-gi/haskell-gi/issues/234) thread suggests it works on cabal. It links to issue #4886, where we can find a "solution" which actually works (at least for me), but that solution is more of a workarround then an acceptable actual solution. It might even cause other problems. I guess there is a reason for the different zlibs?

Issue #3619 and #4886 should be marked as duplicates.

**Comment by mpilgrem** [comment]
I think that is caused by a copy of `zlib1.dll` on the path which is used in the stack environment being not the most up to date version of the `.dll`. The version that ships with GHC is not up to date.

`stack exec -- where.exe zlib1.dll` (assuming PowerShell) will list the locations of `zlib1.dll`. On my PC it yields (for example):
~~~
C:\Users\mikep\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.5\mingw\bin\zlib1.dll
C:\msys64\mingw64\bin\zlib1.dll
~~~
The solution is to copy the MSYS2 version of `zlib1.dll` (which is up to date) into the GHC folder.
