### ISSUE TITLE
Confusing error message when requested version of a package is not found

### ISSUE THREAD

**Issue by jforberg** [commercialhaskell/stack#5468]
### General summary/comments

When given a version constraint on the command line, stack install sometimes confusingly reports that packages cannot be found, when in fact it is only a specific version of a package that is missing.

### Steps to reproduce

```
$ stack install cabal-install-3.0.0.1    # NB this version of cabal-install does not exist

Error: While constructing the build plan, the following exceptions were encountered:

Unknown package: cabal-install
```

**Interestingly, if I add any version of cabal-install to my extra-deps then bug #5467 is triggered instead**

### Expected

Error message to say that the requested version of cabal-install was not found. Alternatively, say that cabal-install-3.0.0.1 was not found. Alternatively, say that the version contraint for cabal-install could not be satisfied.

### Actual

Error message implies that cabal-install does not exist at all.

### Stack version

Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mpilgrem** [comment]
Investigating, with Stack 2.9.3, `stack build cabal-install-3.0.0.1 --dry-run` (with snapshot LTS-20.18) results in `cabal-install-3.6.2.0` being built. Why? From `Stack.Build.Target.resolveRawTarget` (`go (RTPackageIdentifier ident@(PackageIdentifier name version))`), `cabal-install` is in the package index (Hackage) but there is no latest revision for `cabal-install-3.0.0.1`, so the fall back is to `cabal-install`, which is in the snapshot. 

The fall back (`deferToConstructPlan`) has this code comment:
~~~haskell
-- This is actually an error case. We _could_ pure a Left value here, but it
-- turns out to be better to defer this until the ConstructPlan phase, and let
-- it complain about the missing package so that we get more errors together,
-- plus the fancy colored output from that module.
~~~

At the very least, the online documentation needs to be corrected.
