### ISSUE TITLE
Docker builds don't work on LTS 17

### ISSUE THREAD

**Issue by koterpillar** [commercialhaskell/stack#5489]
### General summary/comments (optional)

`stack --docker` cannot find the Docker image for LTS 17.

### Steps to reproduce

1. Create a new Stack project:

```shell
stack new test-docker
cd test-docker
```

2. Edit `stack.yaml` to say:

```yaml
resolver: lts-17.4
packages:
- .
```

3. Run:

```shell
stack --docker build
```

### Expected

Dockerized build of a fresh package.

### Actual

`fpco/stack-build:lts-17.4` Docker image is not found, and the build errors.

### Stack version

```
$ stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by TravisCardwell** [comment]
I saw this issue before creating #5592 but assumed that it was a different issue because an `lts-17.4` image is available at [fpco/stack-build](https://hub.docker.com/r/fpco/stack-build).  I have since noticed that the image was pushed on April 1st while this issue was created on February 20th...  Perhaps it is the same issue after all!

Note that #5592 has a workaround.

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time.
