### ISSUE TITLE
Use a git worktree for GHC

### ISSUE THREAD

**Issue by gergoerdi** [commercialhaskell/stack#5500]
We can use GHC from Git using the following `stack.yaml` syntax:

    compiler: ghc-git-0dc7985663efa1739aafb480759e2e2e7fca2a36-quick

This seems to do its own cloning into some directory in /tmp. However, if I already have a GHC checkout somewhere, I would like the ability to point Stack at it, so that it can just make a new temporary [worktree](https://git-scm.com/docs/git-worktree) without having to download everything again. This would also make it very simple to use commits that are not pushed to upstream GHC yet.

**Comment by hsyl20** [comment]
Is this feature still working? I thought it would have been broken after building script changes in upstream GHC...

You should be able to use a local git repository with the following in `stack.yaml`:

```
compiler-repository: /path/to/my/ghc/repo
# OPTIONAL. Default compiler repository is "https://gitlab.haskell.org/ghc/ghc"
```

It still clones but it should be a bit faster. Sadly we can't avoid cloning at least some stuff because upstream uses submodules. It's a daily pain point for GHC devs as every worktree uses its own copy of the submodules...
