### ISSUE TITLE
`stack haddock --open <package>` attempts to open `wine` on a linux machine

### ISSUE THREAD

**Issue by marchgithub** [commercialhaskell/stack#5637]
### Steps to reproduce

1. Run `stack haddock --open <package>`

### Expected

Documentation opens in `$BROWSER`, with as little console output as possible.

### Actual

Documentation opens in `$BROWSER`, but stack also attempts to open wine. See last line in console output.

```
$ stack haddock --open scalpel
Haddock index for snapshot packages already up to date at:
/home/user/.stack/snapshots/x86_64-linux-tinfo6/f5d6deea78f924744a20cf77af36bb5d8f31b8ca62b28d27cfb6d8a92094f676/8.6.5/doc/index.html
Opening /home/user/.stack/snapshots/x86_64-linux-tinfo6/f5d6deea78f924744a20cf77af36bb5d8f31b8ca62b28d27cfb6d8a92094f676/8.6.5/doc/scalpel-0.6.0/index.html in the browser.
/usr/bin/env: ‘wine’: No such file or directory
```

### Stack version

```
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

**Comment by qrilka** [comment]
@marchgithub Stack uses https://hackage.haskell.org/package/open-browser for opening a browser - would you mind testing if the same happens when you just use `openBrowser` from that package? On Linux it should run XDG handler for html files - https://github.com/rightfold/open-browser/blob/master/lib/Web/Browser/Linux.hs#L10 - probably you have `wine` registered as a such?

**Comment by marchgithub** [comment]
Is there a way to import a remote package into `stack ghci`?
