### ISSUE TITLE
Can't have `extra-deps` inside the global config

### ISSUE THREAD

**Issue by effectfully** [commercialhaskell/stack#5650]
The docs [make it seem](https://docs.haskellstack.org/en/latest/yaml_configuration/#global-packages) like I can use `extra-deps` within a global `config.yaml` file. However when I do that via

```
extra-deps:
- git: https://github.com/coot/ghc-tags-plugin
  commit: 6ff8d8d0b539eef747f9a4dc109380aea3052ed7
```

I get this:

```
Warning: /etc/stack/config.yaml: Unrecognized field in ConfigMonoid: extra-deps
```

Other global options work alright. So are the docs wrong or am I doing something wrong?

My use case is making `stack repl` invoke the [`ghc-tags-plugin`](https://hackage.haskell.org/package/ghc-tags-plugin) whenever `stack build` is called, so this is why I want this global dependency. Is is possible to achieve that?

### Stack version

```
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mpilgrem** [comment]
The online documentation may well have moved on since this was raised. It currently makes clear that `extra-deps` is a project-specific option that can only be included in a project-level configuration file (`stack.yaml`): https://docs.haskellstack.org/en/stable/yaml_configuration/#extra-deps.

If `stack repl` is being run outside of a project directory, then it will look to the `stack.yaml` file in the `global-project` directory of the Stack root for its project-level configuration (including `extra-deps`).
