### ISSUE TITLE
stack setup fails if make is not GNU make

### ISSUE THREAD

**Issue by mwm** [commercialhaskell/stack#566]
Since GHC requires GNU make to install, there needs to be a way to tell stack the name of the program so that  "stack setup" has at least a chance of working. Not sure if that's also true for other programs in the GHC build system.

**Comment by snoyberg** [comment]
Perhaps we should just change the program name in stack. I can't see a
downside to that. Can you send a PR?

**Comment by mwm** [comment]
I don't know what you mean by "send a PR". Do you want mail to support or bugreport@fpcomplete.com? Something else?

**Comment by snoyberg** [comment]
I meant a "pull request." This would entail changing the codebase to have the desired change, pushing to a fork on Github, and clicking the "pull request" button. The reason for doing it this way is that you'll be able to test the changes on your machine directly, instead of going through a much longer iteration cycle of someone else trying to make the necessary change and then seeing if it fixes things for you. Since this should just be a one-line change in src/Stack/Setup.hs, it should hopefully be pretty simple.

**Comment by mwm** [comment]
I don't think this is a one-line change. The name of the make program needs to be settable by the user, or at least set on a system basis. I'm not sure how the latter would be done. Adding an option to the setup command would do the former. The simplest change is probably checking an environment variable, but that doesn't seem very user-friendly.

**Comment by phadej** [comment]
in https://github.com/commercialhaskell/stack/blob/master/src/Stack/Setup.hs#L566 the `tar` and `make` commands are hard-coded. We could have global `--with-make` `--with-tar` `--with-git` options. And have specialised version of `readInNull` which takes `ExternalProgram`, not a `String`. Does this sound ok to @snoyberg ?

 I don't know if there are other external programs used, which stack doesn't install.

**Comment by manny-fp** [comment]
Perhaps if `gmake` exists then it should be used by default, otherwise fallback to `make`?

**Comment by phadej** [comment]
@manny-fp I had that in mind too. Will it be enough for @mwm?

**Comment by mwm** [comment]
Just preferring gmake to make would certainly work for me, but it seems less than optimal.

**Comment by snoyberg** [comment]
@phadej's changes are now on master (thank you!), closing.
