### ISSUE TITLE
stack ignores STACK_ROOT and --stack-root

### ISSUE THREAD

**Issue by mnn** [commercialhaskell/stack#5664]
### Steps to reproduce

0. Freshly install stack
1. Set `STACK_ROOT` or pass `--stack-root`
2. run stack which proceeds to use some directory in a user directory instead

### Expected

Stack uses given directory as docs say:

> Among other things, this is where stack stores downloaded programs and snapshot packages. This location can be configured by setting the STACK_ROOT environment variable or passing the --stack-root commandline option.

### Actual

<img width="469" alt="2022-01-03_20-01" src="https://user-images.githubusercontent.com/1975567/147969252-92c3de34-e632-4748-a52e-833bc94fa498.png">

### Stack version

2.7.3

### Method of installation

* Official binary - the Windows installer

**Comment by mattaudesse** [comment]
Hi @mnn - I think this is actually the expected behavior (but could possibly be better documented - PRs welcome):

https://docs.haskellstack.org/en/stable/faq/#can-i-change-stacks-default-temporary-directory
> **Can I change stack's default temporary directory?**
>
> Stack downloads and extracts files to $STACK_ROOT/programs on most platforms, which defaults to ~/.stack/programs. On Windows $LOCALAPPDATA\Programs\stack is used. If there is not enough free space in this directory, Stack may fail. For instance, stack setup with a GHC installation requires roughly 1GB free. If this is an issue, **you can set local-programs-path in your ~/.stack/config.yaml** to a directory on a file system with more free space.

https://github.com/commercialhaskell/stack/blob/69f55d401d8ef719d255b7876884899fbfcd546e/src/Stack/Config.hs#L456-L471
https://github.com/commercialhaskell/stack/blob/69f55d401d8ef719d255b7876884899fbfcd546e/src/Stack/Config.hs#L281-L283
