### ISSUE TITLE
`drop-packages: Cabal` is silently ignored

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/stack#5707]
Entry 
```yaml
drop-packages: 
- Cabal
``` 
in `stack.yaml` seems to be silently ignored.
So working around
- #5706 

according to the recipe in
- #5679 

fails.

**Comment by mpilgrem** [comment]
I think that `stack` may not be ignoring `drop-packages: - Cabal`; I think that recent resolvers do not include `Cabal` to start with - so that it is the version of `Cabal` that ships with the version of GHC that is relevant. See https://github.com/commercialhaskell/stackage/issues/4425#issuecomment-602321624 (from March 2020).

**Comment by mpilgrem** [comment]
With my investigation above and the updating of the documentation, I am going to close this issue.

**Comment by andreasabel** [comment]
Thanks for the explanation, @mpilgrem !
