### ISSUE TITLE
Allow `stack build --resolver ...` without `stack.yaml` file

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/stack#5830]
It would be natural if I could type e.g. `stack build --resolver nightly-2022-08-17` in a directory that has a `.cabal` file, and this would behave like `(echo "resolver: nightly-2022-08-17" > stack.yaml); stack build`.  Having to commit a `stack.yaml` to disk always irritates me, and its necessity isn't apparent to me. 

A standard workaround is to have `stack-XXX.yaml` files for specifying resolver `XXX`, and then use `stack build --stack-yaml stack-XXX.yaml`.  But here, the same critique applies: Why having to commit to disk?  I see my project roots getting cluttered with tons of `stack-XXX.yaml` files...

**Comment by mpilgrem** [comment]
The current behaviour, if a project-level configuration file (`stack.yaml`) is 'missing' from the current working directory, is that Stack checks the parent directory and so on, checking the `global-project` directory in the Stack root in the last resort. This proposed behaviour would be to take the presence of a Cabal file (or, presumably, a `package.yaml` file, if it had not yet been used to create a Cabal file) in the working directory as a 'flag' that the 'missing' `stack.yaml` was intentional and Stack's project-specific configuration was to be assumed based on the CLI alone.

My concern is a user who has a multi-package local project that looks something like this:
~~~
\my-project
  \my-package1
    my-package1.cabal
    [other files]
  \my-package2
    my-package2.cabal
    [other files]
stack.yaml
~~~

Currently, if they happen to be working down in directory `my-package1` and they command `stack build` the project builds as intended, as Stack will find the `stack.yaml`. With your proposal, they would have change directory to the `my-project` directory before they could command `stack build`.

It is a question of the balance of different conveniences. Are single-package projects that involve no `extra-deps` really that common (even given the coverage of modern Stackage snapshots)?

**Comment by andreasabel** [comment]
Thanks for the triage!

Alternatively, one could ask explicitly for "no stack.yaml" via option `--stack-yaml -`; (I wasn't aware of the upward search).

> Are single-package projects that involve no `extra-deps` really that common ...?

I am looking a small, unpublished projects, maybe even throw-away projects.  For these, this would be convenient.

**Comment by juhp** [comment]
(This reminded me that I also wish one could just specify a resolver major version in `stack.yaml` files: so I opened #5838.)
