### ISSUE TITLE
Integration tests not actioning 'download Linux-ARM64 artifact' or 'hash and sign assets'

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#5868]
@jsoref, unfortunately, when I pushed a tag for the v2.9.1 release, the workflow did not 'download Linux-ARM64 artifact' or 'hash and sign assets'. So, I've deleted that tag and will investigate.

It seems that conditions:

~~~yaml
if: contains(needs.configuration.outputs.runners, 'arm64')
~~~

and

~~~yaml
 if: needs.configuration.outputs.can-sign
~~~

are not being met. I think I see the problem with the first and will open a pull request. I am not sure why the second is not working. Perhaps it needs a more explicit test.

**Comment by jsoref** [comment]
Hmm...
https://github.com/check-spelling/stack/actions/runs/3079579488/jobs/4975983933

I have the following

#### Repository secrets

_Secret_|_Updated_
-|-
`ACTIONS_RUNNER_DEBUG`|Updated 5 minutes ago
`ACTIONS_STEP_DEBUG`|Updated 5 minutes ago
`RELEASE_SIGNING_KEY`|Updated 5 minutes ago

I set `RELEASE_SIGNING_KEY` with some random characters which enables the can_sign criteria, and the output appears in the last thing `Complete job`:

```
##[debug]Starting: Complete job
Evaluate and set job outputs
##[debug]Evaluating: steps.runners.outputs.arm64
##[debug]Evaluating Index:
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating steps:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'runners'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'outputs'
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'arm64'
##[debug]=> '''ubuntu-latest'''
##[debug]Result: '''ubuntu-latest'''
##[debug]Evaluating: env.CAN_SIGN
##[debug]Evaluating Index:
##[debug]..Evaluating env:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'CAN_SIGN'
##[debug]=> 'true'
##[debug]Result: 'true'
##[debug]Evaluating: steps.runners.outputs.test-arm64
##[debug]Evaluating Index:
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating steps:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'runners'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'outputs'
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'test-arm64'
##[debug]=> 'false'
##[debug]Result: 'false'
Set output 'arm64-runner'
Set output 'can-sign'
Set output 'test-arm64'
Uploading runner diagnostic logs
##[debug]Starting diagnostic file upload.
##[debug]Setting up diagnostic log folders.
##[debug]Creating diagnostic log files folder.
##[debug]Copying 1 worker diagnostic logs.
##[debug]Copying 1 runner diagnostic logs.
##[debug]Zipping diagnostic files.
##[debug]Uploading diagnostic metadata file.
##[debug]Diagnostic file upload complete.
Completed runner diagnostic log upload
Cleaning up orphan processes
##[debug]Finishing: Complete job
```

So, I'm fairly certain that `can-sign` has `'true'` -- that said, checking explicitly against == `'true'` instead of treating it as a boolean is probably a good idea.

I probably shouldn't have picked `contains()`, it's the fancy GitHub-ish method and would enable one to reuse the field for multiple items, but simple booleans are probably a better approach (and are hard enough...)
