### ISSUE TITLE
I have problems installing package with stack

### ISSUE THREAD

**Issue by DanielBurgaard** [commercialhaskell/stack#6018]
See https://stackoverflow.com/questions/74888599/how-do-i-install-and-run-test-tasty-patterns

When I try to give a relative path as argument I get the following such as:

```
PS D:\CurDir>stack install Test.Tasty.Patterns.Parser --stack-yaml stack.yaml
Error: [S-8506]
Error parsing targets: Directory not found: Test.Tasty.Patterns.Parser```

**Comment by mpilgrem** [comment]
@DanielBurgaard, from your question, I understand you are new to Haskell and Stack and are learning to use Stack. I have two pieces of general advice. First, you are likely to get a better response for this sort of query if you post in the 'Learn' category of the [Haskell Community](https://discourse.haskell.org/). Second, if you have not done so, you should work through Stack's [introductory user guide](https://docs.haskellstack.org/en/stable/GUIDE/), which has a tutorial-like approach. If problems using Stack are introduced by reference to parts of the guide, then I can work out what might be changed to help both you and others.

In respect of your specific problem. `stack install` means the same thing as `stack build --copy-bins`, which is explained here: https://docs.haskellstack.org/en/stable/build_command/. The syntax for `stack build` targets is explained here: https://docs.haskellstack.org/en/stable/build_command/#target-syntax.

A 'target' is a package, a package identifier (a specific version of a package), a package component, or a directory containing packages. `Test.Tasty.Patterns.Parser` is none of those - it is the name of a 'module' exposed by the `testy-1.4.3` package and, more specifically, exposed by the library component of that package: https://hackage.haskell.org/package/tasty-1.4.3/tasty.cabal.

Here, because `Test.Tasty.Patterns.Parser` is not in the format of a package, a package identifier or a package component but could possibly be a directory, Stack is complaining that there is no directory named `Test.Tasty.Patterns.Parser`.

The `--copy-bins` flag of `stack build` (`stack install`) means 'copy built executables to a specified location'. The `testy` package has no executable components - only a library - so it will not make sense to 'install' it.

If you want to use the `testy` library, you need to write a piece of Haskell code that depends on that package and makes use of the functions, types etc exported by its exposed modules.

Alternatively, you can make use of a REPL environment: https://docs.haskellstack.org/en/stable/ghci/ and use `stack repl` or `stack ghci` (they mean the same thing). You can load individual modules into that environment. However, that is too long a topic to discuss sensibly here. The starting point is to read GHC's guide to GHCi: https://downloads.haskell.org/ghc/latest/docs/users_guide/ghci.html to understand the environment itself.
