### ISSUE TITLE
`stack exec` does not respect spaces in command arguments

### ISSUE THREAD

**Issue by anihm136** [commercialhaskell/stack#6118]
### General summary/comments
It appears that arguments passed to the `stack exec` command (i.e, `stack exec cmd -- argument1 argument2`) cannot contain spaces - any argument with spaces is split into multiple arguments, thus changing the command and causing errors.

### Steps to reproduce
1. Run command `stack exec ghc -- -e 'interact (unlines.map reverse.lines)'`

### Expected

An interactive session should begin, reversing strings input on the terminal

### Actual

~~~text
stack exec ghc -- -e 'interact (unlines.map reverse.lines)'

Warning: ignoring unrecognised input `(unlines.map'
Warning: ignoring unrecognised input `reverse.lines)'

<interactive>:0:1: error:
    • No instance for (Show ((String -> String) -> IO ()))
        arising from a use of ‘print’
        (maybe you haven't applied a function to enough arguments?)
    • In a stmt of an interactive GHCi command: print it

~~~

### Stack version

~~~text
stack --version
Version 2.9.3, Git revision 6cf638947a863f49857f9cfbf72a38a48b183e7e x86_64 hpack-0.35.1
~~~

### Method of installation

* An unofficial package repository - ASDF VM

### Platform

`Linux 6.3.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC x86_64 GNU/Linux`

**Comment by mpilgrem** [comment]
@anihm136, thanks for reporting. I can't reproduce this on Windows (PowerShell), all of the following behave as expected:
~~~text
stack exec ghc -- -e 'interact (unlines.map reverse.lines)'
stack exec -- ghc -e 'interact (unlines.map reverse.lines)'
stack exec ghc -- -e "interact (unlines.map reverse.lines)"
stack exec -- ghc -e "interact (unlines.map reverse.lines)"
~~~

On your system, is it just single quotation marks that are not being respected or is it also double quotation marks?

My hypothesis is that something must be going wrong with the `base` package's `System.Environment.getArgs :: IO [String]`, because that is the foundation that the `optparse-applicative' package (which Stack uses) is built on.

If you try a small test program (lets call it `argsTest`), such as:
~~~haskell
module Main (main) where

import System.Environment (getArgs)

main :: IO ()
main = getArgs >>= print
~~~

How does the command line get analysed into arguments? On my machine:
~~~text
> stack exec -- argsTest stack exec ghc -- -e 'interact (unlines.map reverse.lines)'
["stack","exec","ghc","--","-e","interact (unlines.map reverse.lines)"]
~~~

You can see from the output that the single quotation marks on the command line are being respected.

**Comment by anihm136** [comment]
@mpilgrem thanks for the test program! It helped me discover that the issue was indeed not with stack. My non-standard install had created a shim shell script, and the script was being executed instead of the actual executable. The error was occuring due to incorrect parameter expansion in the script. A small change in it (prompted by ShellCheck) fixed the error. Thanks again, and apologies for the false alarm!
