### ISSUE TITLE
Unable to save CompilerPaths cache on Windows

### ISSUE THREAD

**Issue by zeyonaut** [commercialhaskell/stack#6155]
### General summary/comments

After installing Stack for the first time on Windows and creating a new project, calling `stack run` results in the following warning:

```
stack run

Warning: Unable to save CompilerPaths cache:

         C:\ghcup\ghc\9.2.8\bin\ghc: getPermissions:CreateFile "\\\\?\\C:\\ghcup\\ghc\\9.2.8\\bin\\ghc": does not exist (The system cannot find the file specified.)
```

### Steps to reproduce

1. Run `stack new`: `stack new <project>`.
2. `cd <project>`.
3. Run `stack run`.

### Expected

No warning should occur.

### Actual

~~~text
stack run --verbose
...
2023-06-16 18:03:18.702591: [warn] 
Warning: Unable to save CompilerPaths cache:

         C:\ghcup\ghc\9.2.8\bin\ghc: getPermissions:CreateFile "\\\\?\\C:\\ghcup\\ghc\\9.2.8\\bin\\ghc": does not exist (The system cannot find the file specified.)
...
~~~

### Stack version

~~~text
stack --version
Version 2.11.1, Git revision c1167a6abc3f4978ccded5ba0246a57387da0e2f x86_64 hpack-0.35.2
~~~

### Method of installation

* Official binary, downloaded via haskellstack.org (`stack-2.11.1-windows-x86_64-installer.exe`)

### Platform

Windows 10 Home, Version 22H2, OS build 19045.2965.
64-bit operating system, x64-based processor.

**Comment by mpilgrem** [comment]
The `ghcup` in the path in the warning message makes me wonder if, somehow, a GHCup script to manage GHC has got into the Stack root - see https://docs.haskellstack.org/en/stable/yaml_configuration/#ghc-installation-customisation. The Stack root is at `stack path --stack-root` (default is `C:\sr`). For a fresh install of Stack, you can safely delete the Stack root; Stack will re-build everything that it needs there.

On the other hand, if you want to use GHCup, I would use it consistently. That is, use it to get/upgrade Stack and use it to manage versions of GHC (rather than let Stack do the management).

**Comment by zeyonaut** [comment]
I ran the first line, and got this result:

```powershell
> stack path --stack-root | cd

Warning: Unable to save CompilerPaths cache:

         C:\ghcup\ghc\9.2.8\bin\ghc: getPermissions:CreateFile "\\\\?\\C:\\ghcup\\ghc\\9.2.8\\bin\\ghc": does not exist (The system cannot find the file specified.)

Warning: Unable to save CompilerPaths cache:

         C:\ghcup\ghc\9.2.8\bin\ghc: getPermissions:CreateFile "\\\\?\\C:\\ghcup\\ghc\\9.2.8\\bin\\ghc": does not exist (The system cannot find the file specified.)
```

But I think you're right - I deleted `C:\sr` and reinstalled Stack, and the warning no longer appears. I should also note that the Stack installer nukes the User Path variable, so Windows users should take care to back up their User Path before running the installer. Thanks for the help!

**Comment by mpilgrem** [comment]
I am pretty sure the Stack installer on Windows is not _intended_ to nuke the `PATH` variable - something else to look into ...
