### ISSUE TITLE
Support non-relative STACK_WORK directory

### ISSUE THREAD

**Issue by bakhtiyarneyman** [commercialhaskell/stack#6191]
The fact that STACK_WORK can only be relative creates problems when building from read-only filesystems, or filesystems that are being frequently snapshotted and backed up.

**Comment by hasufell** [comment]
This might be a security feature to not support absolute paths. E.g. you can't do reasonable cleanups if someone does `STACK_WORK=$HOME`.

Although I'm not sure stack does any cleanups?

**Comment by hasufell** [comment]
As workaround, you can always use bind mounts or a symlink and set `STACK_WORK` to a subdirectory of those.

**Comment by mpilgrem** [comment]
I'm closing this as it duplicates #6135 and I'm keen to reduce Stack's open issues count.

At the moment, Stack creates a working directory for each local/mutable package and, if different, the project directory. My assumption is that is because the contents are package or project-specific, but I would need to check.

If you are building against (local) immutable packages, perhaps they would be better specified as extra deps rather than as 'packages'? https://docs.haskellstack.org/en/stable/pantry/#local-or-remote-archives-such-as-github-archives

As regards cleanup, I think Stack only does that on request. `stack purge` (`stack clean --full`) deletes all of a project's working directories.

**Comment by andreasabel** [comment]
@mpilgrem : From the outside this issue looks "fixed" because "closed as completed".  Would be clearer if it was "closed as not planned" (which includes "duplicate" in its semantics).
