### ISSUE TITLE
what does ' classy-prelude-yesod needed, but the Stack configuration has no specified version (latest matching version is 1.5.0)' mean?

### ISSUE THREAD

**Issue by KeesBleijenberg** [commercialhaskell/stack#6245]
I' am using a stack project with LTS 16/31 (ghc 8.8.4). Suddenly I got the message Prelude.chr: bad argument: 3179719811. In the past I removed .stack and then I rebuild with  stack build. That solved the problem. But not now. I can't find a real solution so I am stuck. 

Therefor I tried to upgrade to LTS 17.10. But I got this error:

  Stack failed to construct a build plan.
       
       While constructing the build plan, Stack encountered the following errors:
       
       In the dependencies for adressen-0.0.0:
           classy-prelude-yesod needed, but the Stack configuration has no specified version (latest matching version is 1.5.0)

What does this message mean? Why is this a problem in 17/0 and not in 16/31? 
Do I have to specify the version of classy-prelude-yesod in package.yaml? I thought in a stack LTS all packages work fine together. 
During the life time of the project I've stripped more and more version numbers of the package names in package.yaml. Is that the cause of this problem?

**Comment by mpilgrem** [comment]
@KeesBleijenberg, Stack's message is a little terse - that is fixed in Stack 2.13.0.1 (see https://discourse.haskell.org/t/ann-first-release-candidate-for-stack-2-13-1/7606 for Stack 2.13.0.1).

The 'Stack configuration' refers to the `stack.yaml` file for your project. If you have specified snapshot (resolver) `lts-17.10`, then you can see that it does not include any version of `classy-prelude-yesod` - https://www.stackage.org/lts-17.10. So, you have to use an extra-dep to include a version in the set of packages.

`lts-16.31` did include `classy-prelude-yesod-1.5.0` - https://www.stackage.org/lts-16.31.

You could try:
~~~yaml
extra-deps:
- classy-prelude-yesod-1.5.0
~~~

**Comment by mpilgrem** [comment]
This commit: https://github.com/commercialhaskell/stackage/pull/6840/files (which brought it back in, in January 2023) gives an insight into why `classy-prelude-yesod` was removed. It depended on `yesod-static` which depended on `hjsmin` which required `text ==1.2.*`, but `text` had moved on.

**Comment by KeesBleijenberg** [comment]
Now I understand more how stack works. I changed to lts-20.22 and no error messages about classy-prelude-yesod anymore. 
Thanks!

**Comment by mpilgrem** [comment]
Glad to hear that - I'll close the issue.
