### ISSUE TITLE
Dynamically-linked Stack binaries for Termux and other non-FHS compliant environments

### ISSUE THREAD

**Issue by dhuux** [commercialhaskell/stack#6345]
i used `ghcup` to download `cabal` and `stack` on Termux. `cabal`  and `ghcup` can do network stuff with the patched glibc for Termux since they are dynamically linked.  but the `stack binary` is statically linked so it can't resolve DNS names because `/etc/resolv.conf` doesn't exist without proot in Termux. 

it would be nice if we had dynamically linked Linux AArch64 binaries also.

![Screenshot_20231123-193420_Termux](https://github.com/commercialhaskell/stack/assets/63465816/4b73177e-29dc-4d9d-a355-20908f15f9cd)

**Comment by philderbeast** [comment]
I'm looking for this option too. I see that Cabal has [executable-dynamic](https://cabal.readthedocs.io/en/stable/cabal-project.html#cfg-field-executable-dynamic) and this is used in the [clash-compiler/cabal.project](https://github.com/clash-lang/clash-compiler/blob/b242d0263585f7466f344ab8dc23da68526c7380/cabal.project#L56-L57), a project that I'm trying to build with stack.

```cabal
package clash-benchmark
  executable-dynamic: True
```

**Comment by philderbeast** [comment]
@dhuux it is possible to build stack from source with cabal.

**Comment by dhuux** [comment]
how? did you used it like this ` --enable-executable-dynamic`. i have just started my programming journey with Termux. i'm not used to building programs. hhh

**Comment by mpilgrem** [comment]
@dhuux, I am not a user of Cabal (the tool) or a Linux user, but if you have a working version of GHC 9.4.7 on your system, I think you can build Stack from source with Cabal (the tool) as follows:

1. Download the Stack project's source code from GitHub and change to the project's root directory.
2. Command `cabal update` to update the latest package list from Hackage.
3. Command `cabal build --with-compiler <path_to_ghc_9.4.7_executable_file>`. This will take a little while to complete, because there are about 176 direct and indirect dependencies and then 183 modules, but not so very long. The last step should tell you where Cabal has put the Stack executable. It can be moved anywhere.

**Comment by mpilgrem** [comment]
Stack's current release process has its origins in the discussion at #2534. There are no plans to provide dynamically-linked binary distributions from this repository, but if other parts of the Haskell community wish to support what you are looking for, we would try to support them in their support.

**Comment by dhuux** [comment]
@mpilgrem thanks.
