### ISSUE TITLE
Check the hash of a GHC tarball

### ISSUE THREAD

**Issue by nkaretnikov** [commercialhaskell/stack#637]

**Comment by DanBurton** [comment]
Will be implemented here-ish:

https://github.com/commercialhaskell/stack/blob/master/src/Stack/Setup.hs#L721

**Comment by DanBurton** [comment]
This task also involves adding information to the [stack-setup.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup.yaml) file.

For posterity, here's the little script I wrote to calculate the new `content-length` and `sha1` fields for each URL:

```
module Main where

import Data.String
import System.Environment
import Network.HTTP.Client.TLS
import Network.HTTP.Client
import Crypto.Hash
import qualified Data.ByteString.Lazy as LByteString

main :: IO ()
main = do
  [url] <- getArgs
  m <- newManager tlsManagerSettings
  lbs <- responseBody `fmap` httpLbs (fromString url) m
  let digest = hashlazy lbs
  putStr "content-length: "
  print (LByteString.length lbs)
  putStr "sha1: "
  print (digest :: Digest SHA1)
```

**Comment by DanBurton** [comment]
@snoyberg would you like to look over the commit before I close this issue? Should there be an integration test for this?

**Comment by snoyberg** [comment]
No integration test necessary, the existing tests should exercise this well enough. Only two concerns, neither of which are blockers:

* It may be worth considering making the SHA optional, specifically because of the next point
* I think SHA1 is a bad choice, and it should be SHA256 or SHA512. I expect this to change over time, thus the desire to make the absence of the correct type of SHA non-fatal.

**Comment by DanBurton** [comment]
Made the sha1 optional, with a `$logWarn` if absent. Later I'll write a script that modifies the .yaml file with the desired hash for each download; I'm not inclined to do it by hand again.

**Comment by snoyberg** [comment]
This is implemented, closing.
