### ISSUE TITLE
Window 10 CMD and Powershell: raw ANSI codes printed

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/stack#6408]
On Windows 10 (Education), in the Command Prompt and Powershell I am see raw ANSI codes.
```
> stack build foo --color=auto
←[0m
←[91mError:←[0m [S-4804]
       Stack failed to construct a build plan.
```
(Works correctly in the Git Bash.)
Same of course with `--color=always` or no `--color` option given.
Both CMD and PWSH say they are on code page 437.

> you are using the latest release (currently Stack 2.13.1).

Yes: 
Version 2.13.1, Git revision 8102bb8afce90fc954f48efae38b87f37cabc988 x86_64 hpack-0.36.0
Microsoft Windows [Version 10.0.19045.3930]

Previous instances of this problem:
- #4091 
- #3992 
- #3797

**Comment by hasufell** [comment]
ghcup does some magic here that is a rip-off of rust code.

Check: https://github.com/haskell/ghcup-hs/blob/55030d83da6d59196df28c0eb115cdf19ff20393/lib/GHCup/Prelude/Windows.hs#L31

**Comment by mpilgrem** [comment]
This is likely because `ansi-terminal-1.0` assumes that the de facto default terminal on Windows is now Microsoft's free Windows Terminal (which terminal emulator software I strongly recommend as a Windows user) and not ConHost. `ansi-terminal-1.0.1` will not make that assumption, and I will make a change in Stack 2.15.1 (coming soon) that will depend on `ansi-terminal-1.0.1`.
