### ISSUE TITLE
Allow Hpack used by Stack to overwrite a Cabal file it considers has been modified manually

### ISSUE THREAD

**Issue by evan0greenup** [commercialhaskell/stack#6521]
Make sure that you are using the latest release (currently Stack 2.15.3). See the
[upgrade instructions](http://docs.haskellstack.org/en/stable/install_and_upgrade/#upgrade)
to upgrade.

If there is `<package_name>.cabal` existed in the root directory of package, `stack` will automatically ignore `package.yaml`. when build, stack will convert `package.yaml` into `<package_name>.cabal` via `hpack`. 

When update `package.yaml`, the developer has to manually delete `<project_name>.cabal`. This is very inconvenient. It would be nice to make the generated cabal file as `<project_name>.generated.cabal`. So if there is only `<project_name>.generated.cabal`, `stack` will automatically overwrite `<project_name>.generated.cabal` from `package.yaml`. 

This feature can make developer completely forget about the cabal stuff, if he/her workflow is completely depend on `stack`.

**Comment by mpilgrem** [comment]
Hpack added `--force` in Hpack 0.20.0 (16 November 2017) because the original behaviour was to overwrite Cabal files and some Stack users found that confusing:
* https://github.com/commercialhaskell/stack/issues/3380
* https://github.com/commercialhaskell/stack/issues/3383
* https://github.com/sol/hpack/pull/215

However, it seems to me reasonable to have a Stack flag `--[no-]hpack-force` (configuration option `hpack-force: true`) that enables `--force` (disabled by default).

**Comment by mpilgrem** [comment]
@evan0greenup, if you are not using GHCup to manage versions of Stack, the above feature can be tested in `stack upgrade --source-only --git --git-branch fix6521`.

It can be used at the command line with `stack --hpack-force <command>` but the primary intention is that Stack would be configured in YAML files with `hpack-force: true`. I have kept the default as `hpack-force: false`, given the history discussed above.
