### ISSUE TITLE
Why do ghc binaries not go in `.local/bin`?

### ISSUE THREAD

**Issue by zeckalpha** [commercialhaskell/stack#656]
Globally installed binaries go in .local/bin except GHC and friends (which go in `.stack/programs/x86_64-linux/ghc-7.8.4/bin/`), from what I can tell. Is there are reason for this?

**Comment by manny-fp** [comment]
The intent of `stack setup`'s private GHC is to provide a GHC version for stack to use, not to install it for general use.  It needs to support multiple versions of GHC and ensure that the `ghc` (and related tools like `ghc-pkg`, `runghc`, `haddock`, etc) on the PATH is the correct version for the selected resolver, so installing in `~/.local` wouldn't be reliable since you could end up with one `ghc` overwriting another.

**Comment by snoyberg** [comment]
Looks like the question has been answered, and not seeing more activity. Closing.
