### ISSUE TITLE
stack rebuilds sublibraries that are not dependencies of the specified target

### ISSUE THREAD

**Issue by kostmo** [commercialhaskell/stack#6569]
Minimal testcase is here: https://github.com/kostmo/stack-sublibrary-rebuild

I am using `stack` version `2.15.5`.

# To reproduce the bug

1. Build the executable:
    ```
    stack build bug-repro:exe:bug-repro-exe
    ```
2. Then repeat to ensure all targets are up-to-date.
3. Insert a newline into `src2/Lib2.hs` and save
4. Re-run the above command to build the executable. Observe that files are rebuilt despite that the `lib2` sublibrary is not a dependency of `bug-repro-exe`.

## Equivalent cabal test

1. Build the executable:
    ```
    cabal build bug-repro:exe:bug-repro-exe
    ```
2. Then repeat to ensure all targets are up-to-date.
3. Insert a newline into `src2/Lib2.hs` and save
4. Re-run the above command to build the executable. Observe nothing is rebuilt; only `"Up to date"` is printed.

# Potentially related issues
* #6042
* #3486

**Comment by mpilgrem** [comment]
@kostmo, thanks for reporting and for taking the time to create a minimal example.

What you are experiencing is an example of an long-standing issue/feature request known as 'component-based builds'. The most recent open issue pulling that together is:

* https://github.com/commercialhaskell/stack/issues/6356

but there is a long history before that.

In short, Stack currently approaches building in terms of 'packages (with components)' rather than 'components (of packages)'.

I am going to close this issue - not because it is unimportant but because I am seeking to consolidate matters related to component-based builds under a single 'master' issue.
