### ISSUE TITLE
Will compiling different versions of the same package corrupt the database?

### ISSUE THREAD

**Issue by gelisam** [commercialhaskell/stack#672]
The [architecture](https://github.com/commercialhaskell/stack/wiki/Architecture#databases) page states:

> If different projects use different package indices, then their definitions of what package foo-1.2.3 are may be different, in which case they *can* corrupt each other's shared databases. This is warned about in the FAQ

I do not see anything on that subject in the FAQ. By any chance, was this fixed and removed from the FAQ, but not from the architecture page?

My [use case](https://github.com/gelisam/cabal-rangefinder/issues/2) is that I want to repeatedly ask stack to build the same package with different versions of its dependencies.

**Comment by gregwebs** [comment]
This use case is not what is mentioned in the FAQ. If this corrupts the database it would be a bug since it is a normal use case to add dependencies in extra-deps that changes the underlying dependencies of something in the database.

You can probably get better answers for questions on the mail list.
https://groups.google.com/forum/#!forum/haskell-stack
