### ISSUE TITLE
stack download for general Linux has overly long name and not permission to be executable

### ISSUE THREAD

**Issue by wolftune** [commercialhaskell/stack#709]
I just edited the wiki page https://github.com/commercialhaskell/stack/wiki/Downloads to clarify for now, but the download (such as needed for 32-bit Linux) has a long name (like stack-0.1.2…) instead of just "stack" and this means the terminal command has to be this long name. It should be just "stack" or at least people need to rename it to that.

Also, we had to mark the file as an executable manually.

At the very least, there needs to be instructions, but maybe easier way to do this automatically.

It works smoothly for the 64-bit installs via PPAs etc. just not for the general manual zip downloads.

**Comment by radix** [comment]
I guess packing it in a .tar.gz would be a bit more user-friendly, since it can 1) name the executable `stack`, 2) have the correct executable bits set on the file, and 3) perhaps even contain some README or whatever else...

**Comment by borsboom** [comment]
.gz files aren't archives and they don't have any kind of "table of contents" in them that indicates an original filename or permissions -- they're just plain compressed data.  The binaries on the Github release page aren't packages, they're there to make it easier to bootstrap without having to get a whole GHC/cabal-install toolchain first.  We recommend using the Apt/Yum repos when possible.  In addition, future versions of the Haskell Platform are likely going to include stack, and that'll probably end up being a common way to get it.

Thanks for updating the Downloads page.  For whatever reason, only the OS X section included that information before.

**Comment by chreekat** [comment]
Unfortunately, if the goal of the downloads is to make it easier to bootstrap, they aren't doing a very good job for OSX and generic/32-bit Linux. This is especially problematic since all current documentation points to [https://github.com/commercialhaskell/stack/wiki/Downloads] as *the* way to get stack.

OSX/Generic linux users have to do two twiddly extra steps to get running: change the filename and change the file permissions. I would rather see that done by the automated(?) process that generates these files. Is that code public?

**Comment by borsboom** [comment]
See #853.

**Comment by chreekat** [comment]
Perfect, thanks. :)
