### ISSUE TITLE
Provide `stack haddock --executables`

### ISSUE THREAD

**Issue by rimmington** [commercialhaskell/stack#729]
There doesn't seem to be an equivalent to `cabal haddock --executables`. One of our projects has significant executable-only code that it would be useful to generate Haddocks for.

As a workaround, you can [configure Cabal to use Stack DBs](https://www.reddit.com/r/haskell/comments/3bw95a/using_cabal_and_stack_together/csq3c41) and then `cabal haddock --executables`.

**Comment by borsboom** [comment]
Agreed, this would be nice to have.  A PR would be welcome, but if not forthcoming I hope to be able to get to this at some point myself.

**Comment by nd2s** [comment]
+1

**Comment by trskop** [comment]
:+1:

**Comment by Siprj** [comment]
:+1:

**Comment by jasonzoladz** [comment]
Pretty please :)

**Comment by ChristopherKing42** [comment]
http://stackoverflow.com/questions/32712775/generating-documentation-for-my-own-code-with-haddock-and-stack

**Comment by mgsloan** [comment]
Given the popularity of this issue, I took a look at implementing it.

I tried to use cabal, in order to see what it does to have haddock generate docs.  I immediately ran into https://github.com/haskell/cabal/issues/1919 even on the most trivial `stack new` project, with Cabal-1.22.7.0

Unfortunately, this seems to be an issue with Cabal the library, which we currently use for running haddock, so it also affects stack.  I'm not sure I want to expose such brokenness to people.

**Comment by cblp** [comment]
:+1:

**Comment by borsboom** [comment]
There are other good reasons to, as @mgsloan suggested, not use Cabal's implementation of building haddocks (e.g., then we wouldn't have to rebuild a package to build its haddocks), so I think that's definitely the way forward.

**Comment by fosskers** [comment]
I just hit this issue, expecting `stack haddock` to "just work" for executables. It's definitely handy for browsing the API of a executable monoliths backend.

**Comment by GildedHonour** [comment]
what's the status of this? and how to generate documentation for an executable?

**Comment by runeksvendsen** [comment]
It's worth noting that, if you develop your executables as tiny wrappers around a library -- with all the important stuff in the library -- then you have all the documentation in that library, and therefore no need to depend on Haddock to work for executables. The executable itself would literally just be `module Main where; import qualified SuperServer.App as App; main = App.main`), so there's nothing to document there, really.

**Comment by Tr1p0d** [comment]
👍

**Comment by dbaynard** [comment]
[Running haddock for tests would be good, too.](https://stackoverflow.com/questions/52278428/generating-haddock-for-test-modules-with-stack/52449958?noredirect=1#comment91891424_52449958)

**Comment by MuhammedZakir** [comment]
This issue [1] seems to fixed. Can this be supported in Stack now?

[1] https://github.com/haskell/cabal/issues/1919

**Comment by mpilgrem** [comment]
Stack > 2.15.1 supports GHC versions that come with Cabal >= 2.2 (so, LTS >= 12.0). The problem is that `runghc Setup.hs haddock --executables` is broken for Cabal < 3.8.1.0 (so, GHC < 9.4 and LTS < 21.0). Stack would need to warn (and ignore) if `--haddock-executables` was used with a version of GHC that was too old.

**Comment by mpilgrem** [comment]
Implemented in #6508.
