### ISSUE TITLE
Retry build when it yields out-of-memory exit code

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#773]
This happens on travis while building Cabal during a parallel build: https://travis-ci.org/fpco/ide-backend/jobs/73646984#L491

Exit code 9 appears to be an out of memory issue: http://stackoverflow.com/questions/26899426/cabal-update-failure-return-code-9

The temporary fix is to use `-j1`, but this means it takes quite a bit longer to build dependencies.  Ideally, stack would be aware of this condition and retry building the package, without parallelism.

**Comment by snoyberg** [comment]
Why not just have Travis build the Cabal library first, and then build the rest of the codebase in parallel? I'm not in favor of putting in this logic: there's no obvious way to catch the exit code 9 (since it's thrown by GHC, not Cabal, AFAICT), and even if there was, this is outside the scope of build tool territory.

**Comment by mgsloan** [comment]
Good point!
