### ISSUE TITLE
stack 1.3 removes directory-dependent build behavior

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#814]
Given a stack project with multiple package directories

```
a/
b/
```

What is rebuilt with this command?

```
cd b && stack build
```

With stack 1.2,  it was just `b`. With stack 1.3, it is both: I must always run `stack build b` to only rebuild `b`.

My team-mates and I preferred the previous behavior, but we are capable of getting used to the new if that is desired.

**Comment by snoyberg** [comment]
This was one of those "no-win" scenarios, with really good arguments each way. We ultimately did decide on the current behavior, since running `stack build .` is a relatively easy workaround, and the other approach didn't have easy workarounds.

I can't find the issue where it was discussed right now, if it's important let me know and I'll search a bit harder.

**Comment by gregwebs** [comment]
thanks. `stack build .` is not so hard :)
