### ISSUE TITLE
A reason for stack delete/uninstall for libraries/dependencies.

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#829]
See that red squiggly?

![screenshot from 2015-08-21 15 10 28](https://cloud.githubusercontent.com/assets/320177/9418061/ced2465a-4816-11e5-9dda-db3d71716d4a.png)

That's because I have system-uuid and uuid installed in my package database. I'm _only_ using uuid because that's what I replaced system-uuid with, but it complains anyway.

Being able to uninstall it would help. That or flycheck starts paying attention to my stack.yaml snapshots and dependencies. This seems less likely.

**Comment by snoyberg** [comment]
That's really a bug in flycheck, it's perfectly reasonable to have multiple packages with the same module names. You can in fact get rid of such packages with `stack exec ghc-pkg unregister packagename`. But I'm not in favor of exposing this functionality just to work around a limitation in a tool.

A completely different approach by the way is for stack to create a package database with exactly the packages used by the project. That was previously not possible due to limitations in Cabal, by @phadej has fixed that upstream by removing the global package database requirement. That may be coming down the pipeline in the future.

**Comment by bitemyapp** [comment]
@snoyberg fair 'nuff. Thank you.
