### ISSUE TITLE
PATH check should canonicalize paths

### ISSUE THREAD

**Issue by DanielG** [commercialhaskell/stack#840]
I'm getting `Installation path /home/dxld/.local/bin/ not found in PATH environment variable` because `.local` is a symlink on my machine but the target of this symlink is actually on the PATH. I can't be bothered to dig up where this comparison is being made right now but `canonicalizePath` should probably be applied to both sides before checking for equality.

**Comment by snoyberg** [comment]
```
$ grep 'not found in PATH' -rn src/
src/Stack/Build/Execute.hs:336:                , " not found in PATH environment variable"
```

PR welcome, it should be a matter of just `mapM canonicalizePath`, though you should be careful to handle the case where a directory doesn't exist.

**Comment by bollu** [comment]
@snoyberg - This is going to sound silly, but going through the `stack` source code is kind of daunting, since I've never seen "professional" Haskell code before. It would be a great help if you could point to as to where to start from.

**Comment by snoyberg** [comment]
My previous comment gives the relevant filename/line number: `src/Stack/Build/Execute.hs:336`.

**Comment by bollu** [comment]
Yes, I saw that :)

So, well, i wasn't talking about this change - I meant in general, about
how to go through Haskell source when you're unfamiliar with the patterns
and libraries involved.

If it were OO, then I would look for interfaces. Otherwise, in, say,
python, I'd explore types using the interpreter and play with chunks of the
code. I'm not sure what the equivalent is for Haskell.
