### ISSUE TITLE
Allow more command-line options to be specified within stack.yaml

### ISSUE THREAD

**Issue by drvink** [commercialhaskell/stack#846]
Unless I'm missing something, it doesn't seem to be able to set defaults within a stack.yaml for things like `--library-profiling`, `--haddock`, etc. Furthermore, some flags that were available in cabal install are gone entirely (like `--enable-executable-stripping`, just as a random example), and it's not obvious whether there's any workarounds available.

**Comment by drwebb** [comment]
@drvink You could make a PR with additional fields you think are good to have in the `stack.yaml` file. You'll want to start by editing the `Config` datatype in `src/Stack/Types/Config.hs`

Some flags present in cabal-install aren't present in stack, which is because we haven't made it a design goal to replicate every functionality. Starting other issues are good for tracking adding these.

**Comment by lukexi** [comment]
As mentioned in #757, it would be great to have the `modify-code-page` flag available in a config file as it's generally something one needs to set persistently.

**Comment by mgsloan** [comment]
How about having a field called `configure-options`, which has the same format as [ghc-options](https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#ghc-options)?

**Comment by mgsloan** [comment]
@snoyberg @borsboom Are y'all on board with "configure-options"?  See also the discussion here: https://github.com/commercialhaskell/stack/pull/1341#issuecomment-156983972

I wish there was something better for doing this with snapshot dependencies, but that seems like a rather tricky problem to solve.

**Comment by borsboom** [comment]
@mgsloan I think you're mis-reading this issue.  This one is about taking *existing* options (e.g., the various build options) and making it possible to set defaults in stack.yaml.  Adding additional _new_ options (like configure-options) should be a separate issue.

**Comment by borsboom** [comment]
@drwebb, I think you're working on this issue?

**Comment by borsboom** [comment]
Discussion about adding `cabal configure` options: #1438

**Comment by mgsloan** [comment]
I'm imagining this looking like:

```yaml
stack-options: --library-profiling
```

**Comment by charles-cooper** [comment]
@mgsloan Could that result in redundant ways to set command line options? E.g.
```yaml
nix:
  enable: true
```
vs
```yaml
stack-options: --nix
```

**Comment by mgsloan** [comment]
Yes.  `stack-options` would override these.  We might even consider deprecating some of the less used stack.yaml options.  I kinda like just having CLI for the less common things, as then there's one thing to learn instead of potentially 2 (though I think we do a good job of keeping the naming consistent between the two)

Alternatively, we could be sure to make it possible to set every CLI option as a stack.yaml option.

**Comment by charles-cooper** [comment]
Basically, one way or another reifying `BuildOpts` (https://github.com/commercialhaskell/stack/blob/master/src/Stack/Types/Build.hs#L423) and `ConfigMonoid` (https://github.com/commercialhaskell/stack/blob/master/src/Stack/Types/Config.hs#L732)

I don't think people mind learning two sets of options (I certainly don't). It's just confusing when options which affect the build plan aren't available in `stack.yaml`.

**Comment by mgsloan** [comment]
Right, it is certainly an option to just do all the plumbing to get every CLI option available from stack.yaml.  One issue is that the options parsing does do some things a little bit fancier than straight parsing - https://github.com/commercialhaskell/stack/blob/master/src/Stack/Options.hs#L84 .  In order to support the `--profile` and `--trace` flags, we'd need to 

I think it makes sense to make a distinction between options that we want to be part of the project's configuration (part of the repo), and things that are more like development time configuration (now I'm profiling, now I want coverage info, etc).

So, the purpose of this `stack-options:` field would be to allow you to specify development time configuration options in such a way that you don't need to remember to add them to every invocation.  We could even have it say "Warning: Your stack.yaml uses the stack-options field.  You probably shouldn't check it in to your repository, as it's intended to be used for options related to a particular development task".

**Comment by mgsloan** [comment]
In other words, we actually want to discourage people from writing a `stack.yaml` file that enables profiling (and perhaps make it a little less convenient than having an actual field for it), but we do want to allow it.

**Comment by borsboom** [comment]
Ideally, this could go in a "local options" file (e.g. `stack.local.yaml` or something), since it shouldn't be something that would get committed to version control.  Having generalized stack.yaml inheritance would be nice for this (e.g. be able to set any stack.yaml option as overrides in the local file).

**Comment by chrisdone** [comment]
This thread seems to have stalled. Poke!

![](https://media.giphy.com/media/ZlL9U0DNaOdFK/giphy.gif)

With the upcoming `stack hoogle`, always generating haddocks (https://github.com/commercialhaskell/stack/issues/880) is a very desirable property to stick in the global stack.yaml. I'm not convinced we should be considering the command-line options to stack to be the core interface to stack; it's just one UI and the config file is another.

We've already got this in our `~/.stack/config.yaml`:
``` yaml
templates:
  params:
    author-email: chrisdone@gmail.com
    author-name: Chris Done
    category: Web
    copyright: 2015 Chris Done
    github-username: chrisdone
```

And the nix thing someone already mentioned:

``` yaml
nix:
 enable: True
```

Why not also:

```
documentation: 
  enable: True
profiling: 
  enable: True
```

etc. and call it a day?

**Comment by rpglover64** [comment]
This already exists (though IIRC is undocumented):
```
build:
  haddock: true
```

@chrisdone, does that work for you for now?

**Comment by chrisdone** [comment]
It does! :clap::smile: I'll update the other issue.

**Comment by borsboom** [comment]
I wonder if we can close this issue.  Or are there more options we should add than were done by making basically all build arguments settable?  Maybe would be better to have more specific issues than this rather vague one.

**Comment by drvink** [comment]
As the original guilty party for filing this issue, I'm OK with it being closed as long as it's now more or less possible to stash arguments in a persisted config somewhere rather than having to specify them on the command line for every build.

**Comment by mgsloan** [comment]
SGTM, lets open issues for specific CLI things that ought to be settable via configuration.
