### ISSUE TITLE
Rebuild cache problems with multiple projects depending on a shared one

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/stack#855]
There is an unfortunate caching issue I'm hitting on our production projects with stack.

Imagine having this structure:
```
➜  stack-cache-bug  tree -L 2 .
.
├── proj-shared
│   ├── ...
│   └── stack.yaml
├── proj1
│   ├── ...
│   └── stack.yaml
└── proj2
    ├── ...
    └── stack.yaml
```

`proj1` and `proj2` both depend on `proj-shared`, so their `stack.yaml` look like this:

```
➜  stack-cache-bug  cat proj1/stack.yaml
flags: {}
packages:
- '.'
- '../proj-shared'
extra-deps: []
resolver: lts-2.16
```

Now, you build `proj1` and `proj2`, they build just fine. Then, you introduce some new symbol (or a change) in `proj-shared`, and you rebuild `proj1`. Stack notices the change, rebuilds `proj-shared` and `proj1`.

Then, you also use that new symbol in `proj2`, rebuild it (`stack build` inside `proj2` dir), and... you get a type-error:

```
➜  proj2  stack build
proj2-0.1.0.0-94fd113381d8ff555d333eae46ae6dac: unregistering (local file changes)
proj2-0.1.0.0: configure
proj2-0.1.0.0: build

--  While building package proj2-0.1.0.0 using:
      /Users/kb/.stack/setup-exe-cache/setup-Simple-Cabal-1.18.1.5-x86_64-osx-ghc-7.8.4 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.18.1.5/ build lib:proj2 exe:proj2-exe --ghc-options -hpcdir .stack-work/dist/x86_64-osx/Cabal-1.18.1.5/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/kb/workspace/stack-cache-bug/proj2/.stack-work/logs/proj2-0.1.0.0.log

    Configuring proj2-0.1.0.0...
    Preprocessing library proj2-0.1.0.0...
    In-place registering proj2-0.1.0.0...
    Preprocessing executable 'proj2-exe' for proj2-0.1.0.0...
    [1 of 1] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-osx/Cabal-1.18.1.5/build/proj2-exe/proj2-exe-tmp/Main.o )

    app/Main.hs:8:19:
        Not in scope: data constructor ‘SomeNewType2’
        Perhaps you meant ‘SomeNewType’ (imported from LibShared)
```

It doesn't see that `proj-shared` changed.

The worst is that I don't know any better way of invalidating cache than `stack clean`, because after `stack clean` my `stack build` will have to reinstall all local-database packages (the ones which are not in lts), which takes quite some time.

**Comment by borsboom** [comment]
@k-bx: Do you happen to know if this worked better in version 0.1.2.* of stack?  There have been some changes with path handling in the change detection and I'm thinking those may have introduced a regression.

**Comment by k-bx** [comment]
@borsboom I think this is a long-standing bug I had, but I have no problem checking 0.1.2.*, will do.

**Comment by k-bx** [comment]
Reproduced with `0.1.2.2`:

```
➜  proj2  stack build
Warning: /Users/kb/.stack/stack.yaml: Unrecognized field in ConfigMonoid: templates
proj2-0.1.0.0-94fd113381d8ff555d333eae46ae6dac: unregistering (local file changes)
proj2-0.1.0.0: build

--  While building package proj2-0.1.0.0 using:
      /usr/local/bin/runhaskell -package=Cabal-1.18.1.5 -clear-package-db -global-package-db -package-db=/Users/kb/.stack/snapshots/x86_64-osx/lts-2.16/7.8.4/pkgdb/ /var/folders/7l/3ys9j0lx20j6z69lm6s_9r780000gn/T/stack63799/Setup.hs --builddir=.stack-work/dist/x86_64-osx/Cabal-1.18.1.5/ build --ghc-options -hpcdir .stack-work/dist/x86_64-osx/Cabal-1.18.1.5/hpc/.hpc/
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/kb/workspace/stack-cache-bug/proj2/.stack-work/logs/proj2-0.1.0.0.log

    Building proj2-0.1.0.0...
    Preprocessing library proj2-0.1.0.0...
    In-place registering proj2-0.1.0.0...
    Preprocessing executable 'proj2-exe' for proj2-0.1.0.0...
    [1 of 1] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-osx/Cabal-1.18.1.5/build/proj2-exe/proj2-exe-tmp/Main.o )

    app/Main.hs:8:19:
        Not in scope: data constructor ‘SomeNewType2’
        Perhaps you meant ‘SomeNewType’ (imported from LibShared)
➜  proj2  stack --version
Version 0.1.2.2, Git revision 20f6386ec5086d610429d5e8b79d17345aa304ed
```

**Comment by k-bx** [comment]
`0.1.2.0` as well

**Comment by borsboom** [comment]
Thanks for checking, and I think I know what's going on here.  The cache that tracks the state of files to check for dirtiness is within proj-shared's `.stack-work/dist`, but proj1 and proj2 have separate local package databases.  So that means when you build proj2 (in your example), it thinks proj-shared hasn't changed and doesn't rebuild it, but only proj1's local package database was updated and proj2's is still using the older version.

This isn't really a use case we anticipated.  When we want to share code between projects, we handle it with a submodule, so that proj1 and proj2 are self-contained and don't reference anything outside of their working tree.   This means they could use different versions of proj-shared.  In general, that's the best way to get reproducible builds of a project (otherwise you're depending on something that could be different in different poeple's environments).

If we want to support packages with one working tree that's shared between projects, I think each package's `dist` directory would actually need to be stored in the _project_'s `.stack-work` rather than within the package's directory, because otherwise proj1 and proj2's builds of proj-shared would interfere with each other.

@snoyberg, I'd value your opinion here.  In particular, I wonder if this would cause trouble in Windows, where Cabal doesn't support absolute paths for the `dist` directory.  Would it support a relative path like `..
\proj1\.stack-work\distsproj-shared`?

**Comment by snoyberg** [comment]
You hit the nail on the head: cabal bugs on windows are why we didn't do
this initially, even though it's the better design. I'm open to testing
this again though.

**Comment by k-bx** [comment]
So, is this considered to be "by design"? To me this would seem very unfortunate, as:

- this project structure looks quite natural. subfolders with different projects in repository's root, as opposed to putting dependencies in sub-folders. would one need to have multiple copies of shared projects? I don't have full understanding on how things should work properly in current scenario.
- it worked with cabal-install, e.g. it was able to determine that add-source'd project changed

**Comment by snoyberg** [comment]
As mentioned, it's "by design" in the sense that we used this approach as a second-best approach to work around a Cabal bug on Windows. The alternative we initially used is clearly better, and would address this case properly. And also like I mentioned, we can see if there are other ways of working around that bug.

That said: I would recommend against structuring your builds in the way you have them now, since it can present an obstacle to a reproducible build. The success of your build is currently relying on a directory untracked by your version control having the correct commit checked out, and each of your two projects may have different requirements for that. Using either a submodule or tracking the Git commit in the stack.yaml file would be more reliable.

**Comment by k-bx** [comment]
All projects are inside single git repository with no submodules (we migrated to "monorepo" some time ago, since multiple repositories and submodules are a constant pain to work with), so it's always in correct state, sorry if I didn't make it clear. We have a single git repository, which has subdirectories with projects (both, "main" ones, containing executables, and shared libraries). And we'd like to see how can we handle these caching issues in this setup.

**Comment by snoyberg** [comment]
That makes more sense, thanks. Another question: why not just have a single stack.yaml at the root of the repo?

I'm not ignoring the real problem by the way, I'm looking at the relevant source code right now.

**Comment by k-bx** [comment]
@snoyberg I have nothing against having single stack.yaml in repository's root, and actually I had some plans trying that out. It may even help us reducing rebuild-times, as everyone would reuse a single `.stack-work`, as I understand. So I'll definitely check it out.

**Comment by k-bx** [comment]
@snoyberg @borsboom 

Another problem in regards to caching. Running `stack test` after modifying test source doesn't rebuild (just runs old test-executable immediately) if only test-sources changed, not main library. Is this caused by same reasons as per this issue? Or does it have another ticket already? Thanks (and sorry for adding more work, hehe)!

**Comment by snoyberg** [comment]
I'm unaware of this problem, and earlier today I'm fairly certain I saw this working. Can you provide a reproducing test case, preferably in a new issue?

**Comment by k-bx** [comment]
Thanks for info, will try to reproduce in separate repo and create separate ticket in that case.

**Comment by snoyberg** [comment]
I'm just trying to figure out priorities of different issues. Were you able to work around this problem with the combined repo?

**Comment by k-bx** [comment]
@snoyberg we don't have issue anymore. It was resolved by running "stack clean", and we're also migrating to single top-level stack.yaml, but I plan to finish that later a bit. Thanks for asking.
