### ISSUE TITLE
Add a `--dwarf` flag for DWARF debugging

### ISSUE THREAD

**Issue by radix** [commercialhaskell/stack#877]
Say I wanted to build my project with all the debugging options, including stuff like DWARF data. The [page about DWARF support in GHC](https://ghc.haskell.org/trac/ghc/wiki/DWARF) says that you have to pass `-g` to ghc to get it to generate these symbols, but what about all the packages I depend on, and the RTS itself? ("you will need to compile both libraries and the runtime system with debugging support (GhcRtsHcOpts += -g and GhcLibHcOpts += -g).") I guess to make it easy to have a GHC RTS with debugging we'd need bindists that have symbols in them -- I'm not sure if the default 7.10.2 ones have them.

Likewise all this stuff for GHC's profiling options. Is there a way to easily just turn on all profiling options for a project and rebuild everything so I can profile everything?

Maybe this is already pretty easy and this should just be resolved with some documentation in the guide.

**Comment by snoyberg** [comment]
master has support for setting arbitrary ghc-options in your stack.yaml file:

https://github.com/commercialhaskell/stack/wiki/stack.yaml#ghc-options

I can't speak to the settings used by the official bindists, however.

**Comment by radix** [comment]
Thanks for the note. I think it'd be nice to mention this specifically with respect to "debugging" and/or "profiling" in the Guide. (I specifically just did a search for the words "profile" or "debug" in the guide and didn't find one). I'd try to put together a PR (as evinced by the time it took to respond to you on this ticket) I am lacking time.

**Comment by GregorySchwartz** [comment]
I'll write up a brief explaination about using ghc options to profile.

**Comment by gambogi** [comment]
Is this issue still open?

**Comment by borsboom** [comment]
@gambogi The documentation that @GregorySchwartz wrote doesn't address the DWARF case.  I'm guessing it's too early in development for Stack to really support that case well anyway, but I haven't done any research into it (e.g. whether GHC 7.10.2 bindists include DWARF debugging info -- I'm assuming they don't).  The profiling docs that @GregorySchwartz added look good but don't cover using `-fprof-auto` and `+RTS -xc` to get rudimentary stack traces (without DWARF info), so that could potentially be improved as well.

**Comment by christiaanb** [comment]
Just wanted to leave a note as I wanted to use DWARF stack traces. Currently, `--ghc-options="-g"` is not going to work because `stack` strips executables, and there is no way to turn off executable stripping (although the underlying `Cabal` library supports disabling executable stripping).

**Comment by mgsloan** [comment]
I'd be in favor of adding a `--dwarf` flag which builds stuff with the debug symbols and skips stripping.

**Comment by sjakobi** [comment]
I have added a note regarding DWARF support to the docs: https://github.com/commercialhaskell/stack/commit/1c0d5babce0fd9d1dc5fb6032c91742331c7854f

**Comment by mgsloan** [comment]
Bumping to a P1 since I think this would be really handy.  P1 status might get it more attention.

**Comment by tibbe** [comment]
I found myself wanting this today. Turning off stripping would be a good start.

**Comment by SASinestro** [comment]
I've started working on this at SASinestro/stack@f0c9865 a little. I've got something resembling configuration options for it and the actual change itself done, but I'm stuck on how to track what is and isn't built stripped, because GHC unfortunately doesn't seem to track that at first glance. I'm not immediately comfortable doing something hacky with shelling out because it would be different for OS X and Linux (and I can't figure out how to do it on Linux without getting -way- too fuzzy/brittle with my heuristics) and would be completely vestigial on Windows, either. I'll keep working using aforementioned brittle heuristic unless anyone has a better idea, since I need this even if my changes don't get merged.

**Comment by mgsloan** [comment]
@SASinestro Thanks for working on this!  I'm not sure what to do about keeping track of library stripping.  We could possibly store some extra metadata with the installed packages.

**Comment by SASinestro** [comment]
Unfortunately, I don't feel comfortable making a decision about how to handle metadata storage (which is what would be required, there's no way around it, I've been trying for a week) myself.

**Comment by borsboom** [comment]
This reminds me the most of where we're keeping track of libraries that have been built with profiling and/or haddocks, so maybe something similar?

**Comment by SASinestro** [comment]
@borsboom, I was being rather dumb and didn't think about the fact that there's already a place things like this are done. I'm adding it onto `DumpPackage` right now, and it's just some sweeping up left at this point before I can submit a pull request.

**Comment by SASinestro** [comment]
I think that I've got this going. SASinestro/stack@65a70b4

**Comment by mgsloan** [comment]
This has been implemented by @SASinestro - good stuff!
