### ISSUE TITLE
Documentation cleanup

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#900]
We've had a few side discussions floating around, so I wanted to try and congregate a bunch of different documentation ideas into one place:

* In many cases: move Wiki files to the repo itself. (Recommendation: make a `doc/` subdirectory, point old files to that location, and possibly in the future host that `doc/` directory on something like https://readthedocs.org/.)
* Update the CONTRIBUTING.md about:
    * Where documentation is kept, and how to update it
    * Issue tracking behavior
* Possibly add a dedicated document for future improvements (alternatively: keep in a Github milestone)
* Make sure the README.md and Wiki homepage both reflect all of these changes.

I'll likely do some minor parts of this myself if they're non-controversial, but will hold off on any significant changes.

**Comment by borsboom** [comment]
Should we move GUIDE.md into `doc/` (and update any links to it)?

**Comment by drwebb** [comment]
+1 My eyes would look for a doc directory before scanning for the file
manfest for markdown files.

Emanuel Borsboom writes:

> Should we move GUIDE.md into `doc/` (and update any links to it)?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/commercialhaskell/stack/issues/900#issuecomment-137276245

-- 
Tristan Webb PhD
Application Engineer
FP Complete

**Comment by snoyberg** [comment]
Yes, but I'd keep a file in the old location too with a link to the new
location, at least for the next few months.

**Comment by borsboom** [comment]
@kairuku, are you interested in taking a stab at moving additional content from the wiki into main repo?  I did a quick run-through of the pages that exist, and I think:

Should move to repo:
* Architecture
* Build command
* Custom snapshot
* Docker
* stack.yaml

Should stay on wiki:
* Home (but anything it links to not already linked in the README should probably be copied to the README).
* Lowering the bar to open source contributions
* New to Haskell
* Nonstandard project initialization
* Script interpreter
* Signing key (this will go on the new web site once it's ready)
* Stack's origins
* Transition guide

Not sure:
* Checklist
* Downloads
* FAQ
* Shell autocompletion (might be best to copy this content into GUIDE, and leave the old version on the wiki for now with a link to the GUIDE)
* Travis
* Visualizing dependencies with Graphviz (maybe should be copied into GUIDE?)

**Comment by kairuku** [comment]
Sure, I would be interested. As far as the Wiki files specifically, my initial idea had been to *clone* the Wiki repo and *merge* all of it directly into my fork (except Home.md, since README.md could absorb those links). This was primarily to preserve the Wiki edits history (assuming keeping the history is desirable). I've tested this avenue and it seems to work thusfar.

Moreover, assuming the Wiki is truly deprecated now, you *could* put notes around to ask contributors to no longer create/edit Wiki articles, but I don't know offhand of any way to make the Wiki read-only (?). I can't think of a failsafe way to prevent Wiki content from continuing to mutate in parallel to the `/doc` directory, other than disabling the Wiki altogether. Merging all of the Wiki repo into the main repo would also allow for this. In the worst case scenario, a 404 page for someone with an outdated Wiki link would probably compel them to go to the repo home page, and see relevant notes and links in the README. Maybe shutting off the Wiki isn't particularly drastic?

I have further ideas about specific files and such (for example, just placing the signing key directly in the README), but I wanted to get feedback on this primary idea before moving on to others.

**Comment by borsboom** [comment]
That plan sounds fine. 

I think most of my "should stay on wiki" list should either be moved to the web site when it's ready, or be deleted (for those items subsumed by the GUIDE).  Until the web site is ready, maybe we should just leave those on the wiki, but perhaps close it to public edits and suggest contributions by PR instead.  And we can make most of the wiki pages just contain a link to the `doc/` directory in the main repo, for now, and eventually delete it.

**Comment by snoyberg** [comment]
@borsboom I think this issue can be closed
