### ISSUE TITLE
Stack should not repeatedly warn about unlisted modules

### ISSUE THREAD

**Issue by ezyang** [commercialhaskell/stack#913]
Whenever I run stack build, I get this error:

```
[ezyang@hs01 Cabal]$ stack build Cabal 
Warning: modules not listed in cabal-install.cabal for 'unit-tests' component (add to other-modules):
    Distribution.Client.BuildReports.Anonymous
    Distribution.Client.BuildReports.Storage
    Distribution.Client.BuildReports.Types
    Distribution.Client.Compat.ExecutablePath
    Distribution.Client.Compat.FilePerms
...
Cabal-1.23.0.0: build
```

Yes, I should fix this. But Stack should only complain when CONFIGURING, not on every build.

**Comment by borsboom** [comment]
This isn't trivial, because it requires an actual build to find the unlisted packages (the required information doesn't exist at configure time, as it's generated by GHC during the build).  I think the warnings are also useful during normal builds, because if you add a new unlisted dependency, that won't trigger a new configure step (modifying the .cabal file would, but that's what you forgot to do!), which can then lead to confusing linker errors.

My suggestion: fix the warnings when they come up.  It's good that they're annoying :)

**Comment by ezyang** [comment]
But... I'm not even building unit-tests?

**Comment by borsboom** [comment]
Ah, missed that bit in the output you pasted.  Since these warnings are generated by the code that checks for dirty files, I'm thinking it might be nice if the dirtiness checking skipped any components that aren't being built.  Which is probably a bit complicated, I guess we'd have to cache that information from the time it was configured (if the .cabal file or flags changed since last cache, it'd revert to the current behaviour).

I'm going to be doing some significant digging around in this code in the near future anyway, so while I'm doing so, I'll see if there's a  way to improve the situation that doesn't add *too* much complexity.

**Comment by chrisdone** [comment]
I'm just fixing a related bug in this part of the codebase so hold up on that

I actually think the dirtiness check part should be easy as you receive the file set as a `Map NamedComponent (Set DotCabalPath)`, so you can just filter on the components.

**Comment by chrisdone** [comment]
Okay, done on my fixes.

**Comment by mgsloan** [comment]
This seems to be fixed in the development version of stack, possibly in a release as well.  Closing!
