### ISSUE TITLE
Why release tarballs that contain only a single file?

### ISSUE THREAD

**Issue by peti** [commercialhaskell/stack#973]
Download links like https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-i386-linux.tar.gz refer to a tarball since release 1.4.x, but that tarball contains only a single file. What's the point? Why not release just a gzip-compressed executable, like it was done for earlier versions?

**Comment by borsboom** [comment]
We got complaints about the extracted file's permissions being incorrect and having a weird filename (that's because a gzip doesn't know anything about permissions or original filename).  There was some discussion about adding the README to the tarball in https://github.com/commercialhaskell/stack/pull/853, but it wasn't clear that would be an improvement, so I just merged it as it was.

**Comment by peti** [comment]
OK. I suppose there is no way to make everyone happy. Thank you for the quick response.
