### ISSUE TITLE
This HaskellR issue may be a problem with stack's docker support. 

### ISSUE THREAD

**Issue by michaelochurch** [commercialhaskell/stack#999]
This is a cross-post of [an issue](https://github.com/tweag/HaskellR/issues/207) that I've discovered on the HaskellR project when trying to install it on OS X. 

Below is a shell session. This might not be stack's fault at all, but I thought it might be useful for the stack team to look at it? Please forgive me if this turns out not to be useful or interesting; I'm posting it on the chance that it is pertinent to stack and not a problem with HaskellR. 

```
$ stack --docker build
The Docker image referenced by stack.yaml has not
been downloaded:
    tweag/haskellr:latest

Run 'stack docker pull' to download it, then try again.
$ stack docker pull
Pulling image from registry: 'tweag/haskellr:latest'
FATA[0000] Post http:///var/run/docker.sock/v1.18/images/create?fromImage=tweag%2Fhaskellr%3Alatest: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
Could not pull Docker image:
    tweag/haskellr:latest
There may not be an image on the registry for your resolver's LTS version in
stack.yaml.
```

**Comment by borsboom** [comment]
Stack's Docker support requires the Docker client and the Docker Engine to be running on the same host.  That effectively means it only works on Linux 64-bit, since that's the only platform Docker Engine runs on.  See https://github.com/commercialhaskell/stack/wiki/Docker#prerequisites for more information about the prerequisites for `stack --docker`.  https://github.com/commercialhaskell/stack/issues/194 is tracking adding support for non-Linux platforms.
